### ISSUE TITLE
Project file for compilation options

### ISSUE THREAD

**Issue by iljio** [teal-language/tl#103]
Hello,

I noticed that `tl` currently doesn't have a lot of options, like choosing an output directory or anything like that. Continuing that thought, I felt like the existence of further options might warrant a project file altogether, similar to `tsconfig.json` for TypeScript.

If I were to expect how such a project file would look, I would expect something along the lines of:
```
-- tlconfig.lua
return {
  directories = {
    input:    {"src/**/*.tl"},
    include:  {"lib/**/.*.lua"},
    output:   "dist"
  },
  flags = {
    transpiler = {
      save_sourcemaps = true,
      keep_comments   = true,
      check_requires  = true
    },
    warnings = {
      unused_variables  = true,
      unknown_variables = false
    },
    errors = {
      const_reassignment = true
    },
    compatibility = {
      version = "5.1"
    }
  },
  plugins = {
    "prettifier-5.1",
    "switch",
    "lambda"
  }
}
```

Of course, I'm just describing what it might look like, not implying that tl has to implement anything like plugins. (Although, the idea of a tl plugin sounds kind of neat...)

**Comment by pdesaulniers** [comment]
Actually, `tl` already has support for a `tlconfig.lua` file, although it's not advertised anywhere :)

For the time being, these two keys are supported:

```lua
return {
	include = { -- add these directories to LUA_PATH and LUA_CPATH; matches the -I command line option
		"folder1/",
                "folder2/"
	},
        preload_modules = { -- execute the equivalent of require('modulename') before executing the tl script(s); matches the -l command line option
                "my.module",
                "my.other.module"
        }
}
```
I agree that `tlconfig.lua` (and the command line tool) should support something like the `input` and `output` keys in your example. I've opened some issues about this:

Input: https://github.com/teal-language/tl/issues/31
Output: https://github.com/teal-language/tl/issues/47

If ever you want to take a stab at implementing these features, you might want to look at this PR which adds support for the `include` key: https://github.com/teal-language/tl/pull/94

**Comment by hishamhm** [comment]
> Actually, tl already has support for a tlconfig.lua file, although it's not advertised anywhere :)

Time for a `docs/tlconfig.md`? :grin:

**Comment by pdesaulniers** [comment]
Instead, I think I would add `docs/compiler_options.md`, which would describe both `tlconfig.lua` and compiler switches.

**Comment by hishamhm** [comment]
Since the project file already exists, I think we can close this one!
