### ISSUE TITLE
Documentation request: Using tl as a library

### ISSUE THREAD

**Issue by bedax** [teal-language/tl#105]
Hello, it would be useful if it was documented as to how `tl` can be used as a library to generate lua code/bytecode. I can get a rough idea of the process by reading the `tl` script, but an official word on how to do it properly would be useful.

Great work so far btw

**Comment by hishamhm** [comment]
@bedax Hi, and welcome!

If you want to do is to be able load Teal code and run it as Lua, it is as easy as:

```lua
-- in your_program.lua:

local tl = require("tl")
tl.loader()

-- now you can require Teal files and they work as Lua modules
local my_teal_module = require("my_teal_module") -- this loads my_teal_module.tl

```

This will install a package loader that equips Lua's standard `require()` with the ability to load `*.tl` files from Lua's standard `package.path`.

Does that help?

**Comment by bedax** [comment]
That's brilliant, thank you @hishamhm! I now see that's in the tutorial, apologies for the unnecessary ping :+1:
