### ISSUE TITLE
cannot add undeclared function 'test_count' outside of the scope

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#106]
i'm using luaunit to write tests https://luaunit.readthedocs.io/en/luaunit_v3_2_1/

`luaunit.d.tl`

```
global luaunit_runner_t = record
    setOutputType: function(luaunit_runner_t, string)
    runSuite: function(luaunit_runner_t, any): number
end

global luaunit_t = record
    new: function(): luaunit_runner_t
end

local luaunit = record
    LuaUnit: luaunit_t
    assertIsTrue: function(any)
end

return luaunit
```

`tests.tl`

```
local lu = require("luaunit")
local os = require("os")

-- it must be global to use luaunit
global TestSuite = {}

function TestSuite:test_count()
    lu.assertIsTrue(100 == 200)
end

function main(args: any)
    local runner = lu.LuaUnit.new()
    runner:setOutputType("tap")
    local code = runner:runSuite(args)
    os.exit(code)
end
```

however, `tl check` told me

> cannot add undeclared function 'test_count' outside of the scope where 'TestSuite' was originally declared

but they are in the same file?

if i use `local TestSuite = {}`, `tl check` can pass, but luaunit will not work

**Comment by pdesaulniers** [comment]
I think this commit can shed some light on this issue: https://github.com/teal-language/tl/commit/0039676ae6307d1f68b7cf0093e290df22352d69

For the time being, you have to forward declare the function:
```lua
global TestSuite = record
	test_count: function(self: TestSuite)
end
```

**Comment by hishamhm** [comment]
> @hishamhm I believe the limitation for extending records should be per file, and not per scope. This behavior is kinda confusing, and #39 will still pop up when using local records instead of global ones.

I will give this a thought! Per-file restrictions tend to bite back later, and in any case the above behavior presented by @virusdefender is a bug, since the declaration is clearly in the same scope.

**Comment by pdesaulniers** [comment]
As mentioned on Gitter, I'm fine with per-scope limitations after all. I only misunderstood the expected behavior of this feature.

Here is another case where this feature misbehaves. It allows extending the record outside of its original scope:

widget.tl
```lua
local Widget = record
    draw: function(self: Widget)
end

return Widget
```

main.tl
```lua
local Widget = require("widget")

function Widget:totally_unrelated_function()
    print("heyo")
end
```

**Comment by hishamhm** [comment]
I made adjustments to the logic for detecting the scopes, keeping track of open lexical scopes. Both cases should now be handled correctly (the example from @virusdefender in the original issue now works with the `global`, and the example from @pdesaulniers now fails as it should)!
