### ISSUE TITLE
Missing dependency - argparse

### ISSUE THREAD

**Issue by hughjfchen** [teal-language/tl#123]
After having installed `tl` with `luarocks`, I got an error says `no argparse` module found when trying to run the `tl` command. After install `argparse` module with `luarocks`, I can run the `tl` command without any problem. Could you please add the `argparse` as a dependency in the `rocksspec`?

**Comment by hishamhm** [comment]
@hughjfchen Thank you for the heads up! I just pushed a new revision of the 0.4.2 rockspec including the dependency.
