### ISSUE TITLE
Support for type definitions without using `require`?

### ISSUE THREAD

**Issue by dnchu** [teal-language/tl#125]
Is it possible to create a type definition for an API that exposes itself in the global scope? For example, the game Minetest allows items to be registered like so:

```lua
minetest.register_craftitem("default:diamond", {
	description = "Diamond",
	inventory_image = "default_diamond.png",
})
```

**Comment by pdesaulniers** [comment]
Sure! You can define a global record and preload it using [either a compiler switch or a `tlconfig.lua` file](https://github.com/teal-language/tl/blob/master/docs/compiler_options.md#project-configuration).

So, for your use-case, I would create `minetest.d.tl` with the following content:
```lua
global minetest = record
    CraftItemOptions = record
        description: string
        inventory_image: string
    end

    register_craftitem: function(string, CraftItemOptions)
end
```
...and create a `tlconfig.lua` file with the following content:
```lua
return {
    preload_modules = {
        "minetest"
    }
}
```

**Comment by hishamhm** [comment]
Closing this, since the question was solved! :grin:
