### ISSUE TITLE
Add integer type

### ISSUE THREAD

**Issue by luauser32167** [teal-language/tl#127]
When the type _number_ is used for a declaration it could mean either a floating-point or an integer. This can lead users to second guess or force them to read the documentation more carefully. C APIs often expect integers. There are also a few standard library Lua functions that return/take integers (_math.floor_, _string.sub_, etc).

Adding an integer type can improve the understandability/self documentation of code and allow the compiler to catch more errors.

**Comment by hishamhm** [comment]
I have thought a lot about this, but the technical hurdle is that Teal currently targets both PUC-Rio Lua 5.3+ (which has a first-class integer type defined as a subtype of number) and moonjit/LuaJIT (which has a second-class integer type defined as a FFI cdata — you can't use integer literals effectively as table keys).

We could implement "integer" as a mere set of restrictions over operations over numbers, but I'm afraid naming a type "integer" would cause people to assume both 64-bit integer precision and by-value semantics like regular numbers, which is easier to achieve cleanly in PUC-Rio Lua than in moonjit/LuaJIT.

**Comment by catwell** [comment]
For what it's worth I was thinking about creating a similar issue. I don't know how to solve the LuaJIT issue but for PUC Lua that would make a lot of sense.

Related: I have made [a PR adding support for integer division](https://github.com/teal-language/tl/pull/274).

**Comment by lenscas** [comment]
maybe instead of calling it `integer` and `number` we have `number`and `wholeNumber` or `numberRestrictedWhole`, `number.nodecimal` or something along those lines. 

Reduces the chance on name collisions and the fact that it isn't the normal name hopefully leads people to at least look at the documentation once on what it is, thus they are made aware of the fact that it isn't a true integer. By including the `number` in the type the type also draws attention that it is just a more restricted version of `number` and not really its own type.

**Comment by hishamhm** [comment]
Thinking more about this subject, I'm changing my mind and finding it less problematic to have an `integer` type that merely introduces restrictions over number operations for the purposes of type checking but gives no precision guarantees. I'm thinking this can't make the current situation really worse, given that there are already semantic differences whether you pick PUC Lua or LuaJIT as runtime targets:

```
$ luajit -e 'print(_VERSION); print(math.floor(2^53) + 1 ~= math.floor(2^53))'                              
Lua 5.1
false
$ lua -e 'print(_VERSION); print(math.floor(2^53) + 1 ~= math.floor(2^53))'        
Lua 5.3
true
$ cat precision.tl
print(math.floor(2^53) + 1 ~= math.floor(2^53))
$ luajit ./tl run precision.tl
false
$ lua ./tl run precision.tl
true
```

(That doesn't prevent us from leaving the door open to introduce someday an `integer64` type which _did_ provide precision guarantees for Lua 5.3+ and LuaJIT. It would probably need some restrictions for the sake of LuaJIT, which is unfortunate.)

So yeah, an unspecified-precision `integer` type, defined as a subtype of `number`, could be interesting.

**Comment by hishamhm** [comment]
Yay, this feature has shipped!
