### ISSUE TITLE
Handling Userdata

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#133]
This is mostly for \*.d.tl purposes:

Since userdata is one of the primitives in Lua it feels a little odd to use a record to create a new type instead of having a mechanism to handle it.

When working with C libraries it would be nice to be able to label/describe the userdata's properties and methods instead of creating a new type with a record. But since records are already a decent way of describing userdata, maybe add some way of preserving the actual userdata primitive type (`foo is userdata` would generate `type(foo) == "userdata"`).
Maybe some sort of userdatatype (analogous to functiontype) or userdata block
`local Socket = userdata --[[ ... ]] end`
`local Socket = userdatatype`

Perhaps #124 could be adapted for this purpose:
```
local Socket = record is userdata
   -- ...
end
```
where we could tag a record as describing some userdata.

I'm not exactly sure if this is the best way to handle this, but the idea came up when writing a .d.tl file for luasocket (and dependencies) where I had a few userdata types that just needed distinct names like so:
(Edit: apparently in ltn12 these are functiontypes, but I think the point still stands)
```
local ltn12 = record
   Filter = record end
   Sink = record end
   Source = record end
   --[[ ... ]]
end
```
and I'm not sure how I feel about having empty record blocks just to give a type a distinct name.
Since these particular types don't have any metamethods and are just passed to and from the library functions they don't need any properties. So something like this
```
local ltn12 = record
   Filter = userdata
   Sink = userdata
   Source = userdata
   --[[ ... ]]
end
```
would suffice for this case. Although I don't know about the more general case.

**Comment by hishamhm** [comment]
Those are all great points. Just like for records, the key issue about identifying different kinds of userdata is how to tell them apart at runtime when using union types. Generally userdata of the same "type" will have the same metatable or some other identifying method. I'm considering the possibility that this identifying method will have to be user-definable for different libraries.

**Comment by euclidianAce** [comment]
Yeah, I'm starting to fully realize the complexity of this sort of thing and that the problems are more related to runtime checking than I initially thought

**Comment by euclidianAce** [comment]
I believe #307 is enough to close this
