### ISSUE TITLE
how to define return different type value funtion

### ISSUE THREAD

**Issue by cloudfreexiao** [teal-language/tl#134]
i have one use case like this
```lua
local function read_table(list)
   local result = {}
   for i = 1, #list, 2 do
      result[list[i]] = list[i + 1]
   end
   return result
end      

local db = redis.connect(conf)
print("test table")
local ret = db:pipeline({
	{"hincrby", "hello", 1, 1},
	{"del", "hello"},
	{"hmset", "hello", 1, 1, 2, 2, 3, 3}, 
	{"hgetall", "hello"},
}, {})	-- offer a {} for result

print(ret[1].out) -- number
print(ret[2].out) -- number
print(ret[3].out) -- string

for k, v in pairs(read_table(ret[4].out)) do -- list
	print(k, v)
end
```
the redis pipeline offer a list for result but the list element has different type 
how to define the pipeline function 
thanks!!

**Comment by pdesaulniers** [comment]
Which redis library is this?

According to your explanation, it seems like this would be a job for [union types.](https://github.com/teal-language/tl/blob/72e08a01a78685f13e6c446461afa98ec17b295e/docs/tutorial.md#union-types) However, these have a couple of [limitations](https://github.com/teal-language/tl/blob/72e08a01a78685f13e6c446461afa98ec17b295e/docs/tutorial.md#current-limitations-of-union-types) right now.

Based on your example, this is the best I could come up with:

```lua
local redis = record
	Config = record

	end
	
	Database = record
		PipelineResponse = record
			out: number | string | {any}	
		end

		pipeline: function(self: Database, commands: {{string | number}}, ret: {PipelineResponse}): {PipelineResponse}
	end

	connect: function(conf: Config): Database
end

local db = redis.connect({})

local ret = db:pipeline({
	{"hincrby", "hello", 1, 1},
	{"del", "hello"},
	{"hmset", "hello", 1, 1, 2, 2, 3, 3}, 
	{"hgetall", "hello"},
}, {})	-- offer a {} for result

print(ret[1].out) -- number
print(ret[2].out) -- number
print(ret[3].out) -- string

local list = ret[4].out

if list is {any} then
	for k, v in ipairs(list) do -- list
		print(k, v)
	end
end
```

I'm not sure about the type of `ret[4].out` in your example, so I wrote `{any}`.

**Comment by cloudfreexiao** [comment]
the redis library is from 
[redis lib](https://github.com/cloudwu/skynet/blob/master/lualib/skynet/db/redis.lua)
[redis use example](https://github.com/cloudwu/skynet/blob/master/test/testpipeline.lua)
