### ISSUE TITLE
tl gen not actually type checking?

### ISSUE THREAD

**Issue by 3uclidian** [teal-language/tl#138]
The readme states that
> `tl gen module.tl` will type check a Teal module, and if there's no errors, generate a module.lua file in plain Lua with all type annotations stripped.

but `tl gen` seems to create a .lua file no matter what errors `tl check` reports. For example:
```
-- foo.tl
local a: number = "hi"

local function foo(): string
	return 3
end

global b = a + foo()

```
Produces a bunch of type errors as expected
```
$ tl check foo.tl
========================================
3 errors:
foo.tl:2:19: in local declaration: a: got string "hi", expected number
foo.tl:5:9: in return value: got number, expected string
foo.tl:8:14: cannot use operator '+' for types number and (string)
```
but still produces a .lua file, which seems wrong.
```
$ tl gen foo.tl
Wrote: foo.lua
```
Is this intentional? Is there some sort of strict setting that I turned off? Or does it mean that `tl gen` should only be used for libraries and scripts should be run with `tl run`?
If it's intentional then the readme should maybe be updated to say if there are no _syntax_ errors a file will be generated.

**Comment by hishamhm** [comment]
Yes, it was deliberate. The point was to not prevent programs from running while typing is a work-in-progress.

> If it's intentional then the readme should maybe be updated to say if there are no syntax errors a file will be generated.

Agreed!

**Comment by luauser32167** [comment]
'tl gen' still doesn't seem to type check, but the README.md reads:

> ```tl gen module.tl``` will type check a Teal module, and if there's no syntax errors, generate a module.lua file in plain Lua with all type annotations stripped.

**Comment by hishamhm** [comment]
oops!

I'm thinking this will need to change in the near future, though, because it's likely that we'll end up needing the type information to generate proper code for `is` once it does anything smarter than `type(v) == "..."`
