### ISSUE TITLE
complete typing definitions of the Lua standard library

### ISSUE THREAD

**Issue by hishamhm** [teal-language/tl#14]
The definitions of `standard_library` in `tl.tl` are not complete.

I've been adding them on an "as-needed" basis, but all definitions for Lua 5.3 (which would be a good starting point for a tl standard library) are not there yet.

An easy way to help with development is to add more entries to that table with the missing functions. It shouldn't be hard to write down the types of most functions by following the examples of the ones that are already there.

**Comment by mwild1** [comment]
This probably falls under this issue, but I encountered a problem with string.match. The third parameter is not covered in the spec. Easy fix, but there is also an issue with return values (which can be numbers). Not sure how that should be handled.

**Comment by hishamhm** [comment]
@mwild1 Thanks! Input argument fixed in 7b188c09d7433e6d35674da393432c9bb7c85ae9 — the output argument is tricky, the output types depend on the contents of the input argument (yay for dependently typed languages!) — since most patterns in real-world Lua code are literals, we could do what gcc and others do for things like `printf` and handle this magically (actually read the literal looking for captures, and just give up if the pattern argument is not literal). I'm not opposed to adding some magic for the standard library. I already have some for things like `rawget`.

**Comment by darrenjennings** [comment]
@hishamhm is there a link to the list of `standard_library` functions so we could take inventory?

**Comment by hishamhm** [comment]
@darrenjennings I think this is the authoritative source for the latest Lua:
https://www.lua.org/manual/5.4/contents.html#index

There have been various PRs contributed by the community adding more functions to the `standard_library` definitions. At this point I don't even know if it is already complete or not. :)

**Comment by hishamhm** [comment]
one slightly annoying thing is that the specification of the arguments and return types in the reference manual is written in English, and can be vague sometimes.

I believe @andremm and @mascarenhas had a pretty complete definition of the standard library in the Typed Lua format -- not the same syntax as Teal's, but it's a more formal spec than the reference manual.

https://github.com/andremm/typedlua/tree/master/typedlua/lsl53

**Comment by hishamhm** [comment]
I think the standard library defs are complete by now? If there are still any omissions we can reopen an issue.
