### ISSUE TITLE
How are type files supposed to work/be used?

### ISSUE THREAD

**Issue by factubsio** [teal-language/tl#140]
I am writing some code that is currently all in one file, everything is great, I am happy!

I'm trying to pull some of the type defs for the API I am consuming out into a `.d.tl` file to gear up for splitting my monolithic file into modules.

I don't understand how they are supposed to work and there seems to be little documentation - is this replicating some other language's behaviour (e.g. typescript)?

I have a `control.tl`

I moved some typedefs into `factorio.d.tl`

Am I supposed to `local factorio = require("factorio")` in my `control.tl`?

This then breaks because in `factorio.d.tl` types are not prefixed, i.e. I refer to a `LuaSurface`, not a `factorio.LuaSurface` but this then breaks in `control.tl` because it can't find a type def for `LuaSurface`

I suspect I am doing this entirely wrong, any docs would be greatly appreciated!

Thanks for the stuff so far, makes using lua way less painful. :-)

**Comment by pdesaulniers** [comment]
As mentioned in [the tutorial](https://github.com/teal-language/vscode-teal/blob/1985c89ed5f2572e119b4125eb4ba278be276eb9/server/server.ts#L240) at the bottom:

> If you create a file with the .d.tl extension, that will be used as a source of type information when type checking with tl check, even though the real Lua module will be loaded instead when requiring the module from Lua or tl run.

So yes, you should do `local factorio = require("factorio")` (or, if this module is exposed as a global, you should preload it instead; see https://github.com/teal-language/tl/issues/125)

> This then breaks because in factorio.d.tl types are not prefixed, i.e. I refer to a LuaSurface, not a factorio.LuaSurface but this then breaks in control.tl because it can't find a type def for LuaSurface

Perhaps you are defining `LuaSurface` as a local record? This means that the type won't be exported by your module (at least, by default).

There are a couple of ways that you can export the type from your module. You can use nested records:

```lua
local factorio = record
    LuaSurface = record

    end

    -- insert more stuff here
end

return factorio
```

```lua
local factorio = require("factorio")

local x: factorio.LuaSurface = nil
```

Alternatively, you can also make that type global:
```lua
global LuaSurface = record

end
```
```lua
local factorio = require("factorio")

local x: LuaSurface = nil
```

**Comment by factubsio** [comment]
> As mentioned in [the tutorial](https://github.com/teal-language/vscode-teal/blob/1985c89ed5f2572e119b4125eb4ba278be276eb9/server/server.ts#L240) at the bottom:
> 
> > If you create a file with the .d.tl extension, that will be used as a source of type information when type checking with tl check, even though the real Lua module will be loaded instead when requiring the module from Lua or tl run.
> 
> So yes, you should do `local factorio = require("factorio")` (or, if this module is exposed as a global, you should preload it instead; see #125)
> 

Ok gotcha that makes sense - I guess the wording in the tutorial is correct, but I only understand it now I've read it several times. 🤷 

> > This then breaks because in factorio.d.tl types are not prefixed, i.e. I refer to a LuaSurface, not a factorio.LuaSurface but this then breaks in control.tl because it can't find a type def for LuaSurface
> 
> Perhaps you are defining `LuaSurface` as a local record? This means that the type won't be exported by your module (at least, by default).
> 
> There are a couple of ways that you can export the type from your module. You can use nested records:
> 
> factorio.d.tl
> 
> ```lua
> local factorio = record
>     LuaSurface = record
> 
>     end
> 
>     -- insert more stuff here
> end
> 
> return factorio
> ```
> 
> control.tl
> 
> ```lua
> local factorio = require("factorio")
> 
> local x: factorio.LuaSurface = nil
> ```
> 
> Alternatively, you can also make that type global:
> 
> factorio.d.tl
> 
> ```lua
> global LuaSurface = record
> 
> end
> ```
> 
> control.tl
> 
> ```lua
> local factorio = require("factorio")
> 
> local x: LuaSurface = nil
> ```

Ace, thanks. I think in this case "global" is probably the correct thing to do, given it should be "magically present" in all scripts at runtime.

Thanks for the quick response, much appreciated!

It might be worth putting a small example in the tutorial (I could do a PR?)

**Comment by pdesaulniers** [comment]
Yes, I think that would be great!

**Comment by factubsio** [comment]
👍  will do!

**Comment by factubsio** [comment]
> Yes, I think that would be great!

Started a discussion here:

https://github.com/teal-language/tl/pull/143/
