### ISSUE TITLE
Operator precedence is not same with lua ?

### ISSUE THREAD

**Issue by yjhmelody** [teal-language/tl#152]
```
     or
     and
     is
     <     >     <=    >=    ~=    ==
     |
     ~
     &
     <<    >>
     ..
     +     -
     *     /     //    %
     unary operators (not   #     -     ~)
     ^
     as
```

I write some demos found that precedence of `>>` and `<<` are greater than logical op.
What's the reason?

**Comment by hishamhm** [comment]
The precedence list above is lower to higher (as is the one in the Lua reference manual), so the precedence of `<<` and `>>` _are_ higher than the logical operators `and` and `or`:

```
$ cat prec.lua

local x = 2 << 1 > 10 and 2 << 4 or 2 << 20
print(x)

$ lua prec.lua
2097152

$ tl run prec.lua
2097152
```

**Comment by yjhmelody** [comment]
I got it wrong maybe.
