### ISSUE TITLE
Crash when wrapping coroutine.resume and annotating the return type

### ISSUE THREAD

**Issue by luauser32167** [teal-language/tl#160]
local function foo1(): (boolean, any) return coroutine.resume(nil) end -- ok
local function foo2(): (boolean, string) return coroutine.resume(nil) end -- not ok
-- local function foo3(): (boolean, notany) return coroutine.resume(nil) end -- not ok

error: ```tl:137: attempt to concatenate a nil value (field 'x')```

**Comment by euclidianAce** [comment]
Suppressing the parsing errors, (apparently tl gets lost along the way), this will produce the correct error of `got <any type>, expected string`.
Working with coroutines is going to come with a bit of manual casting.

```
local function foo(): boolean, string
   local a, b = coroutine.resume(nil)
   return a, b as string
end
```

**Comment by hishamhm** [comment]
Thank you @luauser32167 for the report and @euclidianAce for the explanation :)

**Comment by hishamhm** [comment]
The crash is now fixed in `master`!
