### ISSUE TITLE
Parser confusion by unpaired 'end' token

### ISSUE THREAD

**Issue by luauser32167** [teal-language/tl#166]
```lua
print('A')

 -- lines after this unpaired 'end'
 -- are not emited to '<filename>.lua' after 'tl gen'
 -- only lines above it
end

print('you won\'t find this in')
print('<filename.lua>')
print('<after a tl gen>')
```
I.e the "unpaired" end token acts as the '\_\_END\_\_' token from Perl :^)

**Comment by hishamhm** [comment]
oops, my `parse_statements` function was trained to stop at `end` because I use it recursively to parse nested blocks, so it was too smart for its own good at the top level!
