### ISSUE TITLE
How to use table.unpack() in .tl?

### ISSUE THREAD

**Issue by paintdream** [teal-language/tl#168]
I've tried:

```
local s = { 1234, "5678", 4566 }
local a, b, c = table.unpack(s) as number, string, number 
```

But it seems that tl trying to assign two variables named "string" and "number" to b and c. As a result, tl reported "number" was not declared:

`main.tl:2:52: unknown variable: number`

**Comment by cloudfreexiao** [comment]
```lua
local testType = record
	{any}
end

local s = { 1234, "5678", 4566 } as testType
table.unpack(s)
```

**Comment by cloudfreexiao** [comment]
I try to fix this case but not sure is right way to resolve it
```lua
local testType = record
	a: number
	b: string
	c: number
end

local s = { 1234, "5678", 4566 }
local t = table.unpack(s) as testType
local a: number = t.a 
local b: string = t.b
local c: number = t.c
```

**Comment by paintdream** [comment]
> I try to fix this case but not sure is right way to resolve it
> 
> ```lua
> local testType = record
> 	a: number
> 	b: string
> 	c: number
> end
> 
> local s = { 1234, "5678", 4566 }
> local t = table.unpack(s) as testType
> local a: number = t.a 
> local b: string = t.b
> local c: number = t.c
> ```

Meanwhile, table.unpack returns ..., not a table. Expanding to var args is required.

**Comment by paintdream** [comment]
> Right now there's no pretty way of doing this, I need to add support for tuples in casts. For now I think this should work:
> 
> ```lua
> local a, b, c: any, any, any = table.unpack(s)
> local a = a as number
> local b = b as string
> local c = c as number
> ```
> 
> edit: actually, even without the `: any, any, any`, I guess!

Thanks~

**Comment by hishamhm** [comment]
Now this works in the `master` branch, and the following works (note that parentheses are mandatory for casting multiple values at once):

```lua
local s = { 1234, "5678", 4566 }
local a, b, c = table.unpack(s) as (number, string, number)
```
