### ISSUE TITLE
how to define subclass in *.d.tl 

### ISSUE THREAD

**Issue by cloudfreexiao** [teal-language/tl#173]
some code like this how to define the Lemon type ?
```lua
local Fruit = record
end

-- Lemon is Fruit subclassing 
local Lemon = record
end

```

**Comment by pdesaulniers** [comment]
Currently, there is no mechanism for this. However, [this PR](https://github.com/teal-language/tl/pull/124) implements tagged records, which may be used to create subtypes:

```lua
local Fruit = record
   tag fruit_type: string
end

local Lemon = record is Fruit with fruit_type = "lemon"
end
```

**Comment by hishamhm** [comment]
Let's close this as a duplicate of #97, to avoid having the same topic spread across various issues. @cloudfreexiao See you there!
