### ISSUE TITLE
Add a tuple-table type

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#181]
Probably with a different name since tuples are sort of already an internal thing.

It would be nice to have a tuple-like type where it is just a table where you can annotate the integer indices (and maybe assert the length? but that would require non-nilable types)

For example when capturing a function's return values in a table
```lua
local pd = io.popen("...")
-- ...
local foo: [boolean, string, number] = {pd:close()}
-- This idea came up when writing tests for Teal and doing this sort of thing
```
not sure about syntax, but would make some things more convenient

**Comment by hishamhm** [comment]
This is very much a valid type idea, like arraymap. The more table types we add, the more careful we need to be about their interactions, so I like to give some time to think them through. This one is not at the top of my priorities right now, but let's keep this issue open and see what response it gets — thank you for bringing it up!
