### ISSUE TITLE
Named return values?

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#185]
Sometimes, functions that return multiple values have an unclear signature, because the return values don't have a name:

```lua
parse_expression = function(ps: ParseState, i: number): number, Node, number -- 'number' by itself doesn't provide much information
```

Could we actually allow named return values, [like in Go](https://tour.golang.org/basics/7)?

```lua
parse_expression = function(ps: ParseState, i: number): (i: number, lhs: Node, exitcode: number)
      i, lhs = P(ps, i)
      i, lhs = E(ps, i, lhs, 0)
      if lhs then
         return i, lhs, 0
      else
         return fail(ps, i, "expected an expression")
      end
end
```

In my example, the following Lua code would be generated:
```lua
parse_expression = function(ps, i)
      local lhs
      local exitcode -- unused, so not really necessary
      -- the `i` return value would shadow the `i` argument, so I guess it shouldn't be generated
      i, lhs = P(ps, i)
      i, lhs = E(ps, i, lhs, 0)
      if lhs then
         return i, lhs, 0
      else
         return fail(ps, i, "expected an expression")
      end
end
```

I'm not actually sure if it's a good idea, but it's something that came to my mind a couple of times.

**Comment by hishamhm** [comment]
Go mandates a return value at the end of the function. Lua allows skipping it to return nil(s). Other languages that have named return values without mandatory `return` exits (e.g. Pascal) make that return at the end implicit (the return value of the function is whatever the return of the return variable is).

If we were to add named return values that auto-declare variables, we would probably have to start checking and mandating explicit `return` variables.

I'm not sold on the idea, just sharing initial thoughts.

**Comment by pdesaulniers** [comment]
Honestly, I don't even like the idea of auto-declaring variables (even though I proposed it :)). I would be in favor of this feature only for documentation purposes, especially in declaration files. But then, I guess it would be confusing if named return values were only allowed in function types, and not in function definitions...

**Comment by agladysh** [comment]
NB: In Lua functions without a return statement do NOT return nil. At least in 5.1.

```
$ lua5.1 
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> =select('#', (function() return nil end)())
1
> return select('#', (function() end)())
0
```

**Comment by hishamhm** [comment]
@agladysh Indeed! Thank you for the correction!

In fact, even though I forgot when making that comment, Teal _is_ aware of that and takes this fact into account, because a function that "returns nothing" in its type signature produces at compile time an (internal) tuple of different arity than ones that "return something" but happens to be nil at run time, and this fact is used at compile time for matching types in multiple assignment, arity checks in expressions, etc.

**Comment by pdesaulniers** [comment]
I don't like this idea after all, so I'll just close the issue.
