### ISSUE TITLE
Remove all restrictions for 'any' type returned by function

### ISSUE THREAD

**Issue by gr8den** [teal-language/tl#192]
When I run `tl check` of this file:
```lua
-- function f(): any -- same error
function f(): any...
  return {123}
end

local c = f();
print(#c);
print(c[1])
```

I receive error:
```
any.tl:6:7: cannot use operator '#' on type any
any.tl:7:9: cannot index object of type any with number
```

**Comment by hishamhm** [comment]
A variable of type `any` accepts any value but it is not a "dynamic type". To use the value in Teal you need to cast it to a more concrete type. In other words, `any` in Teal is more similar to `unknown` in TypeScript than to `any` in TypeScript.
