### ISSUE TITLE
Type Guards for conditional blocks

### ISSUE THREAD

**Issue by gr8den** [teal-language/tl#193]
Please add ability to narrow down the type within a conditional block (Type Guards)

When I run `tl check` for this code:
```lua
local c: nil | number = 7;

if c == nil then
  print('nil!');
else
  c = math.min(c, 5);
end

```

I get error:
```
1 error:
type-guard.tl:6:16: argument 1: got nil | number, expected number
```

**Comment by hishamhm** [comment]
Type guards are implemented for union types using the `is` operator.

However,

```
local c: nil | number = 7;
```

this does not do what you expect: all types in Teal are, for now, nilable. So `local c: number` does allow `c` to accept `nil` and the type guards (even with `is`) will not prevent a `nil` to be stored in `c`.
