### ISSUE TITLE
Better error message for two types with the same unqualified name

### ISSUE THREAD

**Issue by Ruin0x11** [teal-language/tl#198]
If you declare two types with the same name in different modules, but forget to use `as`, you get this error:

```
in return value: record field doesn't match: type: FileMode is not a FileMode
```

This is confusing. It would be better if the names were fully qualified instead, like this:

```
in return value: record field doesn't match: type: lfs.FileMode is not a love.filesystem.FileMode
```

**Comment by hishamhm** [comment]
Fixed via #264!!
