### ISSUE TITLE
Expose the types of the Teal compiler itself in the `tl` module

### ISSUE THREAD

**Issue by Ruin0x11** [teal-language/tl#204]
Since `tl` can be imported as a module, it would be nice if it exposed its own types to use in another `.tl` file, as the functions in the module are themselves typed. Without them we have to copy everything in the compiler to its own `.d.tl` file.

**Comment by hishamhm** [comment]
Yes, I want to eventually have a proper module API but for now and refactor the `tl` module. Part of it will involve exposing types, but be aware that at this stage of the project, I can't provide a lot of backward compatibility guarantees on their internal structures.

**Comment by hishamhm** [comment]
Closing this one since some of the types are now exported for the use of third-party tools. Not all types will be exported though (in particular, the AST structure is not exported because it is not stable and I'd prefer that third-party code did not depend on it right now).
