### ISSUE TITLE
Standard types?

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#209]
I think it would be a good idea to take some of the extremely common patterns and make a standard library of types. For example, `type Set = <T>{T:boolean}` and maybe if at some point if variadic type args become a thing maybe a tuple type could be implemented with it `local res: Tuple<boolean, string, number> = {fd:close()}`. And maybe give some word/template alternatives to maps `{foo:bar} = Map<foo, bar>`

**Comment by hishamhm** [comment]
I would prefer not to bake those into the language, some of this would make more sense as a library, at least to the extent that the language supports it. Also not sure about extending the language just for the sake of allowing these aliases — I'm well aware that one point we'll need to put some boundaries on the type system extensions to avoid falling in super-complicated-PL-territory (if we haven't already :laughing: ).

**Comment by hishamhm** [comment]
Closing this as a "wontfix" of sorts for now, but feel free to add more comments.
