### ISSUE TITLE
Confusing "branch is always false" message

### ISSUE THREAD

**Issue by Zash** [teal-language/tl#210]
- `tl` version 0.7.1+dev / 335f65a1a4ba

Input `test.tl`:

```lua
function foo(v : any)
	if not v is table then
		print"foo"
	else
		print"bar"
	end
end
```

Output:

```
$ tl check test.tl
========================================
1 error:
test.tl:1:18: branch is always false
```

It seems to be triggered by `not x is <type>` where `x` is of `any`. Reversing the if-else and dropping the `not` gives no message. Note how the line number, column points to the type definition.

**Comment by hishamhm** [comment]
Thanks for the report! This is indeed a bug, I'll look into it.

**Comment by Fang-** [comment]
For the record, one of the example in the tutorial suffers from this bug, and another problem which I think is related:

```lua
local record MyRecord
  my_record_field: number
end
local type a = string | number | MyRecord

if a is string then
   print("Hello, " .. a)
elseif a is number then      --  8
   print(a + 10)
else
   print(a.my_record_field)  --  11
end
```

```
2 errors:
main.tl:8:1: branch is always false
main.tl:11:10: cannot index something that is not a record: string | number | MyRecord
```

**Comment by hishamhm** [comment]
@Fang- As of the latest `master` (12216468aa), this example works when entered like this:

```
local record MyRecord
  my_record_field: number
end
local type T = string | number | MyRecord
local a: T
-- or simply like this:
-- local a: string | number | MyRecord

if a is string then
   print("Hello, " .. a)
elseif a is number then
   print(a + 10)
else
   print(a.my_record_field)
end
```

If you use `local type a` and then try to use the union type as a variable, you still get those cryptic errors above, but at first impression I think that's sort of abusing the "type also does double-duty as a prototype declaration" behavior we kept in for records, and shouldn't be used for unions.
