### ISSUE TITLE
Problem with select() variants

### ISSUE THREAD

**Issue by Zash** [teal-language/tl#219]
### Problem

`select()` can be called in multiple ways, both as `select(number, ...)` and `select('#', ...)`. It appears that this is not handled correctly and the `(string, ...)` variant takes precedence when performing type checks.

### Input

``` lua
local greeting = select(2, "hi", "hello")
```

### Output

```
$ tl check test.tl
========================================
1 error:
test.tl:1:25: argument 1: got number, expected string
```

**Comment by hishamhm** [comment]
@Zash Thanks for the report! It's now fixed!
