### ISSUE TITLE
Feedback requested: syntax for function types

### ISSUE THREAD

**Issue by hishamhm** [teal-language/tl#222]
Hi folks! I'm thinking about merging teal-language/tl#194 and push a new release with the syntax changes for type declarations. While we're on the topic of type declaration syntax changes, I have a question:

Do you prefer "textual" `local f: function(number): number` or "arrow" `local f = (number) -> (number)` syntax for function types?

Other typed Lua dialects (@andremm's original Typed Lua and Roblox's Luau) use the "arrow" notation. Should we change to that?

**EDIT**: To clarify, this is about the _type declaration_, not function declarations.

```lua
-- forward-declaring a function variable
local hello: function(string, number): boolean, string

-- the function value itself stays the same
hello = function(name: string, joy: number): boolean, string
   if joy < 1 then
      return false, "not joyful enough!"
   end
   print("Hello, " .. name .. ("!"):rep(joy))
   return true
end

-- a map of strings to functions
local fns: {string : function(string, number): boolean, string} = {}

fns["greet"] = hello
```

versus

```lua
-- forward-declaring a function variable
local hello: (string, number) -> (boolean, string)

-- the function value itself stays the same
hello = function(name: string, joy: number): boolean, string
   if joy < 1 then
      return false, "not joyful enough!"
   end
   print("Hello, " .. name .. ("!"):rep(joy))
   return true
end

-- a map of strings to functions
local fns: {string : (string, number) -> (boolean, string)} = {}

fns["greet"] = hello
```

**Comment by Fang-** [comment]
I'm tempted to argue that, what other languages/dialects do shouldn't factor into teal's design. Still, familiar syntax might make it easier for people to adopt. (If the underlying semantics are subtly different, that familiarity might come to bite you, but I don't think that's the case here.)

Regardless of familiarity, I'm partial to the `->` syntax. It's more concise.

I only started playing with teal very recently. Make of this what you will!

**Comment by CapsAdmin** [comment]
One nice property of the textual version is that you can just add and remove types to switch between the typesystem and lua version. The arrow syntax is just a different thing entirely and doesn't feel right to me given that we don't have arrow functions in Lua.

**Comment by xvxx** [comment]
I'm new to Teal so please take this opinion with a large helping of salt, but IMO one of the things that makes Lua stand out among popular languages in 2020 is its lack of line noise. 

Stuff like using `and` and `not` instead of `&&` and `!`, and `do` / `end` instead of `{` curly braces `}`, are small on their own but add up over a whole file to give Lua code a different feel than most C-based languages.

I really like the `->` operator in some languages, but it definitely falls into the category of "ASCII art", and I would personally, quite humbly, suggest that Teal continue to be a spiritual partner/successor to Lua and follow its philosophy of eschewing symbols in favor of keywords.

**Comment by tsafin** [comment]
Looks like both introducing ':' and '->' at the same context would not complicate parser, keeping it LL(1). So choice is not technical but design-wise. Using ':' is smelling more Pascal-like, and I assume it's a proper feeling for the language like Lua.

So, personally, I'd vote for "textual".

**Comment by euclidianAce** [comment]
I'm personally fine with the current textual syntax as symbols like -> don't quite feel like Lua

**Comment by darekrusin** [comment]
As for the arrow vs textual, I'd vote **textual**. For two reasons:
1. Arrow feels weird in Lua, out of place.
2. Textual forward declaration is consistent with function declaration itself, which is good. Less syntax to remember and I can just cut out stuff from function declaration and voila - I have forward declaration. While with the arrow variant, I'd have to reformat the whole thing, insert arrows, parentheses, etc.

**Comment by hishamhm** [comment]
Thank you all for the feedback!

Textual is where I originally bent towards (clearly, it's what I originally chose to implement :) ) because I agree it does mesh naturally with Lua's ALGOLesque syntax.

If there was overwhelming support for arrow I'd go with that, but for the time being let's just stick to `function` then!
