### ISSUE TITLE
Compiler discards leading newlines causing line numbers to be inaccurate

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#226]
There's some inconsistency when teal compiles code and with some methods lines seem to be off by one from their lua counterparts

**Comment by euclidianAce** [comment]
This may be my fault, I remember some stray newlines in `tl.tl` itself, I'll investigate and put an example later if a can

**Comment by hishamhm** [comment]
Yes please, if you spot any examples please post them here! When that happens it's usually specific statements that are misbehaving, so it's generally easy to reduce the examples if you run into the problem.

**Comment by euclidianAce** [comment]
The problem appears to be that the compiler just throws out leading newlines, it just happened to be off by one since I usually start my scripts with a single newline

minimal example
`hello.tl`
```


print("hello world")
```
`tl gen hello.tl` results in: the following hello.lua
```
print("hello world")
```

for things that work this is fine but errors end up having the wrong line numbers, just replace the `print` with an `error`

**Comment by euclidianAce** [comment]
a quick fix for this (at least in `tl.gen`) would just be to save the leading newlines at the beginning of the call
```
function tl.gen(input: string, env: Env): string, Result
   local leading_newlines = string.match(input, "^\n*") or ""

   env = env or tl.init_env()
   local result, err = tl.process_string(input, false, env)

   if err then
      return nil, nil
   end

   if not result.ast then
      return nil, result
   end

   return leading_newlines .. tl.pretty_print_ast(result.ast), result
end
```
as something like leading newlines feels a little weird to store in the ast node, I'm not sure where else this would be done

**Comment by hishamhm** [comment]
Should be fixed now, thanks for the feedback!
