### ISSUE TITLE
allow returning more than 1 value from a file

### ISSUE THREAD

**Issue by lenscas** [teal-language/tl#240]
in my project rlua expects 3 values back from the lua script that got executed. This works fine for lua, but teal doesn't like it.

minimal example: `return 1,2`

error: `excess return values, expected 1 (<any type>), got 2 (number, number)`

In my case I can probably work around it without much problem, as I will probably end up making a .lua script to load the teal compiler as a library instead of compiling the code directly anyway, but it would still be nice to have that restriction lifted :)

**Comment by hishamhm** [comment]
I think this returned type for the module is truncating to a single value explicitly (look up `-- if at the toplevel` in the source code). It's probably a matter of lifting this restriction to let the module return the tuple, check if that works and add a test to exercise that scenario.

**Comment by Deepak123bharat** [comment]
@lenscas I was trying to reproduce the issue. Can you please share the example code snippet for which the error `excess return values, expected 1 (<any type>), got 2 (number, number)` occurs? 
Example I was using.
```Lua
local tl = require('tl')
tl.loader()

local func, err = load('return 1, 2, 3')
local a, b, c = func()
print(a, b, c)

local program, err = tl.load('local a,b,c : number, number, number = 1, 2, 3 return a, b, c')
local x, y, z= program()
print(x, y, z)
-- Output
-- 1 2 3
-- 1 2 3
```

**Comment by lenscas** [comment]
I think this bug already got fixed? All I needed to do before was make a teal file with `return 1, 2` and it would show that error, but it doesn't do that anymore.
I can now also change my code to how I originally wanted it and `tl check` is also happy with it. My code for what it is worth was
```lua
package.path = './lua/?.lua;' .. package.path
global battle : Rust.Field;
global chosenCard : Rust.Card;

require("engine/battle"):init(battle,chosenCard)
local turn = require"engine/turn"

return turn()
```

**Comment by hishamhm** [comment]
All right, let's close this one then! Thanks @Deepak123bharat for the investigation!
