### ISSUE TITLE
name idea(s)

### ISSUE THREAD

**Issue by akavel** [teal-language/tl#25]
You asked on twitter, but I don't use it nor mastodon, so I let myself answer here: my name idea is: **"lute"**! :)

Otherwise, please try to not go with TypedLua/TypeLua; this would be too similar to the previous project of this name in my eyes...

Good luck! :)

**Comment by ryanford-frontend** [comment]
How about "Teal" as in `tl` and the color. Just a thought

**Comment by pdesaulniers** [comment]
"tl;dr" :stuck_out_tongue: 

More seriously, though, I can't find many words that would fit with the `.tl` extension. Teal, Tail, Tale, Tool...

I can think of some other words, but they would require changing the extension a bit (like "Tulip" => `.tlp`).

**Comment by ash-nolan** [comment]
I kind of like tl (pronounced tee-ell) actually. It's short, simple, easy to read, and easy to write.

**Comment by hishamhm** [comment]
Let's go with Teal then!

It seems to be the most-liked name (based on likes here and my [ultra-scientific Twitter poll](https://twitter.com/hisham_hm/status/1239735525206036484)), plus it allows us to keep both the filename extension and the compiler name, it's pronounced mostly the same, and gives us a [beautiful mascot](https://en.wikipedia.org/wiki/Brazilian_teal). :)

**Comment by akavel** [comment]
I don't know how you made it, but the circle logo with a square in it now totally looks to me like a head and eye of a [~~duck~~ "teal"](https://en.wikipedia.org/wiki/Eurasian_teal) indeed, just missing a beak! I wonder if this is only the power of suggestion, or is there something more behind it?... o_O

**Comment by hishamhm** [comment]
> I wonder if this is only the power of suggestion, or is there something more behind it?

@akavel hahaha, it wasn't the goal but I could see that working! :smile:

**Comment by hishamhm** [comment]
All right, let's close this one then!
