### ISSUE TITLE
if-else doesn't infer "remainder" of union type

### ISSUE THREAD

**Issue by Fang-** [teal-language/tl#250]
Consider the following snippet:

```lua
local type A = number
local type B = record
  h: unionAorB
  t: unionAorB
end
local type unionAorB = A | B

function head(n: unionAorB): unionAorB
  if n is B then
    return n.h
  else
    assert(false, 'head of A; ' .. n)  --  12
  end
end
```

The only type `n` can be, if not `B`, is `A`, right? And yet, it treats it as the full `unionAorB`:

```
main.tl:12:33: cannot use operator '..' for types string 'head of A; ' and unionAorB (inferred at main.tl:11:3: )
```

It should instead infer `n` to be of type "`unionAorB` excluding `B`".

**Comment by hishamhm** [comment]
looks like the opposite problem as before is happening here:

if you do

```lua
function head(n: A | B): unionAorB
```

then it does what you expect! I guess there's still a few places where the "alias vs. resolved-type" check needs to be fixed.
