### ISSUE TITLE
Incorrect output when building modules that depend on other modules?

### ISSUE THREAD

**Issue by fsouza** [teal-language/tl#265]
Hey there!

Thanks for this great project. First, I apologize for the shitty title, but I don't really know how to summarize the issue, so I'll just demonstrate it 🙈 

<details><summary>tlconfig.lua</summary>

```lua
return {
  source_dir = 'src';
  build_dir = 'build';
  include_dir = {'src'};
  skip_compat53 = true;
}
```
</details>

<details><summary>src/themes.tl</summary>

```
local M: {string:number} = {
    theme1 = require('themes.theme1');
    theme2 = require('themes.theme2');
}

return M
```
</details>

<details><summary>src/themes/theme1.tl</summary>

```
local get_value = function(name: string): number
    if name == '1' then
        return 1
    else
        return 0
    end
end

return get_value('random')
```
</details>

<details><summary>src/themes/theme2.tl</summary>

```
return 2
```
</details>

(uploaded it all to a repo: https://github.com/fsouza/tl-repro)

Given the files above or in the repo linked, when I run `tl build`, all output files end-up with the same content:

```
％ tl --version
0.8.2
％ tl build
Wrote: build/themes.lua
Wrote: build/themes/theme1.lua
Wrote: build/themes/theme2.lua
％ find build -name \*.lua | xargs shasum -a 256
81001aa80a80acc10d20b3a17106535e16d03c674339b6041bd5aedc54de2f7e  build/themes.lua
81001aa80a80acc10d20b3a17106535e16d03c674339b6041bd5aedc54de2f7e  build/themes/theme1.lua
81001aa80a80acc10d20b3a17106535e16d03c674339b6041bd5aedc54de2f7e  build/themes/theme2.lua
％ tail build/themes.lua build/themes/theme*
==> build/themes.lua <==
local M = {
   theme1 = require('themes.theme1'),
   theme2 = require('themes.theme2'),
}

return M

==> build/themes/theme1.lua <==
local M = {
   theme1 = require('themes.theme1'),
   theme2 = require('themes.theme2'),
}

return M

==> build/themes/theme2.lua <==
local M = {
   theme1 = require('themes.theme1'),
   theme2 = require('themes.theme2'),
}

return M
```

Let me know if further info is needed!

(sorry I submitted this earlier, apparently ctrl+enter submits the issue lol)

**Comment by lenscas** [comment]
I'm guessing it has to do with there being a `themes.tl` file and a `themes` folder.

**Comment by fsouza** [comment]
@lenscas thanks for the feedback. I suspected that before and it wasn't the case (been wrestling this for a while and forgot to make the name different when creating a small reproducer). I can call themes.tl whatever and it still generates identical outputs.

**Comment by hishamhm** [comment]
Thanks for the detailed report with test case! @euclidianAce, any idea about the `tl build` behavior above?

**Comment by fsouza** [comment]
Played around with it a bit, and if I modify setup_env to always initialize the env, it works: https://github.com/teal-language/tl/blob/1fb94220e309651c390291f037e3b8c301f8758e/tl#L276-L295

But this is me hacking around, I definitely have no idea of what I'm doing 🙈 But since I'm here, I'll also ask another question: does env need to be global? Every time it's referenced, setup_env is called before, so if we change setup_env to always initialize the env, we could have it return the env instead of modifying a global variable. Does that make sense?

Basically, this diff:

```diff
diff --git a/tl b/tl
index 5fb554c..84fa896 100755
--- a/tl
+++ b/tl
@@ -107,7 +107,7 @@ local function get_config()
       config[k] = v
    end
 
-   err = validate_config(config)
+   local err = validate_config(config)
 
    if err then
       die("Error while loading config: " .. err)
@@ -241,8 +241,6 @@ local function report_type_errors(result)
    return not has_type_errors
 end
 
-local env = nil
-
 local function get_shared_library_ext()
    if is_nil_or_whitespace(package.cpath) then
       return "so" -- FIXME
@@ -274,24 +272,22 @@ end
 local modules = tlconfig.preload_modules
 
 local function setup_env(filename)
-   if not env then
-      local basename, extension = filename:match("(.*)%.([a-z]+)$")
-      extension = extension and extension:lower()
-
-      local lax_mode
-      if extension == "tl" then
-         lax_mode = false
-      elseif extension == "lua" then
-         lax_mode = true
-      else
-         -- if we can't decide based on the file extension, default to strict mode
-         lax_mode = false
-      end
+   local basename, extension = filename:match("(.*)%.([a-z]+)$")
+   extension = extension and extension:lower()
+
+   local lax_mode
+   if extension == "tl" then
+      lax_mode = false
+   elseif extension == "lua" then
+      lax_mode = true
+   else
+      -- if we can't decide based on the file extension, default to strict mode
+      lax_mode = false
+   end
 
-      local skip_compat53 = tlconfig["skip_compat53"]
+   local skip_compat53 = tlconfig["skip_compat53"]
 
-      env = tl.init_env(lax_mode, skip_compat53)
-   end
+   return tl.init_env(lax_mode, skip_compat53)
 end
 
 local function get_output_filename(file_name)
@@ -309,13 +305,12 @@ local function get_output_filename(file_name)
 end
 
 local function type_check_file(file_name)
-   setup_env(file_name)
+   local env = setup_env(file_name)
 
    local result, err = tl.process(file_name, env, nil, modules)
    if err then
       die(err)
    end
-   env = result.env
 
    local has_syntax_errors = report_errors("syntax error", result.syntax_errors)
    if has_syntax_errors then
@@ -346,11 +341,11 @@ local function type_check_file(file_name)
 end
 
 local function type_check_and_load(filename, modules)
+   local env = setup_env(filename)
    local result, err = tl.process(filename, env, nil, modules)
    if err then
       die(err)
    end
-   env = result.env
 
    local has_syntax_errors = report_errors("syntax error", result.syntax_errors)
    if has_syntax_errors then
@@ -363,7 +358,7 @@ local function type_check_and_load(filename, modules)
       end
    end
 
-   local chunk; chunk, err = (loadstring or load)(tl.pretty_print_ast(result.ast), "@" .. filename)
+   local chunk, err = (loadstring or load)(tl.pretty_print_ast(result.ast), "@" .. filename)
    if err then
       die("Internal Compiler Error: Teal generator produced invalid Lua. Please report a bug at https://github.com/teal-language/tl")
    end
@@ -395,12 +390,12 @@ if cmd == "run" then
    end
 
    -- shift back all non-arguments to negative positions
-   for p2, a in ipairs(neg_arg) do
-      arg[-p2] = a
+   for p, a in ipairs(neg_arg) do
+      arg[-p] = a
    end
    -- put script in arg[0] and arguments in positive positions
-   for p2, a in ipairs(args["script"]) do
-      arg[p2 - 1] = a
+   for p, a in ipairs(args["script"]) do
+      arg[p - 1] = a
    end
    -- cleanup the rest
    n = nargs
@@ -436,7 +431,7 @@ local function write_out(result, output_file)
          die("cannot write " .. output_file .. ": " .. err)
       end
 
-      local ok; ok, err = ofd:write(tl.pretty_print_ast(result.ast) .. "\n")
+      local ok, err = ofd:write(tl.pretty_print_ast(result.ast) .. "\n")
       if err then
          die("error writing " .. output_file .. ": " .. err)
       end
@@ -454,7 +449,7 @@ if cmd == "gen" then
    local results = {}
    local err
    for i, input_file in ipairs(args["script"]) do
-      setup_env(input_file)
+      local env = setup_env(input_file)
       local res = {
          input_file = input_file,
          output_file = get_output_filename(input_file)
@@ -464,7 +459,6 @@ if cmd == "gen" then
       if err then
          die(err)
       end
-      env = res.tl_result.env
 
       if #res.tl_result.syntax_errors > 0 then
          exit = 1
@@ -585,7 +579,7 @@ local function traverse(dirname, emptyref)
    local paths = {} --lookup table for string paths to help
    -- with pattern matching while iterating over a project
    -- paths[files.foo.bar] -> "foo/bar"
-   emptyref = emptyref or {}
+   local emptyref = emptyref or {}
    for file in lfs.dir(dirname) do
       if file ~= "." and file ~= ".." then
          if lfs.attributes(path_concat(dirname, file), "mode") == "directory" then
@@ -774,13 +768,12 @@ table.sort(sorted_source_file_arr, function(a, b) return a[1] < b[1] end)
 
 for i, files in ipairs(sorted_source_file_arr) do
    local input_file, output_file = files[1], files[2]
-   setup_env(input_file)
+   local env = setup_env(input_file)
 
    local result, err = tl.process(input_file, env, nil, modules)
    if err then
       die(err)
    end
-   env = result.env
 
    local has_syntax_errors = report_errors("syntax error", result.syntax_errors)
    if has_syntax_errors then

```

If this makes sense, I can send a PR.

**Comment by euclidianAce** [comment]
So it definitely seems to be an issue with the caching that the env does to prevent reloading old code, hence why not reusing it fixes it.

The cli driver is probably due for an update as well, maybe its time to migrate some of the things from my own cli to here?

**Comment by euclidianAce** [comment]
Okay, ive found the root cause and will post a summary when my internet wants to cooperate :laughing:

**Comment by euclidianAce** [comment]
Okay, with some good ol `print` debugging, what's happening is that when a module gets cached in `tl.process_string`, it just directly stores the `Result` in the `env.loaded` map. But the `Result` can also be provided as an argument for a default value, presumably to update its `Env` or something (I'm not too famliar with that part of the code), but the consequence of this is that when `themes.tl` gets checked first, it loads the other files, caches them with the incorrect result and when whey get written, they get written with the compiled output of `themes.tl`

Always creating a new `Result` for each `process_string` call fixes this, but creates other issues that I dont really know how to solve, so @hishamhm any suggestions?
https://github.com/teal-language/tl/blob/1fb94220e309651c390291f037e3b8c301f8758e/tl.tl#L6742-L6753

(on a side note, I see you're translating some neovim stuff
 - Is there a particular reason you are doing `src/themes.lua` instead of `src/themes/init.lua`, I've noticed that neovim users learning Lua don't really know that `?/init.lua` is in the package path, theres not really a benefit to one over the other, but just personally like the latter and don't see people using it, mostly out of ignorance.
 - And any `vim.loop` stuff can't really be typed until Teal has class/type inheritence since all the `handle` types inherit from base classes. But this is planned for the next release(?) I believe
 - I've also been moving my Lua Neovim stuff to Teal so feel free to steal from my dotfiles)

**Comment by fsouza** [comment]
@euclidianAce yeah, while investigating this issue I learned about the init trick and adjusted 😁 https://github.com/fsouza/vimfiles/commit/9a2569272764895d683944a4f365fb65dce4c4dd thanks for the feedback!

(my tl branch may be outdated though)

**Comment by hishamhm** [comment]
> But the Result can also be provided as an argument for a default value, presumably to update its Env or something (I'm not too famliar with that part of the code),

Rereading that part of the code, `Result` is passed in and out as modules are processed recursively as `require` calls are type-checked, in order to accumulate error messages. Looking back, that organically-grown API ended up messy. It's better to just take the Env in and only propagate these errors out. We're in 0.x days, I can try my hand at cleaning up that API at the cost of some breakage...

**Comment by hishamhm** [comment]
>  I can try my hand at cleaning up that API at the cost of some breakage...

Oh no, refactoring `tl.tl`, which is written in Teal, was so _easy_ with the help of the compiler, but now for adjusting the main `tl` script which is written in Lua, I'm on my own! 🙄😂

**Comment by hishamhm** [comment]
I ended up going with a simpler change which retains the current tl API and seems to fix the behavior. See #266 

Many thanks to @fsouza for the repro case and to @euclidianAce for the analysis which pinpointed the issue!
