### ISSUE TITLE
Array entries not explicitly nilable?

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#268]
example:
```
-- arr.tl
local arr: {number} = {
   nil, 5
}
```
```
$ tl check arr.tl
========================================
1 error:
arr.tl:2:23: in local declaration: arr: got {nil | number}, expected {number}
```

Since types are nilable this seems like an issue.

**Comment by lenscas** [comment]
if I remember correctly, having holes in arrays can give somewhat unexpected results
```
local a = {1,2,nil,4}
print(#a) --prints 4 as expected
for k,v in pairs(a) do print(k,v) end --prints every key and value except key 3, value nil
for k,v in ipairs(a) do print(k,v) end --prints only the first 2 keys and values
```
as a result, I am not sure if I am against having to specifically tell teal that the array may have holes. I also remember that teal doesn't want you to use pairs on arrays, but considering it has different results than ipairs if an array has holes it should be allowed without a warning in those cases. However, the error message should then specifically mention why its not allowed, and ideally how to fix it.

that is how I look at it at least.

**Comment by euclidianAce** [comment]
This is less of an issue with the unpredictable (and sometimes undefined) behavior of sparse arrays, this is an issue with the type system and all types being nillable, but a nillable type `T`, not being equivalent to `T | nil` (Which to the type system should basically be a no-op). The use case that sparked this was more of a need for a tuple type, so certain integer indices needed to be nil and doing `{ a, nil, b }`, is more convenient than `{ [1] = a, [3] = b}`. And the more I write about this weirder it seems to me that `nil` is even a type at all...

**Comment by hishamhm** [comment]
Thanks for the report! That was a tricky one to catch because

```lua
local arr: {number} = {
   5, nil
}
```

did not cause it, amusingly enough.
