### ISSUE TITLE
Errors in patterns cause internal compiler error

### ISSUE THREAD

**Issue by catwell** [teal-language/tl#273]
If you write:

    print((" xy"):match("[^\s]"))

instead of:

    print((" xy"):match("[^%s]"))

it causes:

> Internal Compiler Error: Teal generator produced invalid Lua. Please report a bug at https://github.com/teal-language/tl

**Comment by hishamhm** [comment]
Thanks for reporting! This is an uncaught lexer error, this causes the same issue:

```
print("\s")
```

**Comment by hishamhm** [comment]
The lexer does not validate escape sequences according to https://www.lua.org/manual/5.4/manual.html#3.1 — currently only detects a `\` when inside `singlequote_string` or `dblquote_string`, switches the lexer state machine to either `escape_singlequote_string` or `escape_dblquote_string`, which skip over the next character. Those states should add some checking that the character is a valid indicator, and produce an `$invalid$` token if the string is malformed (which will cause the parser to bail with `syntax error` later and avoid the error in `tl run`).

**Comment by catwell** [comment]
I am taking a look at this, it is slightly more complicated than expected because of the escape sequences not composed of a backslash + a single character (backslash + line break, \z and unicode characters).

**Comment by hishamhm** [comment]
Fixed by #276 :D
