### ISSUE TITLE
C:\Program Files\Luarocks3.4.0\lua53.dll: file not recognized: file format not recognized

### ISSUE THREAD

**Issue by fujisheng** [teal-language/tl#277]
compat53 0.8-1 depends on lua >= 5.1, < 5.5 (5.3-1 provided by VM)
mingw32-gcc -O2 -c -o lstrlib.o -IC:\Program Files\Luarocks3.4.0/include lstrlib.c
mingw32-gcc -shared -o compat53/string.dll lstrlib.o C:\Program Files\Luarocks3.4.0/lua53.dll -lm
C:\Program Files\Luarocks3.4.0\lua53.dll: file not recognized: file format not recognized
collect2.exe: error: ld returned 1 exit status

**Comment by hishamhm** [comment]
@fujisheng This looks like a LuaRocks installation issue, and not a Teal issue. Please check your LuaRocks installation!
