### ISSUE TITLE
Add warning flags for the compiler

### ISSUE THREAD

**Issue by overcrook** [teal-language/tl#288]
FIrst of all, thanks to @euclidianAce for the warning system, it is a huge step forward for the Teal!

I come here from a C world and miss some of the nice features of the GCC/Clang warning system. Is it possible to make compiler options for every warning type and allow some warnings to be disabled?

GCC, for example, allows certain warning to be turned on and off (like `-Wunused` / `Wno-unused`).
Warnings can be converted to errors (`-Werror` to treat all warnings as errors, and `-Werror=<option>` to treat only certain warnings). This conversion can be reverted: `-Wno-error=unused`.

With these compiler flags, it will be easier to track only the warnings you want and keep the build log clean.

**Comment by euclidianAce** [comment]
This is definitely planned (at least I was/am planning it), just some implementation details to work out about how the cli should pass these flags to the compiler.

As a work around for disabling warnings, the `-q --quiet` flag currently suppresses all warnings, but not errors.

**Comment by hishamhm** [comment]
> just some implementation details to work out about how the cli should pass these flags to the compiler.

@euclidianAce I haven't thought super deeply about it, but as a first approach my suggestion would be to not pass the flags to the compiler, and have the compiler generate all warnings and errors, but have an enum with a sort of "category" in the `Error` record, and then the CLI can choose to filter whatever categories it wants based on flags/config.

**Comment by euclidianAce** [comment]
Implemented via #312!
