### ISSUE TITLE
teal-playground bot previews

### ISSUE THREAD

**Issue by darrenjennings** [teal-language/tl#291]
I don't know how much the `teal-language/teal-playground` is used to test tl during development, if at all, but would be cool to have an auto build env for PR's so that users can play around with the feature before it lands on master. The implementation would be dead simple since teal-playground is completely static and relies on a publicly accessible tl.lua. So every PR could `/s/master/<branch>`

Replace this line with the PR permalink:
https://github.com/teal-language/teal-playground/blob/040e5962c1eb839087b6445f8af37a8dba3a1fe9/src/components/Playground.vue#L39-L48

I think this has implications that we'd need to build a teal bot so opening up an issue to gauge interest and solicit feedback.

Typescript has a bot that builds playgrounds (among other things), example here: https://github.com/microsoft/TypeScript/pull/42020#issuecomment-748259864

**Comment by hishamhm** [comment]
Ooh, nice! I think it would be <i>really</i> cool for discussing PRs implementing language features.

Security-wise, would it be possible to allow code from other forks (for example in https://github.com/teal-language/tl/pull/270 the code is in branch `tuple-type` from @euclidianAce 's `euclidian-ace/tl` fork) or would it be necessary to allow only branches of the `teal-language/tl` repo?

At first glance, since everything runs on the client and is sandboxed by Fengari, it should be all right? The one thing I could think of is that maybe that Lua snippet in Playground.vue needs to add a `js = nil` to prevent the arbitrary `tl` module being loaded from playing funny tricks in the browser via Fengari's JS integration, I guess -- @daurnimator, any advice here with regard to putting something online that lets users load arbitrary Lua code into Fengari?

**Comment by darrenjennings** [comment]
@hishamhm I am thinking:

1. if we are worried about arbitrary code execution, we could have the bot decide if the playground is safe to run, e.g. only trigger a playground if a teal-language org comments with "@tealbot create a playground"
2. the playground can be any fork `https://raw.githubusercontent.com/<path>/?.lua`, not necessarily repo specific. teal-playground supports envs already at build time through vue-cli https://cli.vuejs.org/guide/mode-and-env.html#environment-variables

**Comment by hishamhm** [comment]
^ sounds perfect!

(though it might turn out to be safe enough to auto-create a playground a la netlify previews, I haven't really thought it through, but then that would be the cherry on top)

**Comment by darrenjennings** [comment]
@hishamhm the netlify cli allows for building and deploying. I just did this locally:

```console
// git clone teal-playground

$ VUE_APP_TL_PACKAGE_PATH_URL=https://raw.githubusercontent.com/euclidianAce/tl/tuple-type/?.lua yarn build
$ netlify deploy
Deploy path: /Users/darrenjennings/source/repos/teal-playground/dist
Deploying to draft URL...
✔ Finished hashing 139 files
✔ CDN requesting 7 files
✔ Finished uploading 7 assets
✔ Draft deploy is live!

Logs:           https://app.netlify.com/sites/teal-playground/deploys/5fe3ba33c5d58514a307c1cc
Live Draft URL: https://5fe3ba33c5d58514a307c1cc--teal-playground.netlify.app

If everything looks good on your draft URL, take it live with the --prod flag.
netlify deploy --prod
```

And now https://app.netlify.com/sites/teal-playground/deploys/5fe3ba33c5d58514a307c1cc is pointed at @euclidianAce's branch

**Comment by daurnimator** [comment]
> @daurnimator, any advice here with regard to putting something online that lets users load arbitrary Lua code into Fengari?

People would only be "hacking" their own browser. Might as well let them.

Though really, if you don't want users to be able to interact with JS, then just don't load [fengari-interop](https://github.com/fengari-lua/fengari-interop) into the `lua_State`.

**Comment by hishamhm** [comment]
@darrenjennings Nice! Looks like this is all that is needed in the teal-playground side and now it's the part of creating the teal bot? or perhaps a Github Action that adds the playground link to the PR?

**Comment by lenscas** [comment]
I'm pretty sure that a github action can trigger on comments, so I think an action is easier to setup (No need to find a host for it). But I never made a github bot and only used github actions for the basic stuff so take this with a grain of salt :)

**Comment by hishamhm** [comment]
@lenscas I mentioned Actions because I recalled that the Kong documentation repository auto-generates a Netlify preview on each PR (e.g. [see here](https://github.com/Kong/docs.konghq.com/pull/2524) ) so adding something like that that adds a playground link on Teal PRs would be pretty cool!

**Comment by darrenjennings** [comment]
@lenscas @hishamhm yes agreed was gonna play around with GH actions, should be straightforward if we can get a netlify token that has teal-playground creds. I am unsure if the netlify bot could work like it does in kong docs because we need it to be cross-repo. @hishamhm you might want to create a teal org in netlify and add me as an admin. Right now it’s under my user as a personal site.

**Comment by lenscas** [comment]
actually, I believe github actions makes most if not all secrets unavailable for actions triggered by a fork. Not sure what the exact rules on that are though.
