### ISSUE TITLE
Sandbox compatibility

### ISSUE THREAD

**Issue by deliciouslytyped** [teal-language/tl#297]
Funnily enough this is somewhat related to the recently created #291 issue. I've been doing some research (googling) on sandboxing Lua the past few days, 

I just started learning Lua, specifically because I want a languge I can embed in Haskell apps - so I'm inexperienced.
I haven't used Teal yet, but I do think switching to a typed dialect eventually would be highly preferred, though from what I've seen from [1][2], and [3] suggests that I won't be able to solve one of the biggest annoyances, which is NoneTypeError^W nil. :P

**The question is, does Teal impose any requirements on generated code beyond what was already required by the original code?** If the answer is no, that means (relatively?) severe restrictions still allow continued use of Teal.

My idealized sandbox architecture concept currently consists of
1. restricting the accessible Lua environment to known safe functions, this also explicitly means disallowing any direct bytecode or memory manipulation. (probably redundant with 2.) 
2. sandboxing the whole thing in https://chromium.googlesource.com/chromium/src/+/master/docs/design/sandbox.md

I'm not sure about the viability but I see no reason yet that this shouldn't work.

======
[1] https://invidious.snopyta.org/watch?v=cY9wANsoVx0 `Teal Meetup #1 - Dec 23 2020 - Teal programming language community meetup`
[2] https://invidious.snopyta.org/watch?v=HfnjUCRzRKU `Minimalistic typed Lua is here - FOSDEM 2020`
[3] https://invidious.snopyta.org/watch?v=VUThGgxOf28 `Minimalism versus types`

**Comment by hishamhm** [comment]
> The question is, does Teal impose any requirements on generated code beyond what was already required by the original code? 

Short answer, not really. Long answer: the code generated by Teal is for the most part equivalent to Lua code with the type annotations removed. Small differences are:

* mandatory:
  * the `is` operator translates to plain Lua `type()` checks, but that's a base standard library function from Lua which is safe for sandbox environments.
* optional:
  * the compat53 library is auto-required for producing more consistent semantics in the Teal standard library regardless of what Lua VM is running underneath. If you disable use of compat53, then you're subject to the differences across Lua versions, which may or may not matter to you.
  * when the VM is running Lua < 5.3, the bitwise operators (&, |, ~, <<, >>) generate code using the bit32 library (also available as part of compat53). If you don't want to use that library and your Lua VM does not have native bitwise operators, just don't use bitwise operators in Teal.

**Comment by hishamhm** [comment]
Closing this since I think the question was answered! If you have any further questions, feel free to reach out!
