### ISSUE TITLE
os.date([format [, time]]) -- type definition expects 'time' to be string?

### ISSUE THREAD

**Issue by JLPLabs** [teal-language/tl#305]
when passing a number for 'time' -- getting this error "argument 2: got number, expected string"

Lua Reference Manual:

**os.date()**:  If the time argument is present, this is the time to be formatted (see the os.time function for a description of this value).

**os.time()**: The returned value is a number, whose meaning depends on your system.

This might [be the place](https://github.com/teal-language/tl/blob/570135806c6e57bc6bb0d79a47286309dffce8b0/tl.tl#L4123) in tl.tl to fix it (maybe... I'm very new to tl)

from: `a_type { typename = "function", args = { STRING, OPT_STRING }, ...`
to: `a_type { typename = "function", args = { STRING, OPT_NUMBER }, ...`

**Comment by hishamhm** [comment]
@JLPLabs you are correct! Do you want to submit a pull request so that your fix gets the credit? If not, we can fix it on our end too, no worries!

Thank you for reporting, and welcome to Teal!

**Comment by JLPLabs** [comment]
@hishamhm -- thanks for the welcome. I'm having fun learning Teal. Please do fix it on your end.
(maybe if I add something of material value in the future I'll learn the process for pull requests (and the corresponding/obligatory testing))

**Comment by hishamhm** [comment]
Fixed in `master`, it will be included in the next release :)
