### ISSUE TITLE
tl check issue?? -- math.log (x [, base]) vs math.log(x)  -- Lua versions 5.2+ vs 5.1

### ISSUE THREAD

**Issue by JLPLabs** [teal-language/tl#308]
Starting with Lua version 5.2, the two `log` functions (`math.log` and `math.log10`) have been combined into one (`math.log`) with an optional _base_ argument.

I don't know if the below example is really an error, since Teal is trying to work across so many versions... 

This correct code will generate a tl check error:

`local x = math.log(val, 10)        --> wrong number of arguments (given 2, expects 1)`

I am not positive how to solve it, but maybe a "VARARG" on [this line](https://github.com/teal-language/tl/blob/0372d195f8493734d157d9aa3e36eeb159a3117f/tl.tl#L4120)? Or not, if this is really a philosophical issue...

In my view this is not a high priority issue... something to resolve someday, perhaps.

**Comment by hishamhm** [comment]
Fixed in Teal 0.10.0 :)
