### ISSUE TITLE
Convenient way of generating Lua files for every tl file?

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#31]
Right now, it seems like I need to manually call `tl gen <filename>` for every tl file in my project.

While I can write a script to automate this, I suppose it would be nice if there was a built-in way of generating Lua files for multiple tl modules at once.

For instance, in TypeScript, we can specify the input files inside [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) and run `tsc` to compile the whole project.

**Comment by mrtnpwn** [comment]
You can use [Tup](http://gittup.org/tup) for that I guess

```tup
: foreach *.tl |> tl gen %f |> %B.lua
```

I haven't test it yet but that's how it works.

**Comment by hishamhm** [comment]
I guess we can call this one fixed by #42, since you can run `tl gen *.tl` now!

**Comment by pdesaulniers** [comment]
Yes, that works. However, I would prefer if there was some way to specify the input files inside `tlconfig.lua`. That way, users would not have to rely on a shell-specific script or command to build the project.

For instance, the syntax for globs is shell dependent, especially when we get to patterns like `**/*.tl`. Also, my `build.sh` script would not work in cmd.exe :(

I'd be happy if tlconfig supported something akin to the ["include" and "exclude" properties in tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#examples). This would allow using globs in a platform independent manner. 

For the time being, though, I suppose a simple `files` array would be good enough.

**Comment by hishamhm** [comment]
> For the time being, though, I suppose a simple files array would be good enough.

Yeah, that should be an easy add. Anything involving globs would take some extra dependency to do the directory traversal.

**Comment by pdesaulniers** [comment]
It seems like this library could do the job: https://github.com/starwing/lpath. It seems a tiny bit obscure, but it does support globs:
```lua
local fs = require("path.fs")

-- find all .lua files in directory "game"
local src = "game/*/*.lua"

local files = fs.glob(src)

for _, v in ipairs(files) do
	-- do something
end
```
This library could also be used for building paths in https://github.com/hishamhm/tl/issues/47.

Are you aware of a better library for this?

**Comment by hishamhm** [comment]
> Are you aware of a better library for this?

Not really! At first glance it doesn't look like either of them supports the zsh/typescript `**` notation for recursive descent, but I don't know if that's a must-have either (maybe some toggle in the libraries make them expand all subdirs in globs? or maybe contacting the module authors about it would be a good idea?).

In any case, I have no immediate preference, it's up to you to pick the library if you're interested in adding the feature!

**Comment by euclidianAce** [comment]
@hishamhm So I'm working on a pr for this and was wondering if we should change the `--include` option to mimic tsconfigs. My thought process is that if you want to include extra paths, you should do that in the shell with `LUA_PATH` and `LUA_CPATH`. Otherwise I'd probably call it `--input` or something. Any thoughts?

**Comment by pdesaulniers** [comment]
@euclidianAce I added the `--include` flag for text editor support. That way, the typechecker works as expected automagically when you open a Teal project. For this use-case, I'm not sure if people want to mess around with `LUA_PATH` and `LUA_CPATH` manually.

**Comment by hishamhm** [comment]
I kinda like the fact that `-I` (uppercase i) and `-l` (lowercase l) have vaguely similar meanings as they do for `gcc`. Don't mind if the long form `--include` becomes `--include-path` or something.

**Comment by pdesaulniers** [comment]
Fixed by https://github.com/teal-language/tl/pull/177.
