### ISSUE TITLE
playgrounds don't work with users with case sensitive names

### ISSUE THREAD

**Issue by darrenjennings** [teal-language/tl#314]
e.g. @euclidianAce's playgrounds haven't been working. Workaround is that we can `toLower` the alias in the meanwhile.

Relevant issue:
https://github.com/netlify/cli/issues/969

**Comment by hishamhm** [comment]
I was wondering if it was the uppercase character in the name or the fact that the PRs came from a non-master branches!

> Workaround is that we can toLower the alias in the meanwhile.

Sounds like a plan; you can't have two Github usernames that differ only on case, I think ( https://github.com/euclidianace/ works the same as https://github.com/euclidianAce/ )
