### ISSUE TITLE
setmetatable doesn't want to hang out with other generic functions

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#322]
(will update title when I have any vague semblance of what is actually going on here)

Look, I have no idea whats happening. At first I thought it was related the the `setmetatable` changes, (and it might probably is, but not in the way I thought), then I thought #318 was the root cause, but now I'm using the branch that fixes it. Now I've been able to reduce it to the following cases and I have actually no idea whats going on.

I'll just list some code snippets and the result of `tl check` and hope somebody else can even begin to think of what is happening:

```
local function my_unpack<T>(list: {T}): T...
end
local tbl_unpack = table.unpack or my_unpack
local map: {string:number} = setmetatable({}, { __mode = "k" })
```
```
2 errors:
blah.tl:5:7: in local declaration: map: got <unknown type>, expected {string : number}
blah.tl:5:43: argument 1: got {}, expected <unknown type>
```
swapping the `or` is fine though?
```
local function my_unpack<T>(list: {T}): T...
end
local tbl_unpack = my_unpack or table.unpack
local map: {string:number} = setmetatable({}, { __mode = "k" })
```
```
no errors
```
so is moving the `tbl_unpack` definition
```
local map: {string:number} = setmetatable({}, { __mode = "k" })
local function my_unpack<T>(list: {T}): T...
end
local tbl_unpack = table.unpack or my_unpack
```
```
no errors
```
Or if `my_unpack` doesn't take any arguments or return anything
```
local function my_unpack()
end
local tbl_unpack = table.unpack or my_unpack
local map: {string:number} = setmetatable({}, { __mode = "k" })
```
```
no errors
```
and none of these error if the `setmetatable` call is taken away

I want to say its something about the internal state of typevars/generics getting messed up when `or`ing two generics together and now that `setmetatable` is generic, something is happening there.
But after messing around with this I could be lead to believe anything is happening

**Comment by hishamhm** [comment]
This pinned down some freak behavior I have observed before but could never quite put my finger on!

I think I got a small fix going in #323, let me know if it works for you!
