### ISSUE TITLE
Error for nested records with metamethods in renamed modules

### ISSUE THREAD

**Issue by wqferr** [teal-language/tl#326]
If you have a `my_huge_lib_name.d.tl` containing the following:

```lua
local record my_huge_lib_name
  record nested_type
    f: function(my_huge_lib_name.nested_type)
    metamethod __add: function(my_huge_lib_name.nested_type, number)
  end
  new: function(): my_huge_lib_name.nested_type
end
return my_huge_lib_name
```

The following code will error at line 4 with `"argument 1: got {f: function(my_huge_lib_name.nested_type)}, expected my_huge_lib_name.nested_type"`:

```lua
local lib = require 'my_huge_lib_name'
local v = lib.new()
v:f() -- this works fine
print(v + 2)
```

HOWEVER, the error goes away if instead of `lib`, the result of `require` is stored in a variable of the same name as the lib:

```lua
local my_huge_lib_name = require 'my_huge_lib_name'
local v = my_huge_lib_name.new()
v:f() -- still works, as expected
print(v + 2) -- now this also works
```

**Comment by hishamhm** [comment]
Fixed in `master`, and added your testcase to the test suite!
