### ISSUE TITLE
How to do dynamic dispatch on require

### ISSUE THREAD

**Issue by daelvn** [teal-language/tl#334]
While setting up my project, I decided to use a project layout based on an `init.tl` file that would import either `posix.tl` or `windows.tl` based on the current platform, so that `init.tl` would serve as an alias. However, I did not want to have a duplicate codebase, so I created an `internal.tl` file whose return value depends on the module used to call it. Some definitions in `internal.tl` were platform-dependent, but since the module only operates on strings, I still wanted to let the users choose either module regardless of their current platform. As such, `internal.tl` returns a function with a signature `function(WINDOWS: boolean): {string:any}`, `windows.tl` and `posix.tl` just contain `return (require "internal")(bool)` (where `bool` is true or false), and `init.tl` contains a simple platform check that returns either `require "windows"` or `require "posix"`.

I believe that this setup is correctly typed, but when trying to test it from a `test.tl` file, requiring `init.tl` and putting the result in a local, detects the type as `boolean` and not `{string:any}`, yet when I do `print(type(require "init"))`, I get `"table"`.

Here is a minimal setup I could use to replicate what I believe is a bug:

```
minimal/
  back.tl
  middle-true.tl
  middle-false.tl
  front.tl
  proof.tl
```

`back.tl`: `return function(bool: boolean): {string:any} return {bool = bool} end`
`middle-true.tl`: `return (require "minimal.back")(true)`
`middle-false.tl`: `return (require "minimal.back")(false)`
`front.tl`: `if true then return require "minimal.middle-true" else return require "minimal.middle-false" end`
`proof.tl`: `local front = require "minimal.front"`

Running `tl check` will mark `front` as an unused local of type `boolean`, which is incorrect. ~~While it is certainly possible to hide this error by using `require"minimal.front" as {string:any}`, I don't believe I should have to do this for something that the typechecker is incorrectly guessing.~~

Edit: After more tinkering, it is not possible to hide the error casting it to `{string:any}` or `{string:function}`, because then the signatures of every method in the module are not regarded at all, effectively invalidating any usage of the functions.

**Comment by hishamhm** [comment]
Thank you for reporting and for the detailed explanation!

> `front.tl`: `if true then return require "minimal.middle-true" else return require "minimal.middle-false" end`

At this time, Teal does not do control-flow-based type inference for return types in modules. A module is naively assumed to be of the type of a `return` statement issued at the top scope level (in other words, the `if` there it's throwing it off). 

I assume this should work then:

```lua
local ret: {string:any}
if true then
   ret = require "minimal.middle-true"
else 
   ret = require "minimal.middle-false"
end
return ret
```

Please let me know if this does the trick!

**Comment by daelvn** [comment]
I did this on the `front.tl`-equivalent of my project, but now, using it becomes nearly impossible (at the type level, of course): While trying to address any function in the module, the error now becomes `not a function: <any type>`, which is the problem I described in my last edit to the original issue. For it to be usable, I would essentially have to re-type the whole module separately; The type signatures of each function essentially disappear by using `any`. While sure, it would still work with Lua, I wanted to enjoy the benefits of type signatures from the module.

**Comment by hishamhm** [comment]
> The type signatures of each function essentially disappear by using any.

Yes, this is what `any` means, because given a variable of type `any`, the compiler has no way of knowing statically (at compile time) what the variable contains dynamically (at runtime):

```lua
local mystery: any
if math.random(2) then
   mystery = "hello"
else
   mystery = 123
end

-- the compiler has no way of knowing what is `mystery` here and typechecking its uses!
```

When you do something like `if X then return require "A" else return require "B" end`, for this to work (in a practical, runtime, sense) the implicit promise here is that `require "A"` and `require "B"` return the exact set of types, so that client code can call the returned functions without knowing which one of "A" or "B" was returned.

For Teal to be able to type check the client code, yes, you'll need to make this promise explicit, writing a type definition that essentially _declares the interface_ of the module:

```
-- public interface of front.tl
local record Front
   func_a: function(number): string
   func_b: function(boolean, {string}): number, string
end

local ret: Front

if true then
   ret = require "minimal.middle-true"
else 
   ret = require "minimal.middle-false"
end

return ret
```

This has the benefit that Teal will actually verify for you at compile time that both "minimal.middle-true" and "minimal.middle-false" do indeed present compatible interfaces!

Note that you only normally only need to do this when you're doing this kind of dynamic dispatch over `require`.

**Comment by hishamhm** [comment]
> (EDIT: updated the comment to add the needed casts)

It is possible to avoid the casts `as Front` by creating a separate module with the type definition only, requiring it from both middle-true and middle-false implementations and using the type definition there as the return type of the modules. _This_ will verify at compile time that both modules return the same interfaces.

**Comment by lenscas** [comment]
> For it to be usable, I would essentially have to re-type the whole module separately

Most languages will require you to make some kind of type (often in the form of an interface) that both modules will need to follow.

**Comment by hishamhm** [comment]
Declaring the common interface:
```lua
-- minimal/type/Front.d.tl
local record Front
   bool: boolean
end
return Front
```
Making `back` return the common interface:
```lua
-- minimal/back.tl
local Front = require "minimal.type.Front"
return function(bool: boolean): Front return {bool = bool} end
```
Fixing up the return type for `front` as mentioned above, no casts:
```lua
-- minimal/front.tl
local Front = require "minimal.type.Front"
local ret: Front
if true then
   ret = require "minimal.middle-true"
else
   ret = require "minimal.middle-false"
end
return ret
```

`middle-false.tl`, `middle-true.tl` and `proof.tl` remain unchanged from your example above (the types flow correctly from module to module).

**Comment by hishamhm** [comment]
I fixed the issue with `return` nested inside `if` statements at the toplevel! 

Now your original `front.tl` works too. All you need is to declare the proper type for the return of `back.tl` (see the test case added in #335, which is based on your repro list above, thanks!)

**Comment by daelvn** [comment]
Awesome! I've checked out the test cases, shortly I will reinstall and start working again with the new model. Is there an issue tracking progress for automatically-generated `.d.tl` files?
