### ISSUE TITLE
Passing types across files.

### ISSUE THREAD

**Issue by daelvn** [teal-language/tl#336]
While trying to create the `.d.tl` file for the example in #334, I moved over the types used in the signatures to the `.d.tl` file as well, and decided to just pass them back along with the record. I did this as a local, wanting to avoid just throwing a type into the global environment (although I am willing to use a global to resolve this issue). This gave me a type error in one of the type signatures of the many functions the record contains, despite there being more functions with the same return value: `in return value: record field doesn't match: splitSearchPath: return 1: got {FilePath}, expected {FilePath}`. Again, I setup a minimal setup to reproduce this error:

`minimal/typedef.d.tl`:
```lua
local type Alias = number
local record Front
  action: function(number): {Alias}
end
return {Alias=Alias, Front=Front}
```

`minimal/back.tl`:
```lua
local _Front = require "minimal.typedef"
local Front  = _Front.Front
local type Alias = _Front.Alias

return function(bool: boolean): Front
  local function action(n: number): {Alias}
    if bool then print "has bool" end
    return {n} as {Alias}
  end
  return {
    action = action
  }
end
```

This effectively generates an error: `in return value: record field doesn't match: action: return 1: got {Alias}, expected {Alias}`. Changing `{Alias}` to just `Alias` reveals something else:

```
in return value: record field doesn't match: action: return 1: Alias (defined in minimal/back.tl:6) is not a Alias (defined in ./minimal/typedef.d.tl:3)
```

This would indicate to me that the types are not the same based on where they are defined, and that `local type Alias = number` is not `local type Alias = _Front.Alias -- (number)`. If this is the case:

a. Are globals the proper way of sharing types across files? And if not,
b. What would be the accepted way of doing this?

Thank you.

**Comment by hishamhm** [comment]
Try with `local Alias = _Front.Alias` (without `type`) instead of `local type Alias = _Front.Alias`

**Comment by daelvn** [comment]
Oh, I can't believe it was so simple, I'd have thought I had tried this before. Thanks!

**Comment by darrenjennings** [comment]
This is a gotcha that I ran into as well. Shouldn't the example @daelvn tried work or is the intended usage that you would not use the type keyword again?

**Comment by euclidianAce** [comment]
Theres some discussion of this in #269, but the gist of the current behavior is that `local type` creates a new type from a valid type expression and just `local` creates a variable that takes any teal expression but can be used as a type and a value
