### ISSUE TITLE
`table.unpack` returns wrong type when dealing with type aliases.

### ISSUE THREAD

**Issue by daelvn** [teal-language/tl#337]
Take the following snippet (minimal setup for reproducing bug):
```lua
local type Alias = string
local t = {"a", "a"} as {Alias, Alias}
local a, b = table.unpack(t)
```
In this case, `tl check` reports `a` and `b` to be both of type `Alias | Alias` (a union of itself, somehow). This does not happen with primitives:
```lua
local t = {"a", "a"} as {string, string}
local a, b = table.unpack(t)
-- both a and b are reported to be of type string
```

This may possibly be related to `table.unpack`'s type signature, which is nonstandard (`function({@a},number,number):@a`).

**Comment by hishamhm** [comment]
@daelvn Fixed, things like `Foo | Foo` shouldn't appear in unions anymore!
