### ISSUE TITLE
Fixed length array syntactic sugar

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#341]
A good use case of tuples is fixed length arrays, adding some sugar for it would be nice to encourage its use.

Something simple like
```
local arr: { 3 of number }
```
or
```
local arr: { 3 * number }
```

The implementation is simple enough and i have a branch with it, but im open to take some suggestions on syntax

**Comment by euclidianAce** [comment]
Oh, and this would allow for unary tuples to be written without using an explicit `nil` type which i feel should be discouraged

**Comment by lenscas** [comment]
so... say hello to const generics?

**Comment by euclidianAce** [comment]
After a quick look at the rfc, sorta? This only allows number literals though making it just syntactic sugar over existing stuff

**Comment by hishamhm** [comment]
I'll be direct and say I don't think we should add this at this point.

There's a baggage of expectations that comes with the notion of "fixed length arrays"; the first one that comes to mind is bounds checking, to verify that the arrays are truly fixed length. Then it ties into the muddy question of "array lengths in Lua" in general. Is an array with a hole such that the initial sequence forms a valid n-ary tuple an "array of fixed length n"? If you nil an element in the middle of the array and the value of `#a` changes by Lua rules, isn't it weird that an array x of "fixed length 5" returns anything other than 5 for `#x`? I think we can't claim these to be really "fixed length arrays", and I don't think adding this as a "syntactic shortcut for long tuples" (or unary tuples, which I see more as a degenerate case) is worth adding, weighing the benefits, language growth cost, and possible confusion.

Roberto says something insightful about the cost of adding a feature to a language should factor both the cost of implementing and the cost of explaining/documenting, including all possible gotchas. I don't think we have a good cost/benefit here, in particular for the latter.

**Comment by euclidianAce** [comment]
Okay, fair enough
