### ISSUE TITLE
type check of `{record}` may give some wrong result

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#348]
```
local record test_t
    a: number
    b: number
end

local _: {test_t} = {
    {
        a=1,
    },
    {
        a=1,
        b=2
    }
}
```

the error message is `in local declaration: _: got {{string : number}} (from {{string : number}, {a: number, b: number}}), expected {test_t}`

the code snippet below is correct

```
local _: {test_t} = {
    {
        a=1,
        b=2
    },
    {
        a=1,
    },
}
```

**Comment by hishamhm** [comment]
@virusdefender Fixed! The example above was added to the test suite as a test case!
