### ISSUE TITLE
The 'include_dir' compiler option does not include directory module (init.lua)

### ISSUE THREAD

**Issue by jmcmorris** [teal-language/tl#353]
Hello! I've been using teal for a few weeks now and it is great so far.

I ran into an issue today with a init.tl module not being found properly. I have the compiler option `include_dir = {'data/scripts/',}` which finds all of my modules correctly except when I added the file `"data/scripts/ui/init.tl"`. I was surprised by this and am currently working around it simply by using `require("ui.init")`. I tried playing around with include_dir but after looking at the src I discovered it'll only add `?.lua` to the path with the include_dir entry. Is there something I'm missing or doing wrong here? This is obviously not a big deal since it can be easily worked around but it would be nice for it to work. Thanks!

**Comment by hishamhm** [comment]
> Hello! I've been using teal for a few weeks now and it is great so far.

Thank you for the positive feedback!

> it'll only add ?.lua to the path with the include_dir entry. Is there something I'm missing or doing wrong here?

I think it shouldn't be hard to fix this behavior of `include_dir` in the `tl` main script. If you want to give it a try and send a PR, consider yourself encouraged to give it a shot!
