### ISSUE TITLE
A `tl init` command for easy project initialization

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#363]
Something that would setup the current dir as with something like
```
.
├── build
├── src
└── tlconfig.lua
```
and `tlconfig.lua` would have build\_dir and source\_dir set, with maybe a `src/main.tl` that's a hello world or something

**Comment by lenscas** [comment]
maybe it can be expanded to have a `tl new {path}` which first creates the directory given in path and then runs `tl init` inside of it?

**Comment by hishamhm** [comment]
Closing this one since it's addresed by [cyan](https://github.com/teal-language/cyan)! :rocket:
