### ISSUE TITLE
a strange behavior about tl gen compat

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#365]
tested on tl master branch

the project structure is 

```
✗ tree
.
|-- errors.tl
|-- log.tl
`-- tlconfig.lua

0 directories, 3 files
```

`errors.tl`

```lua
local errors = {}

-- the real type is string
local record err_t
end

function errors.newf(msg: string, ...:any): err_t
    return string.format(msg, ...) as err_t
end

return errors
```

`log.tl`

```lua
local record log
end

local record logger
    name: string
    __index: logger
end

logger.__index = logger

function log.get_logger(name: string): logger
    local self = setmetatable({} as logger, logger as metatable<logger>) as logger
    self.name = "[" .. name .. "] "
    return self
end

return log
```

`tlconfig.lua`

```lua
return {
    gen_compat = "optional",
}
```

`tl build` will show `log.tl:12:55: argument 2: metatable<logger> is not a metatable<@a>`

if you 

 - set `gen_compat = "off"`
 - or remove `errors.tl` (obviously, `log.tl` does not require `errors.tl`

tl can build without any error message

another error massage is `tests/tests.tl:54:13: argument 0: FILE is not a FILE`, it also can be resolved by setting `gen_compat = "off"`.

**Comment by hishamhm** [comment]
@virusdefender This is now fixed on the master branch!

**Comment by hishamhm** [comment]
Thank you for the complete reproduction case with detailed instructions!
