### ISSUE TITLE
Broken type inference of if conditionals

### ISSUE THREAD

**Issue by lewis6991** [teal-language/tl#382]
Regression in 0.11.0.

Snippet below should cause no errors.
```lua
local function foo(a: number | string | function)
  if a is string and a == 'hello' then
    return
  elseif a is string and a == 'bye' then
    return
  end
end

foo('hello')
```

```
❯ tl check test.tl
========================================
2 errors:
test.tl:5:12: a (of type number | function(<any type>):<any type> (inferred at test.tl:5:22)) can never be a string
test.tl:5:22: cannot resolve a type for a here
```

**Comment by hishamhm** [comment]
@lewis6991 Thank you for the report! I'll look into a fix.

In the meantime, you should be able to remove the `is` test when doing a `==` test, since `==` now does narrowing of unions.

```lua
local function foo(a: number | string | function)
  if a == 'hello' then
    print(a:upper()) -- a is a string!
  elseif a == 'bye' then
    print(a:lower()) -- a is a string!
end

foo('hello')
```

**Comment by hishamhm** [comment]
@lewis6991 Fixed in master! A release is coming shortly! Thank you for the prompt feedback for 0.11!

**Comment by hishamhm** [comment]
@lewis6991 Thank you for the feedback!! I must tell you thinking about how to best solve this took me away some sleeping hours, but building the internal logic engine is a fun problem to work on. I've just pushed a

**Comment by lewis6991** [comment]
Sure will do and will report back.

**Comment by lewis6991** [comment]
Change appears to work well, no more errors/warnings. 👍
