### ISSUE TITLE
bug: non const variable is marked as const

### ISSUE THREAD

**Issue by lenscas** [teal-language/tl#383]
in the below example, I can not assign something to `negatives` again, as it is marked as `<const>`
```lua
local negatives = {}
negatives[1] = 1
negatives = {}
```

Error: `cannot assign to <const> variable`

playground: https://teal-playground.netlify.app/?c=bG9jYWwgbmVnYXRpdmVzID0ge30KbmVnYXRpdmVzWzFdID0gMQpuZWdhdGl2ZXMgPSB7fQo%3D)

Note: if I give the variable a type myself like the next example, then it works
```lua
local negatives :{number} = {}
negatives[1] = 1
negatives = {}
```
It also works if the array is created starting with a value
```lua
local negatives = {1}
negatives[1] = 1
negatives = {}
```

**Comment by hishamhm** [comment]
@lenscas that's odd, I don't remember how that slipped in! anyway, it's fixed in master — a release is coming shortly!

**Comment by lenscas** [comment]
oh well, shit happens. Thanks for fixing it :)

**Comment by lenscas** [comment]
@hishamhm Looks like you forgot to close this one :)
