### ISSUE TITLE
math.randomseed -- tl.tl has wrong return type

### ISSUE THREAD

**Issue by JLPLabs** [teal-language/tl#388]
<<I've never done a pull request. This might be an easy one for a newbie, like me. Do I have to set up full environment, with tests before I can do a pull request?>>

from Lua 5.4 reference manual...

[math.randomseed](https://www.lua.org/manual/5.4/manual.html#pdf-math.randomseed) ([x [, y]])

This function returns the two seed components that were effectively used, so that setting them again repeats the sequence. 

----
I believe an update to tl.tl will match Lua 5.4. 
* add a second input number
* return two numbers

[line 4694](https://github.com/teal-language/tl/blob/18fcdd06a934a87c02d21f4de40f4e28f4a3a1d9/tl.tl#L4694)

is:
`["randomseed"] = a_type { typename = "function", args = TUPLE { NUMBER }, rets = TUPLE {} },`

should be:
["randomseed"] = a_type { typename = "function", args = TUPLE { NUMBER, NUMBER }, rets = TUPLE { NUMBER, NUMBER} },

**Comment by hishamhm** [comment]
Thanks for reporting!

> I've never done a pull request. This might be an easy one for a newbie, like me. Do I have to set up full environment, with tests before I can do a pull request?

For a simple change like this, a one-line PR is fine, and yes, this is a perfect one for your first PR! A while ago I [wrote a tutorial on how to do pull requests](http://hisham.hm/2016/01/01/how-to-make-a-pull-request-on-github-a-quick-tutorial/), it may be useful for you!

**Comment by hishamhm** [comment]
Fixed by #389 :)
