### ISSUE TITLE
regression in type flow inference?

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#390]
Just pulled from `master` and some code now doesn't compile due to constructs like these
```lua
local record Foo
end
local makeFoo: function(string): Foo
local a: string | Foo
local _b: Foo = a is string and makeFoo(a) or a
```
now failing to compile. It seems that teal no longer narrows `a` down to `Foo` in the `or` branch
```
$ ~/dev/tl/tl check foo.tl
========================================
1 error: foo.tl
foo.tl:6:44: cannot use operator 'or' for types Foo and string | Foo
```

**Comment by hishamhm** [comment]
That's true, but the new behavior is actually correct! Consider this valid implementation of makeFoo:

```lua
makeFoo = function(s: string): Foo
   return nil
end
```

If the narrowing was allowed, if you gave a string in `a`, you would end up with a string in variable `_b` of type Foo.

**Comment by euclidianAce** [comment]
Ah, right, `nil`. That makes sense then

**Comment by hishamhm** [comment]
I just pushed a change making the result of assert known to be truthy, such that this works:

```
local record Foo
end
local makeFoo: function(string): Foo
local a: string | Foo
local _b: Foo = a is string and assert(makeFoo(a)) or a
```
