### ISSUE TITLE
code after a `return` causes syntax error

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#391]
```
local function foo(): number
   return 1

   print()
end
```
```
$ tl check foo.tl 
========================================
2 syntax errors:
foo.tl:2:12: syntax error
foo.tl:4:4: syntax error, expected one of: '$EOF$', ';', 'else', 'elseif', 'end', 'until', ','
```

**Comment by hishamhm** [comment]
Code after return is a syntax error in Lua as well!

**Comment by euclidianAce** [comment]
Huh... TIL! I feel like I've used early returns like that when debugging something but I must be mis-remembering, or have had them in some if statement

**Comment by Ghost4Man** [comment]
But the _Internal Compiler Error_ when you use a semicolon after the return is not intended, right?
![Console demonstration of an internal compiler error when using code after return with semicolon](https://user-images.githubusercontent.com/8436102/142686838-35749e77-1430-4bda-857e-a6f11f7324fe.png)

**Comment by hishamhm** [comment]
@Ghost4Man yes, it shouldn't be generating an ICE like that! Let's open a new issue!
