### ISSUE TITLE
 `tl types` command failed if typename is none

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#393]
if `rt.typename` is `none`, `typename_to_typecode ` https://github.com/teal-language/tl/blob/db6b345235f53442b1da4e50ebe529d1d20666b5/tl.tl#L8562 will raise an assertion exception

```
stack traceback:
	[C]: in function 'error'
	...e/ubuntu/.luarocks/share/lua/5.1/compat53/module.lua:161: in function 'assert'
	/home/ubuntu/.luarocks/share/lua/5.1/tl.lua:8567: in function 'get_typenum'
	/home/ubuntu/.luarocks/share/lua/5.1/tl.lua:8672: in function 'get_types'
	...ntu/.luarocks/lib/luarocks/rocks-5.1/tl/dev-1/bin/tl:927: in main chunk
	[C]: ?
```

**Comment by hishamhm** [comment]
Could you provide a minimal code snippet where this happens? There shouldn't be any `none` types exposed in the `tl types` info. Thank you!

**Comment by virusdefender** [comment]
sorry, i was to lazy to reproduce it in a complex project at that time

may be it's related to the goto label

```
local function a()
    ::continue::
end
```

**Comment by hishamhm** [comment]
Yes, that's it, thank you! A fix is on the way.
