### ISSUE TITLE
support octal number

### ISSUE THREAD

**Issue by virusdefender** [teal-language/tl#410]
like

```
local a: number =  0o644;
```

it can be convert to decimal number in Lua

```
local a = 420
```

**Comment by hishamhm** [comment]
Thanks for the suggestion! But I've been avoiding adding isolated "nice-to-have" features to the language for now, to keep the project size under control and avoid slippery-slope arguments ("once you start, when do you stop adding stuff"). My criteria for adding features are admittedly subjective, but I try to follow a logical path.

Regarding octals, the existing Lua functionality for that that you can use is is

```
local a = tonumber("644", 8)
```

It's a bit more verbose, but hey, `str:sub(i, i)` is also more verbose than `str[i]`, which I'm sure a lot of people would also love to have...
