### ISSUE TITLE
For things like JSON parsing, distinguish between an 'any' and 'unknown' type

### ISSUE THREAD

**Issue by Ruin0x11** [teal-language/tl#411]
In some definition files for TypeScript, certain functions can return `any`. However, it was later realized that this is too forgiving for things like JSON parsing, because many people ended up using the `any` as an untyped map. What was actually desired in many cases was to deserialize the JSON into a concrete type, but because there was no type check that enforced this, such a contract was not explicit in the code.

The solution was to introduce the type `unknown` instead of `any`, which would always typecheck. However, the existing definition files could not be changed to take advantage of this new strictness, because it would break existing code.

https://github.com/microsoft/TypeScript/issues/26188

I hope that if Teal gets something like a JSON parser that it can avoid this issue, because it's the kind of thing that cannot be fixed in a backwards compatible way.

**Comment by lenscas** [comment]
Maybe I am misunderstanding what you are asking for. The way I read it, `please add typescript's unknown type`.

Teal's `any` is already pretty much acting like typescript's `unknown`. For example, this code does not compile
```lua
local a : any = "nice"
local b = a .. "see?"
```
the error that you get is
```
cannot use operator '..' for types <any type> and string "see?"
```
https://teal-playground.netlify.app/?c=bG9jYWwgYSA6IGFueSA9ICJuaWNlIgpsb2NhbCBiID0gYSAuLiAic2VlPyI%3D

**Comment by Ruin0x11** [comment]
Okay, thanks for clarifying. I guess it was my misunderstanding.
