### ISSUE TITLE
Busted test suite doesn't work on Windows

### ISSUE THREAD

**Issue by DragonDePlatino** [teal-language/tl#426]
I would like to submit a PR but cannot get the busted tests to run. The earliest tests like `assignment to union resolves union types in map keys` are passing, but any test involving a temporary directory is failing. These are the 3 variations I found:

```
Failure ΓåÆ spec\api\process_spec.lua @ 24
tl.process process should cache modules by filename to prevent code being loaded more than once (#245)
./spec\util.lua:224: No such file or directory

stack traceback:
        ./spec\util.lua:224: in function 'spec.util.write_tmp_dir'
        spec\api\process_spec.lua:27: in function <spec\api\process_spec.lua:24>

...

Failure ΓåÆ spec\cli\check_spec.lua @ 6
tl check on .tl files works on empty files
./spec\util.lua:205: /tmp/teal_tmp17654419.tl: No such file or directory

stack traceback:
        ./spec\util.lua:205: in function 'spec.util.write_tmp_file'
        spec\cli\check_spec.lua:7: in function <spec\cli\check_spec.lua:6>

...

tl gen setup
./spec\util.lua:188: Unable to change working directory to '/tmp'
No such file or directory


stack traceback:
        ./spec\util.lua:188: in function 'spec.util.chdir_setup'
```

On a related note, to get the makefile working I need to change `busted` to `busted.bat`. There isn't a binary distribution of busted so I think it's safe to assume it will always be a batch file on Windows when installed via LuaRocks. Can I modify the makefile to detect the platform and switch on that?

Environment:
Windows 8.1 Pro
MinGW-w64 via MSYS2 installation
Command Prompt / Powershell / Git Bash / MSYS2 Shell

**Comment by hishamhm** [comment]
That probably won't be the only issue you would hit... the test suite was written for running on Unix (it refers to things like `/tmp`, `/dev/null`...), it would need to be ported to run on Windows.

**Comment by DragonDePlatino** [comment]
Could I modify the test suite to work out of a project-level directory instead of a global one for better portability? Then just add that path to the .gitignore or make sure it's cleaned up after tests?

**Comment by hishamhm** [comment]
@DragonDePlatino if the portability issues are few and can be abstracted away in `spec/util.lua`, I think we could take the changes.

Something like: (rough sketch)

```
local detected_os = package.config:sub(1,1) == "\\" and "windows" or "unix"

local TMP = detected_os == "unix" and "/tmp" or os.getenv("TEMP")

-- and so on...
```

You'd probably need a helper function for the non-portable uses of io.popen, I guess. I don't have a Windows machine, so I can't make or test the necessary changes...
