### ISSUE TITLE
Unicode BOM symbol support.

### ISSUE THREAD

**Issue by nagolove** [teal-language/tl#435]
Hi. I do not know is it real issue, but then my editor save BOM symbols in file(on Windows) Teal parser get error like this:
```
3 syntax errors:
sub\code2.tl:1:1: invalid token '∩'
sub\code2.tl:1:2: invalid token '╗'
sub\code2.tl:1:3: invalid token '┐'
```

**Comment by hishamhm** [comment]
Yes, skipping the initial UTF-8 BOM ("\xEF\xBB\xBF") from files when running the lexer would be good! Looks like Lua does this as well.
