### ISSUE TITLE
Required Lua Version?

### ISSUE THREAD

**Issue by tooolbox** [teal-language/tl#439]
Sorry if this is documented somewhere, but I'm wondering what the minimum Lua version requirement is, such as to do:

```lua
local tl = require("tl")
tl.loader()
```

I was guessing 5.1, but I would like to make sure.  Thanks!

**Comment by hishamhm** [comment]
Yes, it's Lua 5.1! More info in the docs here: https://github.com/teal-language/tl/blob/master/docs/compiler_options.md#generated-code

**Comment by tooolbox** [comment]
Great, thanks :)
