### ISSUE TITLE
problems with unpack

### ISSUE THREAD

**Issue by remdragon** [teal-language/tl#442]
I just discovered teal last night and I'm pretty excited to have found the project.

I've started running it against my largest project and I'm running into an issue with unpack.

I have my problem simplified down to the following:

```
global unpack: ( function({any}, number, number): any )

unpack = table.unpack or unpack -- Lua 5.1 or 5.2 table unpacker

function originate (
	call_url: {string:string}
): string
	local vars: {string} = {}
	for k, v in pairs ( call_url ) do
		if v ~= nil and v ~= '' then
			vars[#vars+1] = k .. '=' .. v
		end
	end
	return table.concat ( vars, ',' )
end
```

I am experiencing several issues with unpack:

1) How do I define unpack so that it can return a variable number of values depending on the number of elements in the first parameter, or at least define it to return an arbitrary number of elements?

2) Why is it confusing the call to pairs():

```
========================================
2 errors:
tl_unpack_considered_harmful.tl:9:22: argument 1: got <any type>, expected string
tl_unpack_considered_harmful.tl:11:22: cannot use operator '..' for types <any type> and string
```

3) Changing the definition of unpack to the following seems to put teal in an infinite loop:

```
global unpack: ( function<T>({T}, number, number): T )
```

tl --version
`0.13.1+dev`

**Comment by lenscas** [comment]
> How do I define unpack so that it can return a variable number of values depending on the number of elements in the first parameter, or at least define it to return an arbitrary number of elements?

teal already should make sure that `unpack` is available as `table.unpack` regardless of lua version. Then you don't have to define your own version. No need to define your own version

> Why is it confusing the call to pairs():

that is a weird one indeed

> Changing the definition of unpack to the following seems to put teal in an infinite loop:

does that happen to just `unpack` or also other functions. I put that line into the playground and it seems to work
https://teal-playground.netlify.app/?c=Z2xvYmFsIHVucGFjazogKCBmdW5jdGlvbjxUPih7VH0sIG51bWJlciwgbnVtYmVyKTogVCApCgpsb2NhbCBhID0gdW5wYWNrKHsxLDIsM30pCmxvY2FsIGIgPSBhICsgMQ%3D%3D

**Comment by remdragon** [comment]
> > How do I define unpack so that it can return a variable number of values depending on the number of elements in the first parameter, or at least define it to return an arbitrary number of elements?
> 
> teal already should make sure that `unpack` is available as `table.unpack` regardless of lua version. Then you don't have to define your own version. No need to define your own version

understood. I will test this, thanks. Hopefully not having to define unpack myself will fix the other issues I'm having, but you may want to look into that unpack/pairs confusion.

> 
> > Why is it confusing the call to pairs():
> 
> that is a weird one indeed
> 
> > Changing the definition of unpack to the following seems to put teal in an infinite loop:
> 
> does that happen to just `unpack` or also other functions. I put that line into the playground and it seems to work
> https://teal-playground.netlify.app/?c=Z2xvYmFsIHVucGFjazogKCBmdW5jdGlvbjxUPih7VH0sIG51bWJlciwgbnVtYmVyKTogVCApCgpsb2NhbCBhID0gdW5wYWNrKHsxLDIsM30pCmxvY2FsIGIgPSBhICsgMQ%3D%3D

If you paste my complete example into the playground, it also freezes up. For some reason the redefinition of unpack causes some real confusion with the pairs() function.

**Comment by hishamhm** [comment]
Any freeze is definitely a bug! I'll give it a closer look as soon as I get a chance!
