### ISSUE TITLE
.d.tl on my own files?

### ISSUE THREAD

**Issue by remdragon** [teal-language/tl#444]
I just read about .d.tl files and I'd really like to use them on my own files instead of having to pass them through the tl compiler. For one, tl is messing up the formatting of my code and for two it would eliminate a step in making adjustments before deploying an update.

When I run a check against my files, it doesn't seem to recognize that there's a .d.tl matching the .lua name. Is there something I need to do to get it to load the .d.tl file?

**Comment by lenscas** [comment]
I'm not entirely sure what you are trying to do. Are you trying to get teal to typecheck lua files? If so, this isn't something teal is doing. The use of .d.tl files is to tell teal what a .lua file exports, not to help typecheck a .lua file.

> I just read about .d.tl files and I'd really like to use them on my own files instead of having to pass them through the tl compiler.

.d.tl files contain just the type definitions of the values and functions that a .lua file exposes. They are only useful to the tl compiler

> For one, tl is messing up the formatting of my code

What is it doing to your code that it messes it up? I'm not aware of tl having a formatter and the generated lua should be formatted the same as the teal files, to make sure that stack traces point to the same line.

> When I run a check against my files, it doesn't seem to recognize that there's a .d.tl matching the .lua name. Is there something I need to do to get it to load the .d.tl file?

All you should need to do is place the .d.tl file such that the same require path can refer to both files. Or in other words: Place it next to the ,lua file.

**Comment by remdragon** [comment]
thank you for the reply.

I want to be able to take advantage of type checking without being forced to convert it back to runnable lua.

As far as the formatting issues, there's 4 that I've noticed so far:
1) it's removing comments *this is a big deal - forces me to go back to tl file to see them*
2) it's replacing tabbed indentation with spaces *easy fix with a command-line flag*
3) it's removing whitespace `type ( call_url )` -> `type(call_url)` *makes code a bit harder to read, especially diffs*
4) it's moving the close parenthesis *nitpicking but breaks my personal code standard thus confuses me why it's in the wrong spot*

I realize some people will think I'm stupid for not wanting to format my code the way "everybody" does and not see some of my issues as priorities. This is why I was trying to find some kind of out-of-band or comment-based type instrumentation for my source.

The following example:
```
function originate (
	call_url: string | {integer|string:string},
	origin: string,
	dialplan: string,
	context: string,
	cid_name: string,
	cid_num: string,
	timeout_sec: number|string
): string
	--[[
	call_url can be a string or a table, construct it like so ( do NOT use the literal string "1234..." as a uuid... ):
	{ 'digits', origination_uuid='1234...', hangup_after_bridge='false' } => '{origination_uuid=1234...,hangup_after_bridge=false}digits'
	{ 'digits' } => 'digits'
	--]]
	if type ( call_url ) == 'table' then
```

gets converted to this:

```
function originate(
   call_url,
   origin,
   dialplan,
   context,
   cid_name,
   cid_num,
   timeout_sec)






   if type(call_url) == 'table' then
```

**Comment by euclidianAce** [comment]
> I want to be able to take advantage of type checking without being forced to convert it back to runnable lua.

How are you running your code then? Are you using Teal as a type checker for just Lua code? While lax mode is okay, I wouldn't really recommend it and would say to just use Teal.

And I don't really understand the concern with having the compiled output of your code not being formatted the way you want?  It's the compiled output of your program, it isn't supposed to be read/treated like source code. The Teal code you posted is formatted the way you want, and the only reason the output is formatted at all is so that line numbers match up for errors.

Could you maybe describe your use case a bit more? I feel like there's an [XY problem here](https://en.wikipedia.org/wiki/XY_problem)

**Comment by remdragon** [comment]
When my code is deployed onsite with customer and customer calls me with a problem I need to troubleshoot, I'm going to be remoted into customer system troubleshooting their issues. Lua code is installed on system, not teal code. Much easier to look at the local lua code than to toggle back and forth with my development system. Heck I might not even have a development machine with me when the call comes in. This code will end up being installed in 24/7 emergency ( medical/FEMA ) environments so I could get a call any time of day.

Additionally, if I need to make a local edit to fix a bug on the spot, there's extra care to make sure that change gets backtracked to the original teal code.

**Comment by lenscas** [comment]
not sure if it would help, but it is possible to load teal files directly if you load the `tl.lua` file and call `tl.loader()`. 

This does mean that nothing is preventing you from writing broken code, as loading teal files directly like this doesn't run the type checker. However, assuming you already use a git repo you should be able to have a job running automatically whenever someone wants to merge code that runs `tl check` and rejects it if the the type checker fails.

The benefit is that there isn't a real compile step anymore and that you can just work with the teal files directly if you have to fix something on the spot. Note: `tl.lua` has NO external dependencies, EXCEPT for the `luacompat` module. HOWEVER if you know you will always run on the latest lua, you can just recompile the `tl.tl` file and give the flag to not include that. 


I have a similar setup for my card game, and though it isn't ready to be deployed yet it works quite well so far. Especially now that my main code (Rust) automatically embeds the `tl.lua` file for me. I just need to have teal installed and when I build my Rust code it finds the compiler and embeds it into the final binary and gives me a function to prepare the lua vm this way.

However, I'm guessing you don't have your lua/teal code embedded in another program. In which case, just vendor the `tl.lua` file and make this your new start file

```lua
local tl = require "tl"
tl.loader()
local main = require "main" --or any other file name you think is a good start
main()
```

**Comment by remdragon** [comment]
the code isn't embedded, but it's running inside another program ( FreeSWITCH ).
I don't know if luacompat is available in there but I'll check into that as an option. I already have a very small entry file and I wouldn't mind foregoing that as a .tl file as there's almost nothing happening in it.

What kind of a cpu/memory consumption hit would I take loading tl like this? I've already run into some scalability issues with the lua code in this project and had to pull some functionality out into a separate python process, so I worry that this could tip the scales back in the wrong direction. The way FreeSWITCH works it has to reparse my entire 214KB of lua every time a request is sent to the system and when we were load testing 500 simultaneous calls we were seeing multiple thousands of invocations per second.

In the meantime, I'm developing a code-refactoring tool that converts my comment-type-checked lua into tl then runs tl check and this is working *really* well so far.

So this:
```
function foo (
   bar --: integer -- how many bars to foo
) --: string
```

is getting translated to this:
```
function foo (
   bar: integer -- how many bars to foo
): string
```

the syntax is a bit terse, but I didn't want it to be too verbose. I find python's "# type: " just a bit too noisy

So far the translation tool is only about 60 lines of python code. In addition to function parameters and return types it can handle local variable declarations. I'm able to hide code from tl that it doesn't understand ( like my unpack redefinition from another issue ) and I'm able to hide code from lua that helps tl understand ( like record definitions )

If anybody is interested, I'm happy to share it you guys or on my github when it's proven.

**Comment by lenscas** [comment]
tl only needs to do something when (first?) loading the file.

As for the `luacompat` stuff you can simply feed `tl.tl` into teal and pass the flags to not require `luacompat`. Note: if you compile your `teal` code and don't give that flag then your generated lua code also ends up depending on `luacompat`.

**Comment by euclidianAce** [comment]
The performance of the loader depends on what you are doing. As lenscas says it really only affects startup, so if you have just one long running program then that's fine and will probably work for you. But if you are starting up a new Lua process each time (which is what it seems like you are doing), where the loader would have to do work each time then I think you'd see a noticeable performance hit (especially with 214K of code).

If there's a way you can keep certain modules loaded and hot reload the ones you are changing that could be a solution but I don't really know much about FreeSWITCH so I'm not sure if I can think of any solutions
