### ISSUE TITLE
Programmatically Execute Teal

### ISSUE THREAD

**Issue by tooolbox** [teal-language/tl#455]
I'm wondering if the Teal module has some easy way to programmatically transpile and/or execute Teal code.  Similar to how you can use `tl.loader()` and then when you `require("myteal")` it transpiles & loads the module.  I'm imagining something like `tl.exec("script.tl")` or `local luacode = tl.transpile("script.tl")`.

I'm trying to add first-class support for Teal in a Lua VM, i.e. for the scripts themselves and not just modules they might require, and just looking for the easiest way to go about this if I already have Teal require'd and available in the Lua VM.  Thanks.

Edit: To be clear, I know that `tl.exec` or `tl.transpile` do not exist.  I can look at the source and see `parse_program`, which seems like what I want.  I also can see the `tl` file and how it wraps `tl.lua`.  I'm more just hoping for some advice on the best route forward.

**Comment by tooolbox** [comment]
Alright, I copied most of the code from `tl_package_loader` and have it working initially.  Essentially a sequence of `parse_program()`, `type_check()`, `pretty_print_ast()`, and then `load()` and call the resulting chunk.

The one thing I'm a little uncertain about is `package_loader_env` and `init_env(lax)`.

1. I don't understand the ramifications of the environment or the lax setting--at a glance, it seems to affect whether calls into the stdlib are typechecked or not.
2. The lax setting seems to be based on if the running file is `.lua` or `.tl`.  In my case the Lua VM is persistent & Teal is loaded once on startup.  The VM may run Lua scripts that `require()` Teal modules, or run Teal scripts directly, and if it's a shared `package_loader_env` I'm uncertain about the best setting for `lax`.

**Comment by hishamhm** [comment]
@tooolbox I believe `tl.load` does what you want, it is similar to Lua's own `load()`. 

```
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> tl = require("tl")
> code = tl.load("local x: string = 'hello'; print(x)", nil, nil, _ENV)
> code()
hello
> 
```

An annoying bit right now is that it's not working unless you pass `_ENV` explicitly on Lua > 5.1; we need to fix that (but the fix will be backwards compatible).

**Comment by hishamhm** [comment]
I pushed the fix to `master`, so just `tl.load("local x: string = 'hello'; print(x)")` will work on all Lua versions.

**Comment by tooolbox** [comment]
Superb, thanks.  I'll give it a go shortly.
