### ISSUE TITLE
Failed to check record items in return type

### ISSUE THREAD

**Issue by fcr--** [teal-language/tl#456]
Somehow this is being accepted:
```
local record T
    m: string
end

function t1(): T
    return {m=42}
end
function t2(): T
    local x = {m=42}
    return x
end
```

even though this is correctly rejected:
```
local function f(_: T) end
f {m=42}
```
and so is this:
```
local t: T = {m=42}
```

**Comment by hishamhm** [comment]
@fcr-- Thank you for the report and test cases! I pushed a fix _and_ added a compiler warning that would warn about the bug I made!
