### ISSUE TITLE
unknown variable annotation: close

### ISSUE THREAD

**Issue by isRyven** [teal-language/tl#467]
Hello, do i understand it correctly that in current versions `0.13.2` you cannot use `close` variable annotation? Is there a work-around?

**Comment by FractalU** [comment]
There is already an issue for this problem.
(Lua 5.4) <const> and <close> attributes are not preserved #252

**Comment by isRyven** [comment]
Yes, but the mentioned issue is generic to `attributes` and suggest generic solution. This one specifically concerns the `close` attribute. Since as mentioned in the linked issue, in case you're targeting the older lua versions (`< 5.4`), it's not enough to just preserve the attributes when it comes to `close` or any other potentially new attribute. So the actual solution by itself would not be trivial. So i would say it makes sense to have issue for specific attribute, especially like this one.

**Comment by FractalU** [comment]
Well, I was pointing to the linked issue, because the maintainer was already thinking about it. However, I understand that the 'close' attribute is an issue on its own, because the solution for it is much harder than the one for the 'const' attribute.

**Comment by hishamhm** [comment]
@isRyven thanks for reporting! I think we can keep tracking this issue in #252, as suggested by @FractalU :+1:
