### ISSUE TITLE
AST parsing

### ISSUE THREAD

**Issue by tommitytom** [teal-language/tl#469]
I'm interested in parsing the teal AST and generating my own code with it.  I couldn't find any documentation on where to start with this, so was curious where a good starting point is, and if there are any examples of its usage I could take a look at

**Comment by hishamhm** [comment]
Hi! Unfortunately, the AST format is not documented because at this point it is not stable — it wasn't really designed to be reusable at this point, so I've been changing it whenever I felt it would help the code generation in tl.tl. What kind of code generation do you have in mind?

**Comment by tommitytom** [comment]
I'd like to use the AST to generate C structs that can be used at runtime by luajit.  I built a library a few years ago that does something similar at runtime (https://github.com/tommitytom/stronger) and I was curious if the same could be done using teal records.  Was also interested in converting records to a lua schema format (I use something similar in TypeScript that generates JSON schema).  I'll put this one on the back burner for now, thanks for the reply!

**Comment by mingodad** [comment]
Hello Tom !

Have you looked at https://github.com/edubart/nelua-lang they also have 
a kind of typed Lua and their parser emit an AST too.

Cheers !

**Comment by tommitytom** [comment]
Thanks for the heads up, I'll take a look :)
