### ISSUE TITLE
Out of source builds?

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#47]
I think it would be useful if the CLI supported some way to generate Lua scripts into a separate directory. For instance,
```
tl --outdir=build/ gen game/main.tl
```
...would generate
```
build/game/main.lua
```
That way, I would not have to pollute my source tree with .lua files. I could simply add the `build` directory to `.gitignore`.

**Comment by hishamhm** [comment]
+1 to this feature!

**Comment by euclidianAce** [comment]
@hishamhm i believe #177 closes this

**Comment by pdesaulniers** [comment]
Yep!
