### ISSUE TITLE
`is integer` should pull in compat53 when needed

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#472]
since it generates `math.type`

Additionally, it may be useful to discourage the use of `is integer` with a warning due to the possibly unexpected behavior between compat53 and Lua >=5.3

**Comment by hishamhm** [comment]
@euclidianAce Thanks for reporting! I pushed a fix.

> it may be useful to discourage the use of is integer with a warning due to the possibly unexpected behavior between compat53 and Lua >=5.3

Oh, you mean about it having different behavior regarding 64-bit precision? If that's the concern, then pretty much every operator (`+`, `-`...) is subject to that caveat.

I think all we can do regarding that is to keep the precision of the `integer` type under-specified in the language itself (just like `int` does not specify a precision in the C standard, unlike Java for example).

In the implementation, if you're using a 64-bit-capable backend such as Lua 5.3+, then you get 64-bit precision.

**Comment by euclidianAce** [comment]
> Oh, you mean about it having different behavior regarding 64-bit precision?

I was thinking more about the limitations of `compat53`'s version of `math.type`, Lua's will report if the number is represented as an int or float (disregarding the value), but [compat53 will basically report if the float is integral](https://github.com/keplerproject/lua-compat-5.3/wiki/math.type). So running something like `math.type(1.0)` gives different results on 5.3 (`float`) and up than with compat53 (`integer`)

**Comment by hishamhm** [comment]
>  compat53 will basically report if the float is integral

More than that, it reports if it's an integral _within range for integer math_, which I think is the useful definition for whether one wants to know if the number is `integer` or not.

> So running something like math.type(1.0) gives different results on 5.3 (float) and up than with compat53 (integer)

As I can see it, there are two reasons why one would care if `x` is float or integer: precision of calculation, or display representation.

Compat53 takes care of the former, so I think we're good on that regard within the boundaries of possibility (i.e. that different Lua backends have different precisions, and `is integer` is able to work with that).

As for the latter, `1.0` and `1` are indistiguishable in Lua < 5.3: `print(1.0)` prints `1`. And the position for the Lua team regarding display (which we inherit by default in Teal) is that the format of `print` is unspecified; if you want a specific display format one should use `string.format`, and in fact `string.format("%d", 1.0)` displays `1` in both Lua < 5.3 and >= 5.3, and `string.format("%.1f", 1)` displays `1.0` in both too.

So I think the current behavior is workable for these two use-cases. Did I miss some other case where the distiction matters?
