### ISSUE TITLE
Bug in tl.lua

### ISSUE THREAD

**Issue by yuriv** [teal-language/tl#483]
Hi,

You need to change 'load(...)' to 'loadstring(...)' int tl.lua:9443

Cheers

**Comment by ghsttwn** [comment]
There's no bug. Since 5.2, `load` is the replacement for `loadstring`. You may want to look at https://github.com/teal-language/tl/blob/master/tl.lua#L1, where there's a little version checking logic going on that will apply some shims based on the version you're running the module.

**Comment by hishamhm** [comment]
@ghsttwn is correct: @yuriv, to use the module in Lua 5.1 you should install https://github.com/keplerproject/lua-compat-5.3. When installing the `tl` rockspec using LuaRocks, it installs `compat53` as a dependency.
