### ISSUE TITLE
or operator not type-checking properly 

### ISSUE THREAD

**Issue by Mephistophiles** [teal-language/tl#487]
Current teal version (0.13.2) does not type check else branch on ternary operator (after `or` keyword).

How to reproduce:
```lua
local enum Test
	"one"
	"two"
end

local test_var: Test = true and "one" or "invalid" -- else branch have invalid value "invalid" of enum
```

**Comment by Kangaroux** [comment]
Just speculating, but if the condition is `true` it may just skip whatever the alternate is. Does it complain if you change `true` to `false`?

**Comment by hishamhm** [comment]
Fixed, finally! Thank you all for the reports and test cases!
