### ISSUE TITLE
Local function type generates unused local table

### ISSUE THREAD

**Issue by kikito** [teal-language/tl#489]
Given the following example:

```
local type MyFun = function(integer, integer): integer

local function execute(f: MyFun, x: integer, y: integer): integer
  return f(x, y)
end

local function sum(x:integer, y:integer): integer
  return x + y
end

execute(sum, 1, 2)
```

The generated Lua code replaces the `MyFun` local type with an empty local table declaration (note the first line):

```
local MyFun = {}

local function execute(f, x, y)
   return f(x, y)
end

local function sum(x, y)
   return x + y
end

execute(sum, 1, 2)
```

This variable is never used by the generated Lua code, and will make linters complain about it.

Expectation: local types should not generate Lua code at all, unless they are used by said Lua code.

**Comment by hishamhm** [comment]
@kikito This is now implemented! Local types that are never used in a concrete context are now elided from the generated code!
