### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by ryanford-frontend** [teal-language/tl#49]
Can some, at least basic, docs be made. The notation, the new types introduced etc. Interest is growing, and making those available will allow people to help you test and find/squash bugs.

**Comment by hishamhm** [comment]
Yes! Will definitely work on docs!

**Comment by fperrad** [comment]
At least the grammar, see for example [pallene](https://github.com/pallene-lang/pallene/blob/master/doc/manual.md#the-complete-syntax-of-pallene)

**Comment by hishamhm** [comment]
@fperrad yes, definitely! :) I'm well aware of that page, I was involved in starting it before the Titan fork ;)

**Comment by hishamhm** [comment]
@ryanford-frontend @fperrad @pdesaulniers @mwild1 @kipras please take a look at this PR! https://github.com/hishamhm/tl/pull/57

**Comment by ryanford-frontend** [comment]
Looks good to me. Appreciate the effort, I can only imagine what all that phone typing did to your eyes and fingers :grimacing:

**Comment by hishamhm** [comment]
@ryanford-frontend Thank you! #57 is now merged as-is, so at least the "_creating_" part is done, even if not super complete, so I'll close this issue! Feel free to open more! (I'll open one for the grammar)

**Comment by hishamhm** [comment]
Oops, forgot to close this! Documentation is an endless ongoing effort, but basic docs are here, including the grammar!
