### ISSUE TITLE
Type checking should work with tl.load() or something else.

### ISSUE THREAD

**Issue by nagolove** [teal-language/tl#491]
Hi. I use Teal for my projects for a some time. And in one of projects I build pieces of Lua code from strings to functions. I tried to use `tl.load()` but it does not take checking. I would to have some technique to do type checking through `tl.load()` call or other functions. I think it should return string with valid Lua code without type annotations. Maybe it is rare use case by I got it. Temporary files is not usable because of efficency issue.

**Comment by hishamhm** [comment]
Fixed via 16761188d64a14b9a31c09ff18d6ff7b8715d4cf! You can now request type checking using the `c` modifier in `tl.load` (see commit msg and tests for details!)

**Comment by nagolove** [comment]
Thanks for fix!
