### ISSUE TITLE
debug.getinfo doesn't contain full source

### ISSUE THREAD

**Issue by jadawil** [teal-language/tl#508]
Seems like teal is breaking something in debug getinfo

**Example**
file1.lua
```
return {
   get_src = function() return debug.getinfo( 2, "S" ).source end
}
```
file2.lua
```
print( file1.get_src() )
```

**Outputs**
With Teal -> file2
Without Teal -> @./src/file2.lua

If file2.lua called debug.getinfo( 1, "S" ).source with teal it gets the correct full path.

**Environment**
Teal: 0.13.2
Lua: tarantool 2.8.2

**Comment by jadawil** [comment]
Yep sorry, fixed.

The issue is when the teal loader is included so something like this:

```
-- main.lua  
local tl = require("tl") 
tl.loader()
local file1 = require("file1")
print( file1.get_src() )
```

`luajit main.lua`

The issue looks to be because this loader uses "loadstring" to load the files, which doesn't work well with the debug lib https://www.lua.org/pil/23.1.html

**Comment by hishamhm** [comment]
@jadawil Ahh, that makes sense, thank you! I'm actually using `load` in the loader, and I was just passing the module name as the chunkname. It's an easy change to pass it `"@" .. filename` instead to make it behave like the "native" loading of Lua modules by require!
