### ISSUE TITLE
Error in Playground

### ISSUE THREAD

**Issue by tooolbox** [teal-language/tl#524]
Playground currently seems nonfunctional:

https://teal-playground.netlify.app/?c=bG9jYWwgbWVzc2FnZTpzdHJpbmcgPSAiaGVsbG8gd29ybGQhIg%3D%3D

```
Playground.vue:142 ...raw.githubusercontent.com/teal-language/tl/master/tl.lua:218: TL_DEBUG was defined, but not a number
```

Chrome 102 on Windows.

**Comment by hishamhm** [comment]
Thanks for the report! Fixed by https://github.com/teal-language/teal-playground/pull/36
