### ISSUE TITLE
Compiler crashes with "attempt to index a nil value (local 't')"

### ISSUE THREAD

**Issue by Voycawojka** [teal-language/tl#526]
# To reproduce

Save the following code to either a `.tl` or `.lua` file:

```lua
Entity = {}

function Entity.action()
end
```

and run `tl check` on it. I would expect a complaint about `Entity` not being declared. Instead, the following popup appears (I'm including a screenshot since I can't select the message to copy it):

![image](https://user-images.githubusercontent.com/26658923/173878979-7b4d3a45-9a96-4f0d-8a2e-798b874a2a05.png)

# Environment

- OS: Windows 10
- Teal: 0.13.2+dev (the latest package downloaded from github releases)

**Comment by hishamhm** [comment]
That's very strange! I cannot reproduce it locally. We got a similar report in #535 on macOS as well...

**Comment by hishamhm** [comment]
On further investigation, this does look like #470, which was already fixed (I _can_ reproduce your error with 0.13.2, but not with master which contains the fix from #470). The report from #535, however, said it even happened on _any_ code, and that I cannot reproduce.

**Comment by hishamhm** [comment]
This should be fixed in 0.14. I'm going to close this; feel free to reopen if the problem reappears!
