### ISSUE TITLE
Teal does not seem to support `__index`

### ISSUE THREAD

**Issue by makspll** [teal-language/tl#541]
Having a custom __index metamethod:
```lua
 metamethod __index: function(LuaVec<T>,integer):(ReflectedValue)
```
does not allow me to index my type with integers,

is this intended? It's very much annoying to work around

**Comment by hishamhm** [comment]
> is this intended?

No, it's just not implemented! Patches are definitely welcome!

**Comment by hishamhm** [comment]
I just committed some initial support! For now, only functions as `__index` are handled and it only resolves `__index` when using `t[x]` (not with `t.k` or `t:k`). But it should address these "vector-like" use-cases already.

**Comment by makspll** [comment]
that's perfect, thank you!
