### ISSUE TITLE
A potential bug with variable shadowing?

### ISSUE THREAD

**Issue by Calandiel** [teal-language/tl#545]
```
global function test()
    local boo: string = "1"

    global boo: number = 1
end

test()
print(boo)
```
The above translates to this:
```
function test()
   local boo = "1"

   boo = 1
end

test()
print(boo)
```
I think taking teal code at a glance, you'd expect the print to output 1, but the lua version will of course output nil instead.

**Comment by hishamhm** [comment]
Ah, good catch! I think the way to go to fix this is to disallow creating a global in a scope where there is already a local with the same name, thus guaranteeing that valid Teal code matches the Lua semantics for that.
