### ISSUE TITLE
module 'compat53.module' not found on Lua 5.3

### ISSUE THREAD

**Issue by Zash** [teal-language/tl#56]
I've got a machine where `/usr/bin/lua` is Lua 5.3.

```
tl$ readlink -f $( which lua )
/usr/bin/lua5.3
tl$ lua -v
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
tl$ ./tl
lua: .//tl.lua:1: module 'compat53.module' not found:
	no field package.preload['compat53.module']
	no file './/compat53/module.lua'
...etc
```

Running `busted` produces **a lot** of errors because there's no `compat53` module, which makes sense since it's not needed on 5.3.

**Comment by hishamhm** [comment]
Noted. I can make it smarter to not need it when running on top of 5.3 but
for now you can install compat53 to silence these errors with no problems:
it is a noop module when running with 5.3. I'm using it to make tl produce
the same behavior over different Lua versions.
