### ISSUE TITLE
Request: Add Teal support to ZeroBraneStudio

### ISSUE THREAD

**Issue by qEagleStrikerp** [teal-language/tl#571]
At the moment, it's close to impossible if you want to run Teal on ZeroBraneStudio. The only package manager available is LuaDist which currently does not support Teal. And getting a Luarocks installed package to be loaded natively into ZeroBraneStudio is tedious to say the least (still haven't gotten it to work). It would be awesome if you could either add Teal support to LuaDist or write a plugin that can be used with ZeroBraneStudio (like the Moonscript one).

**Comment by hishamhm** [comment]
@qEagleStrikerp thank you for the suggestion, but this should be a feature request in the ZeroBraneStudio repo, not Teal's :)
