### ISSUE TITLE
Redefining the standard library

### ISSUE THREAD

**Issue by uramer** [teal-language/tl#590]
In my context, the `debug` library is not available, and some methods of other standard libraries aren't either.

I would expect to be able to redefine it by having `global debug: nil` etc in my declaration files, but I get errors such as 
```global was previously declared as <const>: debug```

Is there an intended way to do this?

**Comment by uramer** [comment]
Here it's mentioned that it's possible: https://github.com/teal-language/tl/issues/532#issuecomment-1179307978
> For the time being, unfortunately if you really need to use a customized definition of standard library tables, you'll have to redefine the whole thing.

But not how

**Comment by hishamhm** [comment]
@uramer That last statement was incorrect, sorry. I fixed that comment and I'm closing this issue as a duplicate, while keeping the other one open for tracking the feature request.
