### ISSUE TITLE
Cannot create internal_compiler_output as a hidden directory

### ISSUE THREAD

**Issue by B4mbus** [teal-language/tl#603]
Here is my `tlconfig.lua`:
```lua
return {
  gen_target = '5.1',
  gen_compat = 'off',
  global_env_def = 'types',
  include_dir = {
    'types', 'teal',
  },
  source_dir = 'teal',
  build_dir = 'lua',
  build_file_output_dir = 'lua',
  internal_compiler_output = '.teal_tmp'
}
```
Whenever I run `tl build` it creates `teal_tmp/` instead of `.teal_tmp/`. Tried to escape it, but then it created `\\.teal_tmp/`

**Comment by hishamhm** [comment]
`tl build` is deprecated — please use [Cyan](https://github.com/teal-language/cyan), it is a more powerful build tool, which supports incremental builds and also a more general system of [build-time scripts](https://github.com/teal-language/cyan/blob/main/docs/tlconfig.md#scripts).
