### ISSUE TITLE
assertion failed in upvalue get_typenum

### ISSUE THREAD

**Issue by eigenbom** [teal-language/tl#611]
I was experimenting with tl and the vscode plugin, i began to type `local type vec3 = ` and upon entering another character (e.g., "r") the tl compiler crashed with the following assert:

![image](https://user-images.githubusercontent.com/1103761/211187915-1c8a216f-5e30-4ff8-af20-c3748635b3df.png)

**Comment by hishamhm** [comment]
@eigenbom Thank you for reporting! This will be fixed by #612!

**Comment by eigenbom** [comment]
Thx Hisham :)
