### ISSUE TITLE
tl compiler crashes sometimes when using nested records

### ISSUE THREAD

**Issue by svermeulen** [teal-language/tl#615]
I tried updating to 0.15.0 today and found that the tl compiler crashes in some cases with my code base.  I was able to narrow one of the crashes down to the following file:

```
local record Bar
   record Qux
      foo:function(Qux)
   end
end

function Bar.Qux:foo()
   print("todo")
end
```
If I run `tl gen bar.tl` on the above file I get errors with form:
```
tl.lua:6202: attempt to index local 't' (a nil value)
stack traceback:
        tl.lua:6202: in function 'drop_constant_value'
        tl.lua:6267: in function 'add_var'
        tl.lua:9536: in function 'bs'
        tl.lua:3362: in function 'extra_callback'
```

**Comment by hishamhm** [comment]
@svermeulen Thanks for the report! It's now fixed in `master`.

**Comment by svermeulen** [comment]
Thanks.  Can confirm it is fixed now!
