### ISSUE TITLE
Can I declare a global that isn't require()-able?

### ISSUE THREAD

**Issue by xurion** [teal-language/tl#626]
I have a Lua script that is run in the context of another parent that I don't control. The parent process provides a number of global functions that my script can use, but does not need to reference via a require. I have declared these global functions in a separate `parent.tl` file which I then require in my script:

```lua
-- parent.tl
global type parent = record
  foo: function(): nil
  bar: function(): nil
  -- more funcs...
end

-- script.tl
require("parent")

parent.foo()
parent.bar()
```

The issue I'm facing is the generated Lua then contains a require() that will fail, because the parent does not expose this as a require()-able file in the live system. I considered combining the global parent function declarations with my script, but there are a _lot_ so this becomes disorganised very quickly.

I'm pretty new to Teal so I'm not sure if this is a feature request or just something I'm not sure how to achieve.

Thanks!

**Comment by virusdefender** [comment]
https://github.com/teal-language/tl/blob/e4639a40a414ce670b06ff724335b689ad4a4177/docs/declaration_files.md?plain=1#L58

you need `--global-env-def`
