### ISSUE TITLE
Metamethod type not checked in metatable definition

### ISSUE THREAD

**Issue by bjornbm** [teal-language/tl#633]
Hi, is the below code supposed to pass the typechecker? (The type of `__add` in `rec_mt` does not have the correct type for `metamethod __add` in `Rec`.)

```lua
local type Rec = record
   metamethod __add: function(Rec, Rec): Rec
end

local rec_mt: metatable<Rec>
rec_mt = {
   __add = function(_a: Rec, _b: number): number  -- Type error??
      return 1
   end,
}

local r: Rec = setmetatable({ }, rec_mt)
print(r + r)      -- prints 1
```

What about this one? (`__add` is not defined in `rec_mt`)

```lua
local type Rec = record
   metamethod __add: function(Rec, Rec): Rec
end

local rec_mt: metatable<Rec> = {}  -- __add is not defined

local r: Rec = setmetatable({ }, rec_mt)
```

**Comment by hishamhm** [comment]
The second case (__add is not defined in rec_mt) is unlikely to be supported soon (the compiler currently does not do nil checks in general), but the first one sounds like it should have been checked — (note to self: this may require some adding custom code for checking `setmetatable` arguments).

**Comment by bjornbm** [comment]
OK, so my understanding for the second case: the `record` definition defines what keys/values are valid, but not that they are defined (or more generally perhaps the values may be nil, since nil is a valid value of every type). What is checked is that values for the defined keys have the right type, and that no other keys are added to the record.

**Comment by bjornbm** [comment]
For the first case, I guess the safest place to check is at `setmetatable`.

    local r: Rec = setmetatable({ }, rec_mt)

I assume the inferred type of `{ }` here is `Rec`, thanks to the assignment to `r: Rec`? And thus `rec_mt` must be `metatable<Rec>`, which in turn should satisfy the `metamethod`s of `Rec`?

You could (should?) also check at the assignment to `rec_mt` that it satisfies the `metamethod`s of `Rec`, since `rec_mt` is declared as a `metatable<Rec>`.

Currently it seems the `metatable<Rec>` type does nothing at all:

1.  The contents of `rec_mt` are not checked versus `Rec`s metamethods.
2.  `setmetatable` does not check that `rec_mt` is a `metatable<Rec>` (it will accept any table, including of type `metatable<SomeOtherType>`).

**Comment by svermeulen** [comment]
I keep getting a similar problem:

    local record Foo
       metamethod __add: function(Foo, Foo): Foo
    end

    local record Bar
    end

    local foo:Foo
    local bar:Bar

    -- Teal allows this
    local result:any = foo + bar

    print(result)

This only results in runtime errors but would be great if it was a compiler error instead.  I would expect the add method to not be allowed since Foo explicitly requires Foo type for it

**Comment by hishamhm** [comment]
@svermeulen This looks like a different issue. Could you open a separate ticket? Thanks!!

**Comment by svermeulen** [comment]
@hishamhm I upgraded from 0.15.2+dev to 0.15.3+dev and it is now being detected properly.   Thank you!

**Comment by hishamhm** [comment]
@bjornbm This (at least the first case) is now fixed in the `next` branch — please see the commit message in [fcdd861](https://github.com/teal-language/tl/commit/fcdd86156b8e377b83e3e6f72ade3d784faa0648)

There are still some quirks (e.g. you can declare a metamethod in the table that wasn't declared explicitly in the record, as long as it matches the general `metatable` contract; those behave as "default" metamethod signatures), but overall the checking of things that are explicitly declared is a lot more robust!

I'm going to close this issue since this is the extent that can be fixed without adding `nil` strictness (and once that happens, then this should be essentially fixed in tandem).
