### ISSUE TITLE
Teal cannot load valid Lua modules

### ISSUE THREAD

**Issue by catwell** [teal-language/tl#634]
I got this error while trying to use Lapis with Teal.

Lapis has a submodule that looks like [this](https://github.com/leafo/lapis/blob/9208d1c440a23398efc32f9dd09c6a80f836313c/lapis/db/postgres/model.lua#L224), and so it hits [this](https://github.com/teal-language/tl/blob/45d4c6ea730842677482efa19c32f0efb82fba00/tl.tl#L1474).

Maybe this means we should have a "lax" mode for the parser as well? Lapis keywords should not interfere with Lua code.

**Comment by hishamhm** [comment]
no, that's a bug. That "syntax is no longer valid" check should have been only inside `record` definitions, not inside table literals.

**Comment by hishamhm** [comment]
I improved the checks for soft keywords, it no longer syntax-errors on the example above.
