### ISSUE TITLE
Feature Request: tl compiler option to print to console instead of to file

### ISSUE THREAD

**Issue by SlashScreen** [teal-language/tl#636]
The Moonscript compile has an option to print the compiled code to the console output instead of an output file. Could Teal have this as well? If you're busy, I can add it myself, but the tl.tl file is so big I don't know where to add the code myself.

**Comment by lenscas** [comment]
How should `tl` act if it needs to compile multiple files when this mode is used?

Anyway, depending on your exact needs, `tl.gen()` produces everything you need in order to print the code.

I work with `tl.gen()` in my project to put compiled code into an example, you can see how I do it at https://github.com/lenscas/tealr_doc_gen/blob/f9ce06346b0e97a836d36b86f908e5b7bb229953/base_template.etlua#L137

**Comment by SlashScreen** [comment]
Moonscript just prints them one after the other.
My use case is a bit niche- I'm capturing the console output to save to an asset in an asset importer for Unity. A bit weird and janky, and possibly inadvisable, but it does it automatically.

**Comment by hishamhm** [comment]
Do you need to do multiple files from a single invocation? If you can do a file at a time, on Linux you can do `tl gen myfile.tl -q -o /dev/stdout`

Otherwise, I'd avise writing a script using the tl API as suggested by @lenscas.

**Comment by SlashScreen** [comment]
I see, alright. You mean like, write a lua script that requires tl.lua, and call tl.gen() and pass in a string?

**Comment by hishamhm** [comment]
@SlashScreen yes!

**Comment by SlashScreen** [comment]
As I'm doing this, I have discovered that in the record tl, it describes gen as returning only a string, but the function itself returns a string and a Result type, meaning that when I print tl.gen(), it gives me what I want, as well as appending a table next to it. When I try deconstructing the tuple, it tells me that the function only returns one value. Am I missing something?

**Comment by hishamhm** [comment]
@SlashScreen that's a mistake in the record definition! Just fixed it in `master`, thanks for the heads up!

**Comment by SlashScreen** [comment]
Question: what do I need to do to remove all external dependencies? i don't need any file utility, and there's a lot of compat53. 
I realized since I can call the script i can just ask moonsharp to run tl.gen and get the string directly. However, it needs some dependencies I don't think i can fit within the confines of moonsharp, so I'm figuring out how to strip it of as much as I can so that it doesnt Require anything, but gen still functions.

**Comment by lenscas** [comment]
there should be a compiler option that disables compat5.3. I think those requires are also optional but not sure

**Comment by SlashScreen** [comment]
unfortunately Moonsharp is based on lua 5.2

**Comment by hishamhm** [comment]
`tl --gen-compat off gen tl.tl` should be able to generate a `tl.lua` module that can run `tl.gen` without compat53. I think that should work with Lua 5.2 as well!

**Comment by hishamhm** [comment]
(Also, you don't necessarily need to use the same Lua version in your tl generator script as in your application -- you could use `tl run` to run your generator script from the CLI.)

**Comment by SlashScreen** [comment]
Okay, got it! It was a combination of errors on my end and the compat53 issue. The Unity asset importer is complete, along with my script that takes a C# assembly and generates a .d.tl from all the classes you want exposed though Moonsharp. Would anyone be interested in me releasing it?

**Comment by lenscas** [comment]
being able to generate .d.tl files based on C# sounds useful. Did something similar for Rust (but also added a good bit more to that)

**Comment by hishamhm** [comment]
@SlashScreen Glad you were able to solve your problem via this other route! I'll close this issue since I don't plan to implement it directly in `tl`.
