### ISSUE TITLE
Redefine `assert` with the `global` modifier make the compiler crash

### ISSUE THREAD

**Issue by Aire-One** [teal-language/tl#653]
Hello,

Following discussions from the chat, here is a bug report with a minimal reproducible example. (I have tested the issue against the new tl 0.15.2-1 version)

According to my understanding, the crash is caused by redefining a variable from the standard library (`assert` in this case) with the  `global` modifier. If I change the line to `local assert = asserts`, I "only" get a compiler warning `redeclaration of variable 'assert'`.

```
-- Use a local record with a different name to prevent a tl warning
-- https://github.com/teal-language/teal-types/blob/master/types/luassert/luassert/assert.d.tl#L42
local record asserts
   equals: function(any, any, string): any, any, string
end

global assert = asserts -- This line

local a = 1
local b = "1"
asserts.equals(a, b)
```

```
$ tl check init.tl 
/usr/bin/lua5.4: /usr/share/lua/5.4/tl.lua:7729: attempt to concatenate a nil value (field 'attribute')
stack traceback:
        /usr/share/lua/5.4/tl.lua:7729: in upvalue 'add_global'
        /usr/share/lua/5.4/tl.lua:9050: in local 'cbkind_after'
        /usr/share/lua/5.4/tl.lua:3610: in upvalue 'recurse'
        /usr/share/lua/5.4/tl.lua:3418: in local 'fn'
        /usr/share/lua/5.4/tl.lua:3602: in function </usr/share/lua/5.4/tl.lua:3580>
        (...tail calls...)
        /usr/share/lua/5.4/tl.lua:10310: in function 'tl.type_check'
        /usr/share/lua/5.4/tl.lua:10716: in function 'tl.process_string'
        (...tail calls...)
        /usr/lib/luarocks/rocks-5.4/tl/0.15.2-1/bin/tl:1181: in field '?'
        /usr/lib/luarocks/rocks-5.4/tl/0.15.2-1/bin/tl:1410: in main chunk
        [C]: in ?
```

https://teal-playground.netlify.app/?c=LS0gVXNlIGEgbG9jYWwgcmVjb3JkIHdpdGggYSBkaWZmZXJlbnQgbmFtZSB0byBwcmV2ZW50IGEgdGwgd2FybmluZwotLSBodHRwczovL2dpdGh1Yi5jb20vdGVhbC1sYW5ndWFnZS90ZWFsLXR5cGVzL2Jsb2IvbWFzdGVyL3R5cGVzL2x1YXNzZXJ0L2x1YXNzZXJ0L2Fzc2VydC5kLnRsI0w0Mgpsb2NhbCByZWNvcmQgYXNzZXJ0cwogICBlcXVhbHM6IGZ1bmN0aW9uKGFueSwgYW55LCBzdHJpbmcpOiBhbnksIGFueSwgc3RyaW5nCmVuZAoKZ2xvYmFsIGFzc2VydCA9IGFzc2VydHMgLS0gVGhpcyBsaW5lCgpsb2NhbCBhID0gMQpsb2NhbCBiID0gIjEiCmFzc2VydHMuZXF1YWxzKGEsIGIp

**Comment by hishamhm** [comment]
@Aire-One Thanks for the repro! I've just pushed a fix.

**Comment by Aire-One** [comment]
Thank you for the fix @hishamhm. I can confirm the crash no longer happens on the development version.
