### ISSUE TITLE
place for external modules definitions

### ISSUE THREAD

**Issue by ildar** [teal-language/tl#66]
cont. https://github.com/hishamhm/tl/issues/28
As def-files are supported, we need a definite place for external modules definitions. It must be expanded by community. The following options come to my mind:
1. separate git repo
2. upsteam (module's) repos

Hisham, maybe alternative ideas?

**Comment by hishamhm** [comment]
Agreed!

I think both options can work: having a community git repo for collecting various modules definitions files in the style of https://github.com/DefinitelyTyped/DefinitelyTyped/ would be greatly beneficial — and a lot easier than convincing upstreams to carry definition files! — but that also doesn't prevent upstream projects from hosting `.d.tl` files themselves if they want to.

So yeah, I definitely give my thumbs-up to a community definitions project maintained in a separate repo.

**Comment by pdesaulniers** [comment]
Perhaps it would make sense to create a "tl" organization on GitHub and add the community repo there.

**Comment by ildar** [comment]
We're still lacking a name )))

**Comment by hishamhm** [comment]
on the name topic, I've been thinking TyLua lately: it's descriptive, seems unique enough, keeps the "tl" theme and it's shorter than Typed Lua

**Comment by resolritter** [comment]
@hishamhm "Teal" as suggested in https://github.com/hishamhm/tl/issues/25#issuecomment-557899649 is easy to type and sounds cool : - )

**Comment by pdesaulniers** [comment]
+1 for Teal, I think it's a pretty good name. 

Not sure about TyLua. Since "Ty" is not really a word, I'd be tempted to pronounce it "Tee-why". Also, there are a couple of homonyms that sound like "Ty" (Tie Lua? :stuck_out_tongue: ), so people might not guess the spelling just by hearing the name.

**Comment by hishamhm** [comment]
Now that we have a name, I guess we can get this started?

TypeScripts calls it [https://github.com/DefinitelyTyped/DefinitelyTyped/](DefinitelyTyped), Python calls it [https://github.com/python/typeshed/](typeshed)...

I'm thinking https://github.com/teal-language/teal-types — how does that sound?

**Comment by pdesaulniers** [comment]
Sounds good to me!

**Comment by xch91** [comment]
Thank you for the effort for this awesome project!

Random 2 cents from my brain: How about **tyle** :rofl: 

As it shows the project's effort to provide good standardized, pre-sliced type references; it might be a bit short though

**Comment by pdesaulniers** [comment]
@hishamhm I believe this issue can be closed now?

**Comment by hishamhm** [comment]
Yes!
