### ISSUE TITLE
Custom type checking for custom types

### ISSUE THREAD

**Issue by OrfeasZ** [teal-language/tl#661]
Is it possible to make teal generate custom type checking code when using the `is` operator instead of checking using `type()`?

For example, in my lua implementation, all custom types have an `Is` method which can be used to determine their type if needed, like this:

```lua
if x:Is('SomeType') then
  -- Do something with x
end
```

Is there a way (eg. using some annotation) to make it so the following teal code gets transpiled to the code above, when `x` is declared as some record userdata type?

```lua
if x is SomeType then
  -- Do something with x
end

**Comment by hishamhm** [comment]
@OrfeasZ not yet, but this is something I want to implement. Something along these lines should come with the interfaces implementation, which should cover this, as well as #655 (and possibly other related feature requests).

**Comment by hishamhm** [comment]
This is now implemented! Teal '24 lets you write

```lua
local interface MyObjectType
   Is: function(self, string): boolean
end

local record SomeType is MyObjectType where self:Is("SomeType")

end

local x: SomeType

if x is SomeType then
end
```

and this generates the following Lua:

```lua
local x

if x:Is("SomeType") then
end
```
