### ISSUE TITLE
`...` is not populated when `tl run` loads a Lua module

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#689]
```
$ cat ld.lua 
require'foo'
print('Done')
$ cat foo.lua 
print(...)
$ lua ld.lua 
foo	./foo.lua
Done
$ ./tl run ld.lua 

Done
```

**Comment by hishamhm** [comment]
@fperrad Is this behavior documented? I tried to find it in the Lua manual but I must have missed it. I am in favor of implementing, but ideally I would like to follow the documentation to ensure I got the behavior right.
