### ISSUE TITLE
Required parameters not checked.

### ISSUE THREAD

**Issue by jordan4ibanez** [teal-language/tl#719]
I do not know if this is intentional behavior, but when I do the following:
```lua
local x1: number = 5

local function blah(x: number, y: number): number
  return x + y
end

-- Should have an error here.
blah(x1)
```

It will just run as normal but then error out as there is no y argument given.

**Comment by lenscas** [comment]
See #71 and #598

**Comment by hishamhm** [comment]
Closed as duplicate
