### ISSUE TITLE
Global functions cause a syntax error

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#72]
I suppose this syntax should work?

```lua
global function x()

end
```
Right now, I get the following error:
```
expected a local variable definition
```

**Comment by pdesaulniers** [comment]
Nevermind, I spoke too fast. This syntax is fine:
```lua
function x()

end
```

**Comment by pdesaulniers** [comment]
Wait, no, let's reopen this :stuck_out_tongue:

To avoid creating globals by accident, I think the `global` keyword should be explicit. 

Therefore, this example should work:
```lua
global function x()

end
```

and this example should throw an error (unless 'x' is already declared elsewhere):
```lua
function x()

end
```

**Comment by hishamhm** [comment]
I'm a bit reluctant about making `function x() ... end` invalid... but at the very least it could be made into a "warning".

I have thought about `global function x() ... end` and I have mixed feelings: on one hand, it adds a redundant form (if bare `function x()` remains valid); on the other hand, it looks consistent with `local` forms and the `global x = v` form.

I still need to give this more thought, but I'm inclined to go with something like your proposal in `.tl` files and continue to accept bare `function x()` as a global declaration in plain `.lua` files...

**Comment by ildar** [comment]
If it's about leading TL away from Lua (maybe intending to "fix" Lua's
"flaws") I think you shouldn't.
Lua itself is developing. Roberto doesn't enter `global` keyword and such...

I'd prefer TL staying as close to Lua as it can be while adding things
related to types.

**Comment by pdesaulniers** [comment]
I'm certainly biased against this "flaw". `function x() ... end` without the `local` keyword is a mistake on my part pretty much 100% of the time.

Normally, I would use `luacheck` to avoid this mistake, but I can't use it on .tl files :/

In any case, I see `function x() ... end` as syntax sugar for `x = function() ... end`, which would currently not work without using the `global` keyword. So, I think `global function x()` would be more intuitive.

**Comment by hishamhm** [comment]
> Lua itself is developing. Roberto doesn't enter `global` keyword and such...

tl already has `global`: we need it to declare global variables in order to type them. The question is whether we allow its use in function declarations as well for consistency.

> Normally, I would use luacheck to avoid this mistake, but I can't use it on .tl files :/

If we add support for `global function` as a syntax, I still think disallowing bare `function() ... end` syntax for global functions might be a bit drastic at this stage, but I could see the compiler getting a `-w` option for adding warnings for the kinds of things that luacheck checks for (unused variables, etc.)
