### ISSUE TITLE
Variadic fuction error about argument count

### ISSUE THREAD

**Issue by atticus-sullivan** [teal-language/tl#727]
I have a variadic `function foo(...: string): string` which performs some sort of reduce on its argument by calling `foo("literal", select(2, ...))`. Now `tl check` gives me the following error `wrong number of arguments (given 2, expects 1)` on this call of `foo`.

Currently I'm collecting the arguments in a table so I can use `table.unpack` in the function argument when calling `foo`. But of course this additional table construction is actually unneeded. Also if I do this call outside of function `foo`, there is no error.

[Here's the playground wit that code](https://teal-playground.netlify.app/?c=bG9jYWwgbWVzc2FnZTpzdHJpbmcgPSAiaGVsbG8gd29ybGQhIgoKbG9jYWwgZnVuY3Rpb24gZm9vKC4uLjogc3RyaW5nKTogc3RyaW5nCiAgICBsb2NhbCBuID0gc2VsZWN0KCIjIiwgLi4uKQogICAgaWYgbiA8IDMgdGhlbgogICAgICAgIHJldHVybiAiIgogICAgZW5kCiAgICBpZiBtZXNzYWdlIH49ICJoZWxsbyB3b3JsZCIgdGhlbgogICAgICAgIHJldHVybiBmb28oImhpIHRoZXJlIiwgc2VsZWN0KDIsIC4uLikpCiAgICBlbHNlCiAgICAgICAgbG9jYWwgciA9IHsiaGkgdGhlcmUiLCBzZWxlY3QoMiwgLi4uKX0KICAgICAgICByZXR1cm4gZm9vKHRhYmxlLnVucGFjayhyKSkKICAgIGVuZAplbmQKCmxvY2FsIGZ1bmN0aW9uIGJhciguLi46IHN0cmluZyk6IHN0cmluZwogICAgcmV0dXJuIGZvbygiaGkgdGhlcmUiLCBzZWxlY3QoMiwgLi4uKSkKZW5k)

I hope this information are enough to reproduce and understand the problem.

**Comment by hishamhm** [comment]
@atticus-sullivan Thank you! It is now fixed in `master`!

**Comment by atticus-sullivan** [comment]
Works now. Thanks for fixing. And also thanks for your work/project in general :+1:.

**Comment by hishamhm** [comment]
Thank you for the feedback! :grin:
