### ISSUE TITLE
Can a variable be assigned to it's type?

### ISSUE THREAD

**Issue by Andre-LA** [teal-language/tl#739]
(note: I'm testing the `next`, but Teal Playground doesn't accuse an error either)

While trying interfaces, I found by accident that this code is accepted:

```lua
local record Foo
   x: integer
end

local x: Foo = Foo

print(Foo, x)

-- tl run test.tl 
-- table: 0x558977bee240	table: 0x558977bee240
```

**Comment by Frityet** [comment]
if you use a record like that, it gets turned into a table, you can check it out by doing `tl gen test.tl`

**Comment by hishamhm** [comment]
Yes, this is on purpose, because of record definitions being used as table prototypes (e.g. `function MyRecord:my_method`, `MyRecord.my_static_field`, etc.)
