### ISSUE TITLE
Lua's grammar vs Teal's cast

### ISSUE THREAD

**Issue by fperrad** [teal-language/tl#740]
This Lua code fails, but it is not an issue because the extra parentheses are useless

```lua
(io.stdout):write('one\n')
(io.stdout):write('two\n')  -- attempt to call a FILE* value
```

```lua
io.stdout:write('one\n')
io.stdout:write('two\n')  -- OK
```

Now, with Teal, this kind of parentheses is used by cast (and could become widely used)
```lua
local record Obj
   meth1: function(self: Obj)
end

local t = {}
do
   (t as Obj):meth1()
   (t as Obj):meth1()  -- not a function: nil
end
```

The generated Lua looks like:
```lua




local t = {}
do
   (t):meth1()(
   t):meth1()
end
```

**Comment by hishamhm** [comment]
Not sure what we can do about this. It's a known gotcha for Lua...

Filed this one under the "semantics" label because it's the one we use for "surprising behaviors",  but it really should be under "syntax" :)
