### ISSUE TITLE
No errors reported when assigning value directly to a record table

### ISSUE THREAD

**Issue by svermeulen** [teal-language/tl#752]
I am using version 0.15.3+dev.  Example:

    local record Foo
       qux: integer
    end

    local record Bar
       gorp: number
    end

    -- This correctly reports error "in local declaration: _bar: got number, expected Bar"
    -- local _bar:Bar = 0.0

    -- This does not report an error
    local _bar:Bar = Foo

**Comment by hishamhm** [comment]
This is fixed in the `next` branch! (meaning it will be included in the next release)
