### ISSUE TITLE
Type alias for nested generic crashes compiler

### ISSUE THREAD

**Issue by Zipperdoodle** [teal-language/tl#754]
Hi, I reduced the issue down to the following.

This works:
```lua
local record MyGenericRecord<T>
    Data: T
end

local enum MyEnum
    "foo"
    "bar"
end

local type MyAlias = MyGenericRecord<MyEnum>
```

But this doesn't:
```lua
local record MyNamespace
    record MyGenericRecord<T>
        Data: T
    end
end

local enum MyEnum
    "foo"
    "bar"
end

local type MyAlias = MyNamespace.MyGenericRecord<MyEnum>
```

The latter version crashes the compiler with the following runtime error:
`tl.lua:4273: bad argument #1 to 'concat' (table expected, got nil)`

Here is the relevant code section in tl.lua:
```lua
["newtype"] = {
         after = function(node, _children)
            local out = { y = node.y, h = 0 }
            if node.is_alias then
               table.insert(out, table.concat(node.newtype.def.names, "."))
            elseif is_record_type(node.newtype.def) then
               table.insert(out, print_record_def(node.newtype.def))
            else
               table.insert(out, "{}")
            end
            return out
         end,
```

**Comment by Zipperdoodle** [comment]
Never mind. Aliasing is broken anyway. Even if I don't use nested types, I can't alias a generic into a specific type and have the type checker accept it as an alias. It just sees it as a altogether different type.

This also means that coding with generics becomes very unwieldy very quickly. Because you have to type out the whole mess all the time. Makes it very tempting to slap on some kind of macro preprocessor that does simple substitution, as that would be better than this.

**Comment by hishamhm** [comment]
@Zipperdoodle This is now fixed in the `next` branch! I added your test case as a regression test to the testsuite. Thanks for the report!

**Comment by hishamhm** [comment]
> Not sure what the philosophy is around type aliasing in Teal in any case.

I tried my hand at drafting some documentation about this. Let me know what you think!

https://gist.github.com/hishamhm/396c6dc9015813670d013ba0a4b5ab2a

**Comment by Zipperdoodle** [comment]
> > Not sure what the philosophy is around type aliasing in Teal in any case.
> 
> I tried my hand at drafting some documentation about this. Let me know what you think!
> 
> https://gist.github.com/hishamhm/396c6dc9015813670d013ba0a4b5ab2a

Thanks, that clarifies a few things. Although I think the whole value aliasing thing only serves to confuse things again and I'm not sure that there is a point in mentioning it. As far as I know it's not a feature specific to Teal.





> @Zipperdoodle in this case in particular, `local type MyAlias = MyNamespace.MyGenericRecord<MyEnum>` currently produces a new unique type in the `next` branch, because `<>`-application is being handled as a type constructor. So, `MyAlias` and `MyNamespace.MyGenericRecord<MyEnum>` are not the same same type.
> 
> A type declaration without generic application produces a type alias. Therefore, `local type MyAlias2 = MyNamespace.MyGenericRecord` produces a type alias, meaning that `MyAlias2<MyEnum>` and `MyNamespace.MyGenericRecord<MyEnum>` are the same type.
> 
> This is what the current implementation does, but I'm not fully convinced this is the way to go (I'm debating whether both should be type aliases).

I can see both being useful. But I definitely think there should be a way to declare aliases for long-ass generic instances, maybe even for partial applications, and preferably for anything else as well. That's one thing I really miss. I love that Teal has generics, but I hate using them because of their unavoidable verbosity and endless repetition. And that seems like such a shame for such a useful feature. Maybe it should be explicit in the language when something is an alias vs. a new type, for example by having a separate "alias" keyword or something, sothat you can have use of both features and semantics. Create a new type when that's what you need, create an alias when that's what you need. I don't know, just thinking out loud.

On a related note, would there any way to make the use of lambda's/anonymous functions more concise? Plain Lua is verbose enough with the mandatory use of the keywords "function", "return" and "end", but Teal takes it to another level with mandatory type annotations in function signatures. I find myself actively avoiding such conveniences as map/filter/reduce for of this exact reason. I'm thinking it should at least be possible to do some type inferencing at the call site according to the expected argument and return types of the function being passed in. And maybe you could even introduce a short and sweet syntax that avoids the need for "function", "return" and "end" (although this might be too un-Lua-like for some people's tastes).
