### ISSUE TITLE
How do i solve this error? : argument 2: got type constant (alias), expected constant

### ISSUE THREAD

**Issue by elMuso** [teal-language/tl#766]
Currently porting the Defold annotations library to teal. However i have found a nasty error that is not allowing me to finish 

`argument 2: got type constant (alias), expected constant`

The code that reproduces it:

```
global record constant userdata end
 
global record gui
    type ADJUST_FIT = constant
    set_pivot: function(node: any, pivot: constant)
end 

global function main() 
    gui.set_pivot('', gui.ADJUST_FIT)
end        
```

What's this "(alias)" ? I have looked on the tutorial and issues and i have not found anything related. I could make constant a type and replace the first line with `global type constant = any` and it works... but it also allows anything to be valid. 

Is there a solution for this?

**Comment by hishamhm** [comment]
Is this what you mean?

```
global record constant userdata end
 
global record gui
    ADJUST_FIT: constant
    set_pivot: function(node: any, pivot: constant)
end 

global function main() 
    gui.set_pivot('', gui.ADJUST_FIT)
end        
```
