### ISSUE TITLE
Add a flag to disable compat53 code insertions

### ISSUE THREAD

**Issue by ryanford-frontend** [teal-language/tl#78]
As a feature request can we get a way to disable the automatic compat53 shimming and assume 5.3 or the most recent support version? The added code like:
```lua
local assert = require('compat53.module').assert or assert; local pairs = require('compat53.module').pairs or pairs;
```
is breaking my code in fengari and I'd not like to add compat53 if the only supported version is 5.3 anyway.

**Comment by hishamhm** [comment]
> Thus, I would add skip_compat53 as a boolean to Env, and expose init_env as tl.init_env(lax: boolean, skip_compat53: boolean): Env. I'd then add a boolean flag (e.g. --skip-compat53) that can be set from the command line, and is then passed in env to tl.process.

Sounds like a great plan! Go for it! :D
