### ISSUE TITLE
tl check fails when a function variable gets named

### ISSUE THREAD

**Issue by rayanamal** [teal-language/tl#780]
Hi there.
I've encountered this type of completely unreasonable bug a few times before, and tossed it off as the result of lack of soundness in tl type system (is it?)  or a yet to be implemented feature. But this one is really weird.

I wrote a declaration file for the `outcome` library. Both are attached in [name-bug.zip](https://github.com/user-attachments/files/16661014/name-bug.zip). If you uncomment the 22nd line instead of 23rd line, tl errors with `syntax error, expected one of: ')', ','`. The only difference the former has with the latter is a function argument being named:

22nd line:
```lua
mapOrElse: function<U>(self: Option<T>, defaultProvider: function(): U, mapFunction: function(T): U): U
```

23rd line:
```lua
mapOrElse: function<U>(self: Option<T>, defaultProvider: function(): U, function(T): U): U
```

**Comment by hishamhm** [comment]
@rayanamal There are some ambiguities that arise from our function type syntax. The parser is interpreting `U, mapFunction` as two returns from `defaultProvider`, and then the following `:` becomes a syntax error. The solution for that is to put the returns in parentheses, like this:

```lua
mapOrElse: function<U>(self: Option<T>, defaultProvider: function(): (U), mapFunction: function(T): (U)): U
```

**Comment by hishamhm** [comment]
@rayanamal I have added a 3-token lookahead to the parser when reading arguments, which solves this problem. Your original code now parses correctly in the latest git `master`, even without the parentheses. For compatibility with the current release, the parentheses serve as a workaround.

**Comment by rayanamal** [comment]
Alright, thank you very much. I encountered the same issue in other places as well since I wrote this issue and this fix solved them.
