### ISSUE TITLE
Allow getting type information from file without requiring it

### ISSUE THREAD

**Issue by Hedwig7s** [teal-language/tl#789]
Sometimes you have a module that uses types from another module but doesn't actually need the functionality for it (for example: a module that defines functions that use types from another module which is called elsewhere)

Right now there are 2 options that I know of (if there's another way I'd love to know):
Make a type declaration file (which isn't preferable if you want to define the types where they're made and can be inconvenient)
Forward-declare type without any information (provides no type information within file)

If a better way to handle this situation could be considered that would be great

**Comment by hishamhm** [comment]
You can do that today with

```
local type mod = require("mod")
```

This will load the type info without outputting a `require()` call in the generated code.
