### ISSUE TITLE
[next] Partial input crash in `tl types`

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#795]
The following partial input crashes `tl types`, when using the `next` branch:

```lua
function MyRecord:send_rpc(id: integer)
   self:_encode {
      result = json_nullable(t, -- missing parenthesis
   }
end

function MyRecord:send_rpc_error(name: lsp.ErrorName)
end
```

```
tl types crash.tl
```

```
Internal Compiler Error: tl.lua:11888: assertion failed!
```

**Comment by pdesaulniers** [comment]
> How are you detecting when to check and report syntax errors? 

I use `tl check` every once in a while, which does report syntax errors in this scenario.

> tl types returns no output on master, but it does return some type info for the file up until the crash now.

> I can restore the original behavior of returning nothing in case of pcall errors.

No, I think the new behavior is correct, since we want as much type information as possible, even though the source code is invalid. 

Right now, I show a warning is vscode whenever `tl types` returns nothing, since this generally indicates some sort of crash:

```
[Error]
`tl types` has returned an empty response.
```

**Comment by hishamhm** [comment]
Great! All's good in `next` then!
