### ISSUE TITLE
Records inheritance

### ISSUE THREAD

**Issue by b0ryakha** [teal-language/tl#803]
I would like to be able to inherit records to get rid of code duplication.

Simple example:
```lua
global record Entity
    x: number
    y: number
    vel_x: number
    vel_y: number
end

global record Player
    x: number
    y: number
    vel_x: number
    vel_y: number
    name: string
end
```

I would like a similar syntax:
```lua
global record Entity
    x: number
    y: number
    vel_x: number
    vel_y: number
end

global record Player extends Entity
    name: string
end
```

This is necessary for convenient inheritance in lua using metatable, here is a simple example, but in a real project you have to declare many variables and functions in each heir, which causes great discomfort.
Perhaps the records inheritance function is already there, but I didn't find anything in the documentation.

**Comment by Andre-LA** [comment]
In the next version there will be a interfaces feature which solves that on the type safety side.

https://github.com/teal-language/tl/blob/8f63a8636e27b8a3d9c9fd6d120537d61a9a4767/tl.tl#L1675

However this would not automatically create a constructor that uses the __index metatable or something like that.

**Comment by b0ryakha** [comment]
I did not understand how the code on the link was supposed to help me, I will wait for the new version thanks for the answer.

**Comment by euclidianAce** [comment]
Once the next version is out you'll be able to do the following:

```
global interface Entity
   x: number
   y: number
   vel_x: number
   vel_y: number
end

global interface Player is Entity
   name: string
end
```

And if you want to be able to use the `is` operator then you can add a `where` clause that checks if `self.name` is not nil

```
global interface Player is Entity where self.name
   name: string
end
```

Then you'll be able to do this if you'd like:

```
local x: Entity = -- ...
if x is Player then -- ...
```
