### ISSUE TITLE
[next] Generic type not recognized when loaded via another file

### ISSUE THREAD

**Issue by svermeulen** [teal-language/tl#804]
The following produces the error `unknown type Foo<integer>`.  Moving contents of the file 'foo' directly into this file does not have this error.  This only occurs when type checking using teal from next branch.

```lua
-- This works
-- local record Foo<T>
--    bar: T
-- end

-- This does not, where contents of foo is:
-- local record Foo<T>
--    bar: T
-- end
-- return Foo
local Foo <const> = require("foo")

local foo:Foo<integer>

foo = {
   bar = 5
}

print(string.format("bar: %d", foo.bar))
```

**Comment by hishamhm** [comment]
@svermeulen Thank you for the report and test case! It's now fixed in `next`.
