### ISSUE TITLE
Bug in "tl check" (cannot redeclare global with a different type)

### ISSUE THREAD

**Issue by b0ryakha** [teal-language/tl#805]
When I use tl check on a project, it finds an incomprehensible error:
"sources\oop.tl:5:8: cannot redeclare global with a different type: previous type of extends is function<Child>(Child, Base, ...: <any type>): Child"

The error began to appear only after I moved some files (which use oop.tl) to the widgets subfolder.
At the same time, tl gen correctly generates lua files and everything works.

Example of the project structure:
```
sources/
├── oop.tl
├── 1.tl
├── 2.tl
├── ...
├── tlconfig.lua
└── widgets/
    ├── 3.tl
    ├── 3.tl
    └── ...
```

tlconfig.lua:
```lua
return {
    include_dir = {
        "sources", "sources/widgets"
    },
}
```

oop.tl:
```lua
local record Base
    new: function<Self>(Self, ...: any)
end

global function extends<Child>(child: Child, base: Base, ...: any): Child
    local index = {}
    
    for k, v in pairs(base as table) do index[k] = v end
    for k, v in pairs(child as table) do index[k] = v end

    return setmetatable(base:new(...), { __index = index })
end
```

building:
```bash
tl check sources/*.tl &&
tl check sources/widgets/*.tl &&
tl gen sources/*.tl &&
tl gen sources/widgets/*.tl
```

**Comment by hishamhm** [comment]
Do you have an example of the code of the module that requires oop.tl?

**Comment by b0ryakha** [comment]
Simplified example:
```lua
require("widget")
require("oop")

global record Label
    text: string
end

function Label:new(parent: Widget, text: string): Label
    local self = extends(Label, Widget, parent)

    self.text = text or ""

    return self
end
```

widget.tl in 'sources' folder.

**Comment by hishamhm** [comment]
I tried to but I still cannot reproduce this error. I see that the code in the second comment does `require("widget")`, but you did not include it. What is `widget.tl`?

**Comment by b0ryakha** [comment]
This problem was on the last version of Teal, now there is no problem, maybe the interfaces fixed it =)
