### ISSUE TITLE
Mismatch in line number betwen tl and generated lua

### ISSUE THREAD

**Issue by svermeulen** [teal-language/tl#807]
Running "tl gen" with the following code:

```

local record Foo
end

function Foo:greet(
      greeting:string)
   print(greeting)
end
```

Produces this lua:

```

local Foo = {}


function Foo:greet(   greeting)
   print(greeting)
end
```

I would have expected greeting to be on the next line similar to the teal file.  I encountered this issue because I noticed my stack traces were sometimes 1 or 2 lines off from what I was expecting, since all it takes is one of these cases at top of the file to throw off stack traces for the rest of the file.

Tested both in next branch and also whatever is currently on luarocks

**Comment by hishamhm** [comment]
@svermeulen Thanks for the report and testcase! Fixed!
