### ISSUE TITLE
Inference of `__gt` and `__ge` from `__lt` and `__le` metamethods

### ISSUE THREAD

**Issue by kprimice** [teal-language/tl#809]
### Problem:

In Lua, the `>` and `>=` operators don’t have dedicated metamethods (`__gt` and `__ge`). Instead, they are logically inferred from `__lt` and `__le` (i.e., `a >= b` is equivalent to `not (a < b)`).

However, in Teal, using the `>` and `>=` operators for custom types (like `bint`) results in a type error, even when `__lt` and `__le` metamethods are defined. 

### Example:

```lua
global record BigInteger
  metamethod __lt: function(self: BigInteger, y: BigInteger): boolean
  metamethod __le: function(self: BigInteger, y: BigInteger): boolean
end

-- Works:
if a <= b then print("a <= b") end

-- Error: Teal does not infer __ge from __le
if a >= b then print("a >= b") end

```

### Proposal:

Teal should infer `__gt` from `__lt` and `__ge` from `__le`, just like Lua. This would streamline code and ensure consistency with Lua's behavior.

This change would ensure that operators like `>=` and `>` are automatically usable when `__le` and `__lt` are defined.

**Comment by hishamhm** [comment]
@kprimice Good news! This is already fixed in current `master`, and the behavior you expect will be available in the upcoming release!
