### ISSUE TITLE
Type check bug.

### ISSUE THREAD

**Issue by b0ryakha** [teal-language/tl#811]
The error appeared in the new version, perhaps there is a keyword for it, but I did not find it in the documentation.

No error:
```lua
global record R end
global function f(value: any)

local r: R = {}
f(r)
```

Error by tl check: argument 1: R is not a MyAny. 
```lua
global type MyAny = any
global record R end
global function f(value: MyAny)

local r: R = {}
f(r)
```

**Comment by hishamhm** [comment]
This behavior is intentional. The type system now handles nominal types based on primitives as new distinct type declarations.  See #708.
