### ISSUE TITLE
Unable to use method in interface `where` clause

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/tl#812]
I'm attempting to update the luv type definitions in teal-types where there is a base `Handle` with a method `get_type(): string, integer`, but tl errors with a somewhat confusing message.

I remember being able to do this earlier in the `next` branch, so something must have regressed

repro:

```lua
local interface A
	get_type: function(A): string
end

local interface B is A where self:get_type() == "b"
end

local b: A = {
	get_type = function(): string return "b" end
}


if b is B then
	print("woaw")
end
```

```
$ tl check scratch.tl
========================================
1 error:
scratch.tl:5:35: cannot index key 'get_type' in self 'self' of type self
----------------------------------------
1 error
```

**Comment by euclidianAce** [comment]
I also assume this has to do with inheriting multiple interfaces since I can work around this with a cast:

```lua
local interface A
	get_type: function(A): string
end

local interface B is A where (self as A):get_type() == "b"
end

local b: A = {
	get_type = function(): string return "b" end
}


if b is B then
	print("woaw")
end
```

**Comment by hishamhm** [comment]
> in self 'self' of type self

hahaha indeed, "somewhat confusing" is an understatement here! 

Thanks for the repro! I'll look this up!

**Comment by hishamhm** [comment]
Fixed! Thanks!
