### ISSUE TITLE
Cannot use boolean variables as table keys

### ISSUE THREAD

**Issue by overcrook** [teal-language/tl#816]
Teal reports an error in this script:

```lua
local KEY_FALSE = false
local KEY_TRUE  = true

local foo = {
    [false] = "false",
    [true]  = "true",
}

local bar = {
    [KEY_FALSE] = "false",
    [KEY_TRUE]  = "true",     -- redeclared key false (previously declared at :10:5)
}

print(foo[false])
print(foo[true])

print(bar[KEY_FALSE])
print(bar[KEY_TRUE])
```

However, Lua runs this script fine without errors, as does Teal v0.14.1:
```
$ lua ./test.tl
false
true
false
true
```

This only occurs if the table is indexed by a boolean variable. There are no errors with variables of other types (integer, string, tables, ...).

Tested versions: 0.15.x, 0.24.0 and master branch.

**Comment by hishamhm** [comment]
Thanks for the report! It's now fixed in `master`.
