### ISSUE TITLE
Value incorrectly assigned as type nil when adding certain guards to function

### ISSUE THREAD

**Issue by svermeulen** [teal-language/tl#823]
Example:

```
local function foo(bar:string):boolean
   if bar == nil or #bar == 0 then
      return true
   end

   print(bar:upper())
   return false
end

foo("asdf")
```

Type checking the above produces error "cannot index key 'upper' in variable 'bar' of type nil (inferred at :4:4)" but only if the guard if statement is added

Tested using teal commit 0065786

**Comment by svermeulen** [comment]
Workaround is to use "not bar" instead of "bar == nil"

**Comment by hishamhm** [comment]
@svermeulen Should be fixed now! Thanks!
