### ISSUE TITLE
Placing interfaces in an included file produces error

### ISSUE THREAD

**Issue by svermeulen** [teal-language/tl#829]
The following works fine:

```
local interface IFoo
   bar: function(self)
end

local record Foo is IFoo
end

function Foo:bar()
   print("bar")
end
```

But when placing IFoo in a file like this:

```
local interface IFoo
   bar: function(self)
end

return IFoo
```

```
local IFoo = require("main.ifoo")

local record Foo is IFoo
end

function Foo:bar()
   print("bar")
end
```
We get error 'interfaces are abstract; consider using a concrete record' on the require line

**Comment by Hedwig7s** [comment]
Similar to #825 not sure if the same

**Comment by svermeulen** [comment]
Can confirm that "local type IFoo = require" does fix it.   That is an easy fix.  Feel free to close issue if that's the intended way to do this.

**Comment by hishamhm** [comment]
> Feel free to close issue if that's the intended way to do this.

Yes, that's the intended way, but I'll leave it open since I think it's worth reworking the error message.
