### ISSUE TITLE
Cannot treat records themselves as their interface types

### ISSUE THREAD

**Issue by svermeulen** [teal-language/tl#830]
Example:

```
local interface IFoo
end

local record Foo is IFoo
end

local function bar(_value:Foo)
end

local function qux(_value:IFoo)
end

local foo:Foo

bar(foo) -- works
bar(Foo) -- works

qux(foo) -- works
qux(IFoo) -- works
qux(Foo) -- This produces error "argument 1: got Foo, expected interface IFoo"
qux(Foo as IFoo) -- works
```

I noticed that you can pass the record table itself as a parameter to a function where this parameter has type hint of the same record.  You can do the same with interface tables, but you can't pass record tables in that case with a cast.

**Comment by hishamhm** [comment]
`qux(IFoo)` shouldn't work, and `qux(Foo)` should. d0a371743f37df9c2445039bbe6657d962557b4b takes your testcase (thanks!) and adds a bunch of test cases.
