### ISSUE TITLE
is detect type bug?

### ISSUE THREAD

**Issue by ghost319** [teal-language/tl#834]
```lua
local function test(t: {integer})
end 

local map: {integer:integer} = {[3] = 2}
test(map)  -- no type errors here

**Comment by hishamhm** [comment]
Still, thanks for the feedback! It would probably be a good idea to add some docs explaining those compatibility rules.

**Comment by ghost319** [comment]
@hishamhm But it is easy to make mistakes in development and there are no prompts
```lua
local function test(t: {integer})
    for _, _no in ipairs(t) do
        print(_no)      -- not executed
    end
end 

local map: {integer:integer} = {[3] = 2}
test(map)  -- no type errors here
```
So how to effectively avoid this situation

**Comment by lenscas** [comment]
@ghost319 Your code and this behave the exact same way

```lua
local function test(t: {integer})
    for _, _no in ipairs(t) do
        print(_no)      -- not executed
    end
end 

local arr: {integer} = {nil,nil,2}
test(arr)
```

For as long as any value can be nil there is no difference between a `{T}` and `{number:T}`

Because right now a `{T}` is allowed to have holes
which makes it the same as a `{number:T}`
