### ISSUE TITLE
tl .24.1 - bad argument to popen

### ISSUE THREAD

**Issue by SlashScreen** [teal-language/tl#839]
I just now updated tl to the latest version as of writing, and it gives me the following error: 
```
[Error] C:\Users\talle\scoop\apps\lua\current\lua54.exe: ...\current\rocks\lib\luarocks\rocks-5.4\tl\0.24.1-1\bin\tl:672: bad argument teal-language/vscode-teal#2 to 'popen' (invalid mode) stack traceback: [C]: in function 'io.popen' ...\current\rocks\lib\luarocks\rocks-5.4\tl\0.24.1-1\bin\tl:672: in upvalue 'cd' ...\current\rocks\lib\luarocks\rocks-5.4\tl\0.24.1-1\bin\tl:689: in upvalue 'normalize' ...\current\rocks\lib\luarocks\rocks-5.4\tl\0.24.1-1\bin\tl:724: in upvalue 'already_loaded' ...\current\rocks\lib\luarocks\rocks-5.4\tl\0.24.1-1\bin\tl:738: in field '?' ...\current\rocks\lib\luarocks\rocks-5.4\tl\0.24.1-1\bin\tl:977: in main chunk [C]: in ?
```

The line in neal seems to be:
`local pd = io.popen("cd", "rb")`

**Comment by hishamhm** [comment]
@pdesaulniers Thanks for investigating!

> (though I assume this code path was intended for Windows, since cd doesn't typically output the current directory on Linux)

...which seems to be the case for @SlashScreen. According to the Lua 5.4 source code, `"rb"` is supported by `io.popen` on Windows when the `LUA_USE_WINDOWS` define is set. 

@SlashScreen How was this `lua54.exe` compiled? 

Does the error happen when using the `tl.exe` build from the [official release](https://github.com/teal-language/tl/releases/tag/v0.24.1)?

**Comment by SlashScreen** [comment]
@hishamhm lua54.exe is from the scoop PM for windows.
using the tl.exe seems to work as expected, as well as somehow restoring functionality to the vscode plugin when put in the directory with the code.

**Comment by hishamhm** [comment]
@SlashScreen in that case, my diagnostic is that somehow lua54.exe was compiled by scoop without the `LUA_USE_WINDOWS` define (which should have been autodetected in `luaconf.h` due to Windows compilers defining `_WIN32`). Looks like root cause for the problem lies in the scoop PM package, then.

**Comment by SlashScreen** [comment]
Hmm, okay. I'll have to take a look at that, then. was this calling method used in previous versions of teal? Since earlier versions worked just fine.

**Comment by hishamhm** [comment]
> Hmm, okay. I'll have to take a look at that, then.

Thank you!

> was this calling method used in previous versions of teal? Since earlier versions worked just fine.

No, they were missing the "b" option in `open` and `popen` calls on Windows, which we added in d210ff9fcf39f5981ab40969e1f6356712b7db86.

**Comment by SlashScreen** [comment]
I'm unable to test another lua build, because I have screwed up my lua and luarocks installation. I'll try again once I fix it.

**Comment by pbdot** [comment]
Also getting this with Lua 5.3, with the error coming up in the VSCode extension
```
[Error]
C:\Lua\bin\lua.exe: c:\lua\lib\luarocks\rocks-5.3\tl\0.24.1-1\bin\tl:672: bad argument #2 to 'popen' (invalid mode)
stack traceback:
	[C]: in function 'io.popen'
	c:\lua\lib\luarocks\rocks-5.3\tl\0.24.1-1\bin\tl:672: in upvalue 'cd'
	c:\lua\lib\luarocks\rocks-5.3\tl\0.24.1-1\bin\tl:689: in upvalue 'normalize'
	c:\lua\lib\luarocks\rocks-5.3\tl\0.24.1-1\bin\tl:724: in upvalue 'already_loaded'
	c:\lua\lib\luarocks\rocks-5.3\tl\0.24.1-1\bin\tl:738: in field '?'
	c:\lua\lib\luarocks\rocks-5.3\tl\0.24.1-1\bin\tl:977: in main chunk
	[C]: in ?
```

Lua built with https://github.com/RealmForge/luawinmake and tl installed through luarocks

**Comment by hishamhm** [comment]
Should we just remove that `b` from the `io.popen` call in `tl:672`? We're only reading a single line of text anyway.

**Comment by pdesaulniers** [comment]
It seems like support for the `b` modifier on Windows was added in Lua 5.4: https://github.com/lua/lua/commit/754ca0060fcac9829cfb90dd68d96cbe14aa84f7

So, as far as I can tell, this modifier is not compatible with previous versions of Lua.

Initially, was this flag added to avoid a specific issue on Windows? Besides line breaks, does this flag somehow impact the way the compiler handles non-ASCII characters in paths?

**Comment by SlashScreen** [comment]
been a while, but IIRC removing the b didn't cause any problems on windows, but I didn't test thoroughly.

**Comment by hishamhm** [comment]
@pdesaulniers @SlashScreen thank you for the feedback!
