### ISSUE TITLE
Communication Channel Discussion

### ISSUE THREAD

**Issue by mrtnpwn** [teal-language/tl#87]
Teal should have its own Discord for discussing the language changes in a more "instant" way than GitHub issues, I can help with moderation ;)

**Comment by hishamhm** [comment]
I've never been a Discord user (or a IRC user for that matter), but then again, I didn't have Twitch account until last week. :wink:  How about we use this Github issue to see if there's community interest and if so, we go ahead with it? :smile:

**Comment by pdesaulniers** [comment]
I'm not sure if Discord is appropriate for a project like Teal (it's a proprietary chat platform geared towards gamers :thinking:) But then, maybe that would be the most convenient choice for most people...

Matrix is a nice FLOSS alternative. Otherwise, I think IRC / Freenode is fine too.

Some people also self host a Rocket.Chat instance, but that's probably a bit more complex.

**Comment by ash-nolan** [comment]
I'm more of a IRC fan (old man yells at cloud).

So count me as one vote for [Freenode](https://freenode.net/groupreg).

**Comment by ash-nolan** [comment]
Also @hishamhm we might want to change the issue name to "Communication Channel Discussion" or something.

**Comment by Andre-LA** [comment]
Matrix is nice, the best thing is that you can choose different front-ends.

Riot.im is good and has Discord-like features; Fractal is another nice matrix front-end.

Another also possible platform is zulip chat.
Rocket chat is awesome too, but it needs self-hosting (or use the paid plan).

**Comment by mrtnpwn** [comment]
A lot of open source projects use Discord for communication (check out Luvit, Svelte, Elixir or Yarn, for example).
The cool thing about Discord is that it feels like IRC: you got bots, native commands and channels. But you got other cool modern features like voice chat, images and embeds, and it's cross-platform, you can keep chatting even if you're on a roadtrip or something. It's a great choice for any project, you can keep in touch with everyone with ease and you can keep in touch with for example the GitHub repo using Webhooks.

Open source projects get a verified badge, custom URL and features that come with the verified badge (private voice channels servers, more custom emotes, etc)

**Comment by ryanford-frontend** [comment]
We can create a channel for Teal in the Lua Scripters discord (the one linked on lua.org) if people want to talk about it in the mean time.

**Comment by ildar** [comment]
I (a user) dislike Discord for it's proprietary&close nature. I suggest
using platforms that are easily federated, having bridges to other
communication platforms.

Ideal: Matrix, as having transparent bridges to Irc, Gitter, other
platforms,
Good: Gitter, classical addon to Github/gitlab/etc.
Classics: IRC

**Comment by hishamhm** [comment]
Those are all great insights! I imagine that Discord, Matrix, etc all attract somewhat overlapping and somewhat different audiences. As for myself, personally, I've never been very good at hanging out at chat rooms (IRC or otherwise), so honestly I'm not sure if I'll manage to be very active in any of the proposed options... But if anyone wants to go ahead and create a channel in any platform to discuss Teal, I'm happy to link it from the README.md (and I'll try to check them out!), I'd love to see the community self-organize and grow!

**Comment by ildar** [comment]
IMHO Gitter is best for non-hangers. Also good at spam-resisting.
I still suggest you to be the supervisor as a final authority.

**Comment by Andre-LA** [comment]
> Ideal: Matrix, as having transparent bridges to Irc, Gitter, other
platforms

> also as there's already LuaRocks Gitter room in the hood, gitter looks natural.

Maybe both with a bridge? Apparently is the case with luarocks too, but I'm not sure:
https://riot.im/app/#/room/#gitter_luarocks=2Fluarocks:matrix.org

**Comment by SinisterRectus** [comment]
Hey, just passing through and saw some consideration given to using Discord. Very cool. I'm not trying to encourage its use over Matrix/Gitter/IRC. I just happen to have a lot of experience with Discord, so I figured I'd leave my thoughts.

> I'm not sure if Discord is appropriate for a project like Teal (it's a proprietary chat platform geared towards gamers 🤔) But then, maybe that would be the most convenient choice for most people...

I see this come up occasionally, where people would rather not use a proprietary platform for an open source project. It is a fair conclusion, but then I wonder why people host their projects on a service like GitHub, which was [rated F by the FSF](https://www.gnu.org/software/repo-criteria-evaluation.html).

Discord was made for and (until recently) marketed towards gamers, but they have shed that concept and are now recognizing and embracing other users, especially during the coronavirus pandemic. Here are a few articles about that:

- https://blog.discord.com/helping-out-where-we-can-3a5fb7bac77a
- https://blog.discord.com/talking-to-each-other-during-covid-19-6ca471fbe5ac
- https://blog.discord.com/how-discord-is-bringing-people-together-e215bbd41ad9

Additionally, languages such as [Rust](https://www.rust-lang.org/community) and [V](https://vlang.io/) have official verified Discord communities and Discord has a specific [program for open source projects](https://discordapp.com/open-source). Teal might be too small to be verified at the moment, but Discord could be a good place to host a small community next to a giant like Rust.

**Comment by mwild1** [comment]
I'd be happy with XMPP, Matrix or IRC. All are open/decentralized, FOSS-friendly and bridge to each other.

I don't believe in basing an open-source community around a proprietary commercial platform.

**Comment by ildar** [comment]
Communities may be multiple and it's good. But only in case there's a big
enough user base spread on IRC/Gitter/Discord/Matrix etc. like for Rust.
Teal is still a niche language and we can't afford spreading. So I suggest
that most suitable is that which is most simple and obvious for developers
/programmers (the actual user base of Teal). I see only two satisfying the
criteria: IRC and Gitter.

**Comment by hishamhm** [comment]
I do recall seeing bridging between Gitter and Matrix (@daurnimator?) so if XMPP, Matrix and IRC can bridge to each other I assume they can talk to Gitter as well? So let's give this a try!

https://gitter.im/teal-language/community

I associated it with the teal-language github org (not sure what are the implications, but I assume this means that whoever admins the github org can have admin rights there, not sure). If more steps are necessary to enable bridging with other places, I can see how to provide access to whoever wants to set it up!

**Comment by daurnimator** [comment]
> I do recall seeing bridging between Gitter and Matrix (@daurnimator?) so if XMPP, Matrix and IRC can bridge to each other I assume they can talk to Gitter as well? So let's give this a try!

matrix was made to be the centre of all bridges. Though it never does look quite as pretty on other platforms.
I would say gitter is probably the worst option out of all of them.
Matrix + IRC will work well enough for most people.
Though discord (despite its proprietryness) has ended up winning for most programming language discussions (outside of the hardcode IRC users).

**Comment by hishamhm** [comment]
So I just took a peek at Matrix and looks like you _can_ bridge it with Discord even?

**Comment by ildar** [comment]
You can bridge Matrix to almost anything:
https://matrix.org/docs/projects/try-matrix-now/
The price may vary though: IRC, Gitter are free. For others you need to
deploy your own bridge (not VERY complicated though).
The difference is based on the ability of server-to-server userid
traversal... I'm a user so can't explain deeper details.

**Comment by hishamhm** [comment]
@ildar Ah, got it! 

Since we at least have something going now with the Gitter chat, I guess we can close this issue for now, and perhaps revisit this topic in the future if the community needs change?

Also, if anyone else has any other community channel they maintain and would like to promote, feel free to send a PR to add a mention in README.md, as long as that channel has a compatible CoC to the main project (which is a pretty standard one).

Thank you all for the input!

**Comment by mrtnpwn** [comment]
I'm going to close it, I'm glad at least we got some "fast" and instant way of communicating stuff
