### ISSUE TITLE
Use `...` of a variadic function in "normal" function

### ISSUE THREAD

**Issue by atticus-sullivan** [teal-language/tl#873]
Use-case: Writing a variadic function wich uses a binary function to reduce its arguments.

Example:
```lua
local function foo(a:string, b:string): string
    print(a,b)
end

local function bar(...: string): string
    return foo(...)
end
```
([playground](https://teal-playground.netlify.app/?c=bG9jYWwgZnVuY3Rpb24gZm9vKGE6c3RyaW5nLCBiOnN0cmluZyk6IHN0cmluZwogICAgcHJpbnQoYSxiKQplbmQKCmxvY2FsIGZ1bmN0aW9uIGJhciguLi46IHN0cmluZyk6IHN0cmluZwogICAgcmV0dXJuIGZvbyguLi4pCmVuZA%3D%3D) currently not showing the error until I do a change like removing and adding one parenthesis for example).

I'm not sure if this always should compile as `...` might be more/less than (in this case) two values, but commonly it is guarded (via `select('#', ...)`) that the argument count is `>=` (and usually in lua the additional arguments are just discarded).

As I think about this while writing this, maybe this is not quite a bug report but more seeking for guidance how to write something like this in current teal (just upgraded from `0.15.3` where the above was still working) and maybe a feature request (still not sure how to make this work in a type-safe manner though).

For now the only alternative I'm aware of is putting `...` in a table (this is not safe in case `nil` is involved though) and then access as an array.

**Comment by hishamhm** [comment]
There are some alternatives.

If you know that `bar` might be called with fewer than 2 arguments but your `foo` is fine with it, then you may want to specify that the arguments in `foo` are optional, and that will compile:

```lua
local function foo(a?: string, b?: string): string
    print(a,b)
end

local function bar(...: string): string
    return foo(...)
end
```

If you know that `bar` will always be called with at least 2 entries (assuming you also use `...` for other things in your code), then you may want to unpack the first two entries of `...` in the signature:

```lua
local function foo(a: string, b: string): string
    print(a,b)
end

local function bar(a: string, b: string, ...: string): string
    return foo(a, b)
end
```

If you want a more 0.15-like behavior, this still works:

```lua
local function foo(a: string, b: string): string
    print(a,b)
end

local function bar(...: string): string
    local a, b = ...
    return foo(a, b)
end
```

**Comment by atticus-sullivan** [comment]
Oh I really like your second solution. Combined with using `?string` and checking for `nil` in order to test if only one or two arguments were given.
