### ISSUE TITLE
Feature request: initial values in records

### ISSUE THREAD

**Issue by mtdowling** [teal-language/tl#876]
It would be neat if we could do something like this:

```lua
interface Component
    componentName: string
end

record UserData is Component
    componentName = "UserData"
end
```

And it was equivalent to something like:

```lua
record UserData is Component
    componentName: string
end

UserData.componentName = "UserData"
```

I suppose this would also work to ensure the value doesn't change?

```lua
record UserData is Component
    componentName <const> = "UserData"
end
```

**Comment by hishamhm** [comment]
A tricky thing is that it makes it look like all instances of that record will have that value.

By making it generate the following Lua...

```lua
local UserData = {}
UserData.componentName = "UserData"
```

...that would be adding a value to the field _in the "class" table_ for the record, but not in its object instances, which the extended syntax seems to suggest.

I think that the idea that one would write `local t: MyObject = {}` and that the `t` would end up with magic default fields set would be very alien for people coming from Lua. Having said that, Rust is adding syntax to trigger [adding default field values to a struct literal declaration](https://mastodon.social/@ekuber@hachyderm.io/113635428507188393), though I don't think that `{ .. }` syntax would work for us, given that `..` already has a very different meaning in Lua and Teal (also, even if any syntax was added to say "make me a table with the record defaults", in current Teal that would have to be optional, so forgetting to use it and just writing `{}` would be an easy footgun — in Rust all struct fields are mandatory so adding the shorthand syntax works).

**Comment by mtdowling** [comment]
Yeah, you're right. I was thinking it would be more akin to a static value of the record than an instance value per se. You'd have to use a metatable manually to make it behave like an instance value. I'll close this.
