### ISSUE TITLE
Instantiated generic type aliases sometimes parse incorrectly

### ISSUE THREAD

**Issue by lucillablessing** [teal-language/tl#881]
The following code typechecks just fine:
```lua
local record Foo<T> end
local record Bar<T> end

local type StringFoo = Foo<string>
local type StringBar = Bar<string>

local type Test = {StringFoo: StringBar}
```

However, it breaks as soon as one adds this line:
```lua
local test: Test = {}
```

`tl check` complains about "missing type arguments in `record<T>`", apparently misparsing `StringFoo` as being an alias for `Foo`.

It works when you change the type declaration of `Test` to this:
```lua
local type Test = {Foo<string>: StringBar}
```

**Comment by hishamhm** [comment]
Oh, this happens because the resolution of `T` happens on-demand, and `local record Foo<T> end` never uses `T`. If you change it to `local record Foo<T> dummy: T end`, then the error goes away, interestingly.

I'll look into a fix, thank you for reporting.
