### ISSUE TITLE
Support for LuaJIT BitOp

### ISSUE THREAD

**Issue by mtdowling** [teal-language/tl#882]
LuaJIT uses a built-in [BitOp](https://bitop.luajit.org/api.html) library, but the polyfills for the 5.1 `--gen-target` from Teal uses bit32. It would be great if Teal was able to support a flag specifically for LuaJIT support, or a `--gen-target` for it (though LuaJIT itself has various compatibility flags too). I don't have a concrete proposal for how to address this, but I would love to be able to write bitwise logic in my code that works for different versions of Lua.

**Comment by catwell** [comment]
For reference there has already been discussion of this (and a PR): https://github.com/teal-language/tl/pull/686

**Comment by mtdowling** [comment]
Thanks! Looks like there is an open issue still for this too, so I’ll close as a duplicate of https://github.com/teal-language/tl/issues/723
