### ISSUE TITLE
`self` should be a valid symbol by default for function definition with `:`

### ISSUE THREAD

**Issue by BLKTower** [teal-language/tl#884]
Giving:
```lua
local record mod
    foo1: function(self)
    foo2: function(self)
end

function mod:foo1()
end

function mod.foo2(self: mod)
end
```
From my understanding, `foo1` is the same as `foo2`. But in the generated type infos, the `self` is only a valid symbol in `foo2` scope. I feel it should also be a valid symbol in `foo1` scope by default?
Generated type info:
```
symbols:  [
  [ 1, 1, '@{', 6 ],
  [ 1, 14, 'mod', 10 ],
  [ 9, 1, '@{', 5 ],
  [ 9, 19, 'self', 14 ],
  [ 10, 3, '@}', 2 ],
  [ 10, 8, '@}', 0 ]
]
```

**Comment by hishamhm** [comment]
Fixed, thank you for reporting!!
