### ISSUE TITLE
Instantiated generic types within record type crash the compiler

### ISSUE THREAD

**Issue by lucillablessing** [teal-language/tl#888]
The following code typechecks successfully:

```lua
local record Generic<T>
   x: T
end

local type _Test = Generic<string>

local record Export
   type Test = _Test
end

return Export
```

However, if I instead write `type Test = Generic<string>` within `Export`, then the compiler crashes (not errors) with the following traceback (full file paths truncated to just the file name):

```
tl.lua:8040: attempt to index local 'found' (a nil value)
stack traceback:
        tl.lua:8040: in function 'resolve_decl_into_nominal'
        tl.lua:8085: in function 'resolve_typealias'
        tl.lua:13002: in function 'cbkind_after'
        tl.lua:4681: in function 'recurse_type'
        tl.lua:4675: in function 'recurse_type'
        tl.lua:4914: in function 'fn'
        tl.lua:4954: in function 'recurse'
        tl.lua:4812: in function 'fn'
        tl.lua:4954: in function 'recurse'
        tl.lua:4747: in function 'fn'
        tl.lua:4954: in function <tl.lua:4929>
        (tail call): ?
        tl.lua:13311: in function 'check'
        tl.lua:13447: in function <tl.lua:13423>
        (tail call): ?
        (tail call): ?
        tl:239: in function 'process_module'
        tl:739: in function '?'
        tl:977: in main chunk
        [C]: ?
```

While I could just define `Test` outside `Export`, this causes a separate issue where other modules importing `Export` will claim that `Export.Test` is not a `Generic<string>`.

**Comment by catwell** [comment]
I [found the fix for this](https://github.com/catwell/tl/commit/bffd71f0abe5138be2d3ff23bccb02d42eb97988) (I can add a test and submit a PR if you want).

However I was surprised this happened, until I remember that `nil` is still a valid value for all types. Non-nilable types would have caught this one.

**Comment by hishamhm** [comment]
@catwell yes please! Thank you!

I still think the generics model has some other issues with type aliases, but I'll try addressing them elsewhere.

**Comment by catwell** [comment]
Done (I was editing my comment at the same time you posted this.)

**Comment by catwell** [comment]
@hishamhm I saw you merged the PR already but an alternative fix could be to always return the second value in `find_nominal_type_decl`:

![Screenshot From 2024-12-31 15-15-24](https://github.com/user-attachments/assets/bbf37948-375f-44a0-8a2b-79a7c4485747)

Do you think this is cleaner?
