### ISSUE TITLE
Proper 'module not found' error when running `tl check`?

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/tl#96]
This doesn't throw an error:
```lua
local test = require("this_module_doesnt_exist")
```
Maybe `tl check` should try to resolve modules, and throw an error when it can't? 

(In that case, I think it would be impossible to dynamically pass a module name to `require` at runtime. The argument would need to be a constant string literal. Not sure if that's a deal-breaker)

**Comment by hishamhm** [comment]
> (In that case, I think it would be impossible to dynamically pass a module name to require at runtime. The argument would need to be a constant string literal. Not sure if that's a deal-breaker)

`tl` doesn't even try in that case, it automatically resolves the return type of `require(not_a_literal_string)` to UNKNOWN.

> Maybe tl check should try to resolve modules, and throw an error when it can't?

Agreed, it should produce an error! (and resolve the type to UNKNOWN for the rest of the typechecking, I guess)
