### ISSUE TITLE
_ENV semantics

### ISSUE THREAD

**Issue by Mehgugs** [teal-language/tl#99]
As I'm sure you're aware lua has a special local variable `_ENV` which determines the place from which non-local references are looked up. By default this variable is an upvalue from the outer scope, being initialized to `_G` in the outermost scope of the program. Things get interesting when this value is assigned to: 

```lua
local some_table = {}
local assert = assert

local _ENV = some_table 

example = "Not globally available"
function errors() return print"print is now unbound" end

assert(example == some_table.example)
```

This also works naturally in function arguments:

```lua

local function example(_ENV)
  return "This is a "..adjective.." example!" 
end

print(example{adjective = "weird"}) -- > This is a weird example!
```

Are there any plans to tackle this in teal?

**Comment by hishamhm** [comment]
That's a great question.

And the answer is a firm no, I don't plan to support neither _ENV or setfenv. This is an explicit non-goal.

If parts of your application need to do dynamic stuff like this, I recommend dropping back to Lua. In a sense, this is not unlike a C application that drops into assembly fot lower-level parts. Teal can and will continue to interoperate with Lua modules, but the Teal side of things assume a well-behaved, statically determinable environment.
